frontend/components/bottom-buttons/js/bottom-buttons.component.ts
frontend/components/issues/js/issues.service.js
frontend/components/tree/js/tree.component.ts
frontend/components/tree/js/tree.service.ts

This should speed up showing of issues by about 3 times. It's still not perfect (2-3 seconds for bigger models with complex show/hide groups) but it doesn't mess with any core logic of TreeService.
Premises:
We reset the Tree state before doing certain operations (i.e. showAllTreeNodes) and this updates the model also. This isn't necessary as we immediately impose our new state on the tree and then show/hide the bits of the model we need to. Using a flag we can decide if we want to update the model or just the state.
I also unwound updateParentVisibility to not be recursive.
The next big bottle neck is we have no heuristic for not going up paths we've already checked so we traverse up the tree more times then we need to updating parents. Anyway, one for another time.

ISSUE #719 - Reduce issues load times to around ~1/3 of previous

---

backend/models/group.js

This is fixed.
The problem is that these objects are under the root node; with no metadata associated with them(hence no IFC GUIDs), thus they were ignored and chucked away during the shared id to IFC GUID conversion.
So my fix is to add a set recording the set of shared IDs presented when we create this group, remove all the mapped shared IDs, anything that is left, add them into the object array.
@Charence  please make sure it's ok!

ISSUE #764 Objects modelled in root node/space 

---

backend/models/group.js

Shared IDs are being saved as strings if it is not a IFC model

ISSUE #848 sharedID is being saved as string

---

backend/models/userBilling.js
backend/test/unit/models/payment.js

This issue addresses 2 things:
- cancelAgreement() is called when the user unsubscribed to 3D Repo. As he/she has already paid for the service we shouldn't wipe their paypal entry - instead we should let it expire naturally... 
- Since we are not wiping the entry, we need to make sure we don't count the expired/soon to expire subscriptions  if the user re-subscribes again (for proRata calculation purposes). An unsubscribed account has no billingAgreementId so we can base it on that.

ISSUE #859 only look at paypal subscriptions if there is a billingAgreement ID

---

backend/models/user.js
scripts/db_migrations/v2.10/subscriptionMigration.js

At the moment, we determine someone's start date in 3D Repo by looking at when we create the `BASIC` subscription.
This will be gone in the new subscription refactoring.
We should record this properly and just have a `createdAt` on customData of the user bson object to record when the person actually signs up (`BASIC` wasn't 100% reliable to begin with...)
2 tasks involved:

ISSUE #874 add user createdAt field + db migration to harvest this from Basic sub

---

backend/models/group.js

Do not include transformations when converting IFC GUIDs to shared_ids.
This is to avoid hiding too much when there are visible objects within transformations that share an IFC GUID with IFC spaces.

ISSUE #885 - Do not include transformations when converting IFC GUIDs

---

backend/models/group.js
backend/routes/group.js
frontend/components/groups/js/groups.service.ts

This fixes #902
Speed up the time it takes to save groups by removing mongoose from `updateAttrs` function
- Replace mongoose call with a db `update` query.
- Changed what is returned by createGroup/editGroup end points. Instead of returning the whole group (cleaned) object, we only return ID. Reasons being:
- if `objects` array is massive, we're passing around a lot of data.
- `clean` is a pretty slow process, and only works in a mongoose schema, since we ditched it whilst updating we lost the info (We could reconstruct it with a vanilla js object, or fetch the updated record if necessary.  But so far I don't think it is needed)
- `objects` array returned isn't even correct to begin with (`ifc_guids` are not translated.)
- The user who called edit/create already has the latest group …

ISSUE #902 Improve Group saving time

---

backend/models/history.js
backend/routes/model.js
frontend/components/compare/js/compare.service.ts

`getHeadRevisions` in `models/history.js` in the backend was what caused the sorting error.
After further examination, the return value doesn't seem to be used at all.
- `getHeadRevisions` is only called by `routes/model.js` when the user fetches the model settings.
- the returned value is assigned to the json object with key `headRevisions`, this is only ever used in the compareService.
- The compare service utilises this to determine the head revision's id and tag in `getCompareModelData`, it is returned within the js object as `headRevision` and `headRevisionTag`
- git grep shows that these 2 fields aren't used anywhere. So I removed the whole thing.

ISSUE #908 remove unused function

---

backend/VERSION.json

We can no longer support the old VR due to group schema changes
Changes have been made in unity to support the new group schema. This issue updates the supported version to force the client to use the latest desktop VR viewer

ISSUE #920 version bump on unity VR

---

frontend/components/groups/pug/groups.pug

This fixes #935
Groups sometimes don't render in Firefox because it thinks theres duplicate groups. This fixes it
Open Laika0427/61b7834c-fb26-4668-ba9e-221ffffaf140/issues/e9ab3d50-4a21-11e8-9dfb-39b5c06ae677

ISSUE #935 - Groups sometimes don't render in Firefox 

---

frontend/components/issues/js/issue.component.ts

This fixes #927
Current the update issue function fails because it is not bound to the surrounding object.
Update an issue from another window/user and make sure that it doesn't throw an error in the console

ISSUE #927 - Bind this to  the handleIssueChange

---

frontend/gulpfile.js

This fixes #941 
Hot reloading isn't working, this fixes it
Run `yarn run watch` then change a TypeScript file, the page should reload

ISSUE #941 - Fix watching for JavaScript

---

frontend/tslint.json

This fixes #948
This is stopping things from being merged 
For in loops without if clauses don't cause errors

ISSUE #948 - Remove forin TSLint rule

---

frontend/globals/unity-util.ts

This fixes #952
Added a check for UnityUtil.viewer before checking its properties. This was breaking the embedded viewer demo as the demo does not assign an object to UnityUtil.viewer.
Embedded viewer should now work without breaking.

ISSUE #952 Hotfix unityUtils for embedded viewer

---

frontend/globals/unity-util.ts

This fixes #919
This should catch a wider array of Unity errors
This is quite hard to replicate, but should catch errors in production/dev

ISSUE #919 - Include other culprits in unity error list

---

.travis.yml

This fixes #954
Infrastructure tests breaks due to `sudo service rabbitmq-server stop` failing.
This is due to removing graphics magick means removing the only sudo command within the yaml file, thus sudo is disabled.
Also removed some useless commands within travis.yml.
Travis should now pass.

Issue 954 - remove installation of graphicsmagick from travis

---

backend/models/group.js
frontend/components/groups/js/groups.service.ts

This fixes #960
The frontend RGB only accepts integers 
Send an API request with floats, see if it saves as integers and renders correctly in the viewer groups list

ISSUE #960 - Always convert colours to integers

---

backend/models/helper/model.js
backend/response_codes.js

This fixes #982 
Add error message for the new bouncer code created in https://github.com/3drepo/3drepobouncer/issues/251
A massive model that exceeds 1030000 nodes will now return the new error message "Import failed: Too many objects, consider splitting up the model" (I'm not sure if we have a file big enough for this test.)

ISSUE #982 add error code

---

frontend/components/compare/js/compare.component.ts
frontend/components/compare/js/compare.service.ts

This fixes #985
- Compare tab's visibility icon is no longer synced with the tree. (Instead it's intended to set the model status once the comparison starts)
- Fix the problem where the base model doesn't hide when it was used as comparison model, then reverted back to base.
- Fix the problem where some base models are still shown when it should be hidden
- Also removed some redundancy
- [this](https://github.com/3drepo/3drepo.io/pull/980#issuecomment-390151876) should now pass
- Also [this](https://github.com/3drepo/3drepo.io/issues/1003)

Issue 985 - clash model load comparison fixes

---

frontend/components/compare/js/compare.component.ts
frontend/components/compare/js/compare.service.ts

This fixes #1009
The code to load models when it is in diff + non federation model mode is a bit crazy:
- It tries to find the revision from the baseModel, looking for a field that doesn't exist
- It then loads the target model base on this revision name
- It also takes in account and model parameters and load the target model base on that information instead of what's inside the targetModel state.
This is fixed by:
- look at the target model property instead and call load comparator model base on that information
- removed redundant parameters
- Target model should now be loading the model of the desired revision

ISSUE #1009 fix diff loading the wrong model

---

frontend/components/panel/pug/panel-card.pug
frontend/components/viewpoints/js/viewpoints.component.ts
frontend/components/viewpoints/js/viewpoints.service.ts

This fixes #1040 
- Fix viewpoint thumbnail when viewpoint is created
- Fix viewpoint card state after viewpoint is created
- Create a viewpoint: thumbnail should appear and back arrow should revert to viewpoint icon

ISSUE 1040 - Viewpoint card bug fixes

---

frontend/components/home/js/state-manager.service.ts

This fixes #1062
- Added IssuesService as one of the services to reset when the state changed
- go into a model, toggle subModel issues/closed issues
- go back to teamspace and open another model, subModel/closed issues should no longer be shown

Issue 1062 - fix bug where issues toggle states are not resetting

---

frontend/components/groups/js/groups.component.ts
frontend/components/groups/js/groups.service.ts

This fixes #1111 
Fixes the override all flag when you go back from editing a group
Set override all , edit a group, comeback. Should stay still with override all.

ISSUE #1111 - Fix the override all flag when you go back from editing a group

---

frontend/components/compare/js/compare.service.ts
frontend/components/issues/js/issues.service.ts
frontend/components/tree/js/tree.component.ts
frontend/components/tree/js/tree.service.ts
frontend/globals/unity-util.ts

This fixes #1135
Various effort to optimise tree selection code.
using this model: (carmen/d0eba0cc-989b-4e84-a7a5-8a455e10ff68)
- selecting objects should not take forever anymore.
- expanding/collpasing the tree should have minimal delay
- clicking on objects before tree is ready should no longer through an error on console log(it's now waiting on treeReady promise before proceeding)
- Should work fine on other models too!

Issue 1135 - Tree improvement

---

backend/response_codes.js

This fixes #1178
Error code 6 is showing up as unknown error because responseCode.js calls it `STASH_GEN_FAILED` instead of `FILE_IMPORT_STASH_GEN_FAILED`
Error 6 from bouncer should now display correctly.

ISSUE #1178 fix typo which stops errorCode 6 from showing

---

frontend/components/compare/js/compare.component.ts

This fixes #1197
- There seems to be a bug in `md-radio-button` where `ng-disabled` doesn't actually work (see [here](https://github.com/angular/material/issues/2658))
- To work around it, I added a check on the method that is being called by `ng-click`
- You should no longer be able to click the radio button when it looked disabled
- It should still work when it should be enabled

Issue 1197 - Fix radio button on compare card

---

frontend/components/groups/css/groups.css
frontend/components/groups/pug/groups.pug

This fixes #992 
This branch resolves the issue where the group description was being cut in the Firefox web browser 
The spacing in between the group meta, has also been reduced.
- **Previous Group Description**
- **After Group Description**

ISSUE #992 - Improved spacing, Group Description text fix

---

frontend/components/viewer/js/multi-select.service.ts

This fixes #1220
Add key code 224 support on multiselect service.
- firefox on mac should be able to accumulate objects 
- other platforms/browsers should be unaffected

Issue 1220 - fix multi select on firefox on mac

---

scripts/db_migrations/v2.20/upload_models_s3.py

This fixes #1217
Read off file length from gridFS entry and store it in the reference bson
- the reference bson saved should now contain a size entry

Issue 1217 - add a file size number to migration script

---

backend/routes/issue.js
frontend/components/groups/js/groups.component.ts
frontend/components/issues/js/issues-list.component.ts
frontend/components/panel/js/panel.service.ts
frontend/components/risks/js/risks-list.component.ts

This fixes #1234 
A download button has been added to the following panel card components :
- Groups, Issues , Risks
This allows the user to click a download button that downloads the current response from the server for the above components. 
The user should click the "Download JSON" button found on the panel option menu on Groups, Issues and Risks and have a downloaded file saved to the user's local drive.

Issue 1234 - Create download button for Groups, Risks and Issues component

---

frontend/components/tree/js/tree.component.ts
frontend/components/tree/js/tree.service.ts

This fixes #1281
Hiding of objects via the hide button is extremely slow on a geometry heavy model. This is mainly due to the tree service is unselecting each object , one by one, regardless whether it was selected in the first place.
This is now slightly refactored so the deselection happens on mass. Also it will not try to deselect something that isn't selected.
- Tree functionality should still be working
- hiding objects via Hide button should have great improvements when the number of meshes is large.

Issue 1281 - speed up hiding of selected objects

---

frontend/components/issues/js/issue.component.ts
frontend/components/risks/js/risk-item.component.ts

This fixes #1286
If you jump from a issue/risks component to the teamspace view, the user will not be unsubscribed to the issue/risks notifications and the system will try to process any new updates without the right information, resulting in the error message
The error message should no longer appear

ISSUE #1286 unsubscribe from update regardless of data condition

---

frontend/components/issues/js/issues.service.ts
frontend/components/tree/js/tree.service.ts

This fixes #1310
Due to changes on the tree optimisation last time, if we call hideNodes, it no longer do a full tree visibility update. This becomes a problem as issues show all the nodes (without update to save operations) then calls hide assuming this will update the whole tree.
Added a flag on tree Service to update the whole tree if flagged to true (default is false).
See issue for test case

ISSUE #1310 Issue visibility bug fix

---

frontend/modules/notifications/notifications.redux.ts
frontend/modules/notifications/notifications.sagas.ts
frontend/modules/notifications/notifications.selectors.ts
frontend/routes/components/notifications/notifications.component.tsx
frontend/routes/components/notifications/notifications.container.ts

This fixes #1362 Description
- Ensure the notification panel drawer is closed when clicking "Clear All"
- The Notification Panel Drawer should close when clicking the clear all button.

ISSUE #1362 - Close notification panel drawer on 'Clear all'

---

frontend/modules/auth/auth.helpers.ts
frontend/routes/components/panel/panel.styles.ts
frontend/routes/components/topMenu/components/userMenu/userMenu.component.tsx
frontend/routes/passwordForgot/passwordForgot.styles.ts
frontend/routes/registerRequest/registerRequest.component.tsx

This fixes #1370 
The verification message for a new user and a forgotten password request , has an additonal message. 
- Change Forgot Password message. 
- Change Verification Message.
The new messages now look like the following 
Register User
Forgot Password

Issue 1370 - Add New Paragraph to Verification messages.

---

backend/3drepo.js

This fixes #1384
- HTTPSRedirect wasn't working for front end servers with subdomain specified (i.e. `*.www.3drepo.io`)
- Added all front end servers with subdomain into vhost on http server for redirect.

Issue 1384 add front end sub domains to http redirect

---

backend/models/user.js
backend/response_codes.js
backend/test/integrated/signup.js

This fixes #1398 
- Removed `allowPlusSignInEmail` logic was it was never a actively used option.
- Remove `skipCheckEmail` logic as that is never used 
- Slight refactor on `createUser` logic
- Allow 2 or more characters on the last part of email instead of 2-5 characters
- Ensure update email logic also utilises the regex to check before updating.
- Changed error from `SIGN_UP_INVALID_EMAIL` to `EMAIL_INVALID` so it can be use generically within the context (Error message was "Invalid email" anyway.)
- `a@b.longeremail` should now pass 
- invalid email should no longer work on update (need postman to test, UI already restricts this)

Issue 1398 - Fix email regex

---

backend/models/project.js
backend/test/integrated/project.js
frontend/routes/teamspaces/components/projectDialog/projectDialog.component.tsx

This fixes #1379
- Add regex to validate project names on add project/update project
For cases of create new/update projecT:
- Project name cannot be empty
- Project name cannot end with a space
- Project name cannot contain these characters: `/?=#+`
- length of project name has to be between 1-120 (UI is blocking on 1, for some reason)

Issue 1379 - Add regex to Project name 

---

backend/models/accountPermission.js
backend/response_codes.js
backend/routes/accountPermission.js
backend/test/integrated/accountPermission.js

This fixes #1378
- check if someone is trying to update permissions of the owner, return error if yes.
- Try to change account level permissions of owner on their own teamspace (requires postman to test)

Issue 1378 - Stop owner from revoking themselves from admin role

---

frontend/routes/signUp/signUp.component.tsx

This fixes #1381 
- Only clear the password fields upon submit, avoiding the user having to rewrite the whole form if they put in an erroneous input
- I removed some Refs that doesn't seem to be in used (@simplypixi @dleszcz - please confirm if that makes sense?)
- I removed resetForm since it's no longer used (@simplypixi @dleszcz - please confirm if that makes sense?)
- The form no longer clears if API returns an error
- Successful sign up should be uneffected

ISSUE #1381 only clear password fields upon submit

---

frontend/routes/teamspaces/components/tooltipButton/tooltipButton.component.tsx
frontend/routes/viewer/components/newCommentForm/newCommentForm.component.tsx
frontend/routes/viewer/components/risks/components/riskDetails/riskDetails.component.tsx
frontend/routes/viewer/components/risks/components/riskDetails/riskDetailsForm.component.tsx

This fixes #1407 
- Add canComment permission flag to NewCommentForm
- Update RiskDetails to make use of flag
- Risks card should work exactly the same as before
- New comment area should be disabled if canComment not true
- To make the footer visible, apply the following changes:
```
--- a/frontend/routes/viewer/components/risks/components/riskDetails/riskDetails.component.tsx
+++ b/frontend/routes/viewer/components/risks/components/riskDetails/riskDetails.component.tsx
@@ -208,9 +208,6 @@ export class RiskDetails extends React.PureComponent<IProps, IState> {
screenshot={this.props.newComment.screenshot}
viewpoint={this.props.newComment.viewpoint}
innerRef={this.commentRef}
-                               hideComment={true}
-                               hideScreenshot={!this.isNewRisk} …
```

ISSUE 1407 - Comment permissions flag

---

backend/models/helper/model.js
backend/response_codes.js

This fixes #1437
Supporting change for https://github.com/3drepo/3drepobouncer/issues/291
- uploading a rvt file should now run
- uploading a rvt file when bouncer does not have ODA support should throw error
- uploading a rvt file without a 3D view should fail with error code `FILE_IMPORT_NO_3D_VIEW`

ISSUE #1437 accept rvt formats

---

frontend/globals/unity-util-external.ts
frontend/globals/unity-util.ts
frontend/globals/viewer.ts
frontend/internals/webpack/webpack.prod.config.js
frontend/internals/webpack/webpack.unityutil.config.js

This fixes #1463 
- Revive demo.ts and renamed as `unity-util-external`  as it was necessary
- changed configs to build unity-util-external
- changed loadUnity function parameters to match the pre 3.4 one 
- Normal 3drepo.io should still load
- Embedded viewer (run a server on the demo folder - you will need to change the urls which are hard coded to prod) should now work again.

ISSUE #1463 Fixes embedded viewer demo

---

backend/models/notification.js
backend/routes/notification.js
backend/test/integrated/notifications.js
frontend/modules/notifications/notifications.redux.ts
frontend/modules/notifications/notifications.sagas.ts
frontend/routes/components/notifications/notifications.component.tsx
frontend/routes/components/notifications/notifications.container.ts
frontend/services/api/notifications.ts

This fixes #1456 
This feature allows the user to mark all notifications as "Read" or "Unread".
- Add mark all read button. 
- Add mark all unread button.

Issue 1456 - Create two new buttons for notifications "Mark all as read" and "Mark all as unread

---

scripts/dbMaintenance/dbSizeCount.js

This fixes #1470
a mongo shell script to print out any databases with storage usage above 10GB

ISSUE #1470 Add a script that prints databases that utilising more than 10GB of storage space

---

backend/handler/fs.js

This fixes #1545 
- Try to load a model that has a missing file

ISSUE 1545 - Obfuscate file location in error messages

---

backend/routes/maps.js

This fixes #1561
- add ability to configure connection to osm
config for osm should look like this:
````js
osm: {
domain: //domain to the maptile server (must be HTTPS)
prefix: // any prefix before /z/x/y, e.g. tile types
key: //key to access, expected to be formulated as a query string (i.e. ?key=blah)
}
````
- old way of access osm should still work if no config present (provided you're not blocked!)
- with config, the user can access osm via their info

ISSUE #1561 configurable osm

---

backend/handler/externalServices.js
backend/handler/fs.js
backend/mailer/mailer.js
backend/mailer/templates/fileMissingError.js
backend/models/fileRef.js

This fixes #1568
- if fileshare isn't there, read from gridfs as a backup
- Send mail alert if fall back has been used

Issue 1568 read from GridFS as backup

---

backend/middlewares/chat.js
backend/models/chatEvent.js
backend/models/comment.js
backend/models/issue.js
backend/models/risk.js
backend/response_codes.js
backend/routes/issue.js
backend/test/integrated/chatService.js
backend/test/integrated/impliedPermission.js
backend/test/integrated/issue.js
frontend/modules/issues/issues.sagas.ts
frontend/routes/viewer/components/issues/components/issueDetails/issueDetails.component.tsx
frontend/services/api/default.ts
frontend/services/api/issues.ts
frontend/services/api/meta.ts

This fixes #1498 
- Replaced comments add endpoint (from `PATCH: /:account/:model/issues/:isssueid` to `POST: /:account/:model/issues/:isssueid/comments` )
- Replaced comments delete endpoint (from `PATCH: /:account/:model/issues/:isssueid` to `DELETE: /:account/:model/issues/:isssueid/comments` )
- Refactored the update issue function
- Removed the comment edit endpoint (`PATCH: /:account/:model/issues/:isssueid` with {...edit:true} in payload)

Issue 1498 - Added comments endpoints to issues

---

frontend/modules/userManagement/userManagement.sagas.ts

This fixes #1595
Added a loop and force the model permissions fetch to run in batches of 10.
- should work as before
- If you try to fetch permissions on a project with a lot of models it should now work (but generates multiple requests instead of 1.)

Issue 1595 - Prevent hitting max URL length when fetching model permissions

---

backend/mailer/mailer.js
backend/models/helper/model.js
backend/services/queue.js

This fixes #1593
- Find all logs produced on failed model imports and attach them to the email
- Remove all files within the tmpDir upon success so the tmpDir can be removed successfully.
- On model upload success, the entire folder should now go away
- On model upload failure, you should see logs being attached on the email

Issue 1593 - add logs to failed import notifications

---

frontend/modules/compare/compare.redux.ts
frontend/modules/compare/compare.sagas.ts
frontend/routes/viewer/components/compare/compare.component.tsx
frontend/routes/viewer/components/compare/components/compareClash/compareClash.component.tsx
frontend/routes/viewer/components/compare/components/compareDiff/compareDiff.component.tsx

This fixes #1626
- `setTargetRevision` on `compare.sagas.ts` was changing the clash target revision regardless of which tab i was manipulating.
- Added a flag to `setTargetRevision` to indicate whether that request came from diff tab or clash tab.
- Test case mentioned on #1626  should now work.

ISSUE #1626 TargetRevision fix for diff compare

---

backend/models/helper/model.js

This fixes #1695
- The backend is calling importFail for some reason when the quota check failed.
- It is also calling it with incorrect function parameters (hence [object object])
- If the user tries to upload a model without sufficient quota, it should no longer send a system email for import failure.

ISSUE #1695 do not call importFail when the user is out of quota.

---

backend/VERSION.json

This fixes #1697
Remove support of 2.* version of navis plugins. So we officially stop supporting version BIM01 model files (which has 32bit vertices)

Issue 1697 - Remove old navis plugin support

---

frontend/globals/unity-util.ts

This fixes #1785 
modelLoaderProgressCallback may be undefined outside of 3drepo frontend usage. Check before calling the function

ISSUE #1785 check modelLoaderProgressCallback is not undefined before calling

---

frontend/modules/compare/compare.selectors.ts
frontend/routes/viewerGui/components/compare/compare.component.tsx
frontend/routes/viewerGui/components/compare/compare.styles.ts
frontend/routes/viewerGui/components/compare/components/compareClash/compareClash.component.tsx
frontend/routes/viewerGui/components/compare/components/compareClashItem/compareClashItem.component.tsx
frontend/routes/viewerGui/components/compare/components/compareClashItem/compareClashItem.styles.ts
frontend/routes/viewerGui/components/compare/components/compareDiff/compareDiff.component.tsx
frontend/routes/viewerGui/components/compare/components/compareDiffItem/compareDiffItem.component.tsx

This fixes #1775
- Don't break page if a loaded model has no revisions.
- Show additional info on the list about lack of revision
- Disable items on the list

Issue 1775 - Fix breaking the page in compare card if a loaded model has no revisions

---

frontend/routes/dashboard/dashboard.component.tsx
frontend/routes/teamspaces/components/modelGridItem/modelGridItem.component.tsx

This fixes #1823
- renamed `Teamspaces` to `Models & Federations` on the left menu
- Swapped order of `upload` & `kanban board` on grid item actions menu

Issue 1823 small UI change

---

backend/mailer/mailer.js
backend/mailer/templates/invitedToTeamspace.js
frontend/routes/signUp/signUp.component.tsx

This fixes #1829
-  Fix email template formattive
- signup form now takes a query string to prepopulate email addresses (which would come from email template.

Issue 1829 - invitation update

---

scripts/dbMaintenance/removeUnverifiedExpiredUsers.js

This fixes #1840
a mongo shell script that removes anyone with `inactive` flag and an expired email token.

ISSUE #1840 create a script to remove unverified users with expired tokens

---

frontend/routes/components/panel/panel.component.tsx
frontend/routes/components/panel/panel.styles.ts
frontend/routes/viewerGui/components/gis/components/settingsForm/settingsForm.styles.ts
frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.styles.ts
frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.styles.ts
frontend/routes/viewerGui/components/previewDetails/previewDetails.styles.ts
frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx
frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.styles.ts
frontend/routes/viewerGui/components/viewerPanel/viewerPanel.component.tsx
frontend/routes/viewerGui/components/viewerPanel/viewerPanel.styles.ts
frontend/routes/viewerGui/components/views/views.styles.ts

This fixes #1887
- On some pages, footer is being dragged up instead of stay to the bottom
- Tree search message is at the bottom:

ISSUE 1887  - Fix layout in panels subpages

---

backend/models/ticket.js
backend/routes/issue.js

This fixes #1625
- Deduce creator_role when we're creating the ticket instead of relying on input from endpoint
- remove created timestamp from issue creation (we still need it at ticket.js level for BCF)

Issue 1625 stop reading creator_role from user input

---

frontend/modules/issues/issues.sagas.ts
frontend/modules/risks/risks.sagas.ts
frontend/services/api/issues.ts
frontend/services/api/risks.ts

This fixes #1896 #1674
Some API calls from the frontend include garbage parameters that are not read. These can be cleaned up.
**Create issue:**
**Create risk:**

ISSUE #1896 #1674 - Remove legacy fields from tickets

---

frontend/routes/components/chipsInput/chipsInput.styles.ts

This fixes #1964
The lines on the chip input  are still not the right colour if `yarn build` is ran. It's the right colour if you run `yarn watch`.

ISSUE #1964 - Fix chip input styling

---

frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx
frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx

ISSUE 1947 Fix fetching of issue during component update

---

backend/VERSION.json

This fixes #2037
move 4.6.0 to supported version and update current to 4.6.1

ISSUE #2037 version bump plugins

---

frontend/routes/viewerGui/components/measurements/measurements.component.tsx
frontend/routes/viewerGui/viewerGui.component.tsx
frontend/routes/viewerGui/viewerGui.container.ts

ISSUE #2024 - Listen for measurement removed events in whole viewer instead of only in measurement panel

---

scripts/dbMaintenance/repairFileShare.py

This fixes #2027
instead of going through settings to find all the model ID, then look through specific extensions, it now takes in the list of collection names, find all collection names ending in .ref.
- should now find all references and work accordingly.

ISSUE #2027 update maintenance script to look through all collections ending in .ref

---

frontend/routes/components/criteriaField/criteriaField.styles.ts

ISSUE #2060 - Fixed chip button got out frame when text is too long in groups

---

backend/routes/issue.js

This fixes #2082
ensure issues created by API request cannot depict what ID is being passed over.

ISSUE #2082 remove id field before creating the issue

---

backend/models/helper/model.js

This fixes #2126
- when removing a model, if fileshare failed to delete the file for whatever reason, don't stop, just log the error and carry on
- also rewrote the function into async for ease of reading
- setup a model/fed with broken fileshare linkage, the model/fed should now delete fine.

ISSUE #2126 Do not stop deletion if fileshare failed to remove the files

---

frontend/constants/risks.ts
frontend/helpers/risks.ts
frontend/routes/board/board.component.tsx
frontend/routes/board/board.container.ts
frontend/routes/components/filterPanel/components/childMenu/childMenu.component.tsx
frontend/routes/components/filterPanel/components/childMenu/childMenu.styles.ts
frontend/routes/components/filterPanel/components/filtersMenu/filtersMenu.component.tsx
frontend/routes/components/filterPanel/components/filtersMenu/filtersMenu.styles.ts
frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx
frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.container.tsx
frontend/routes/viewerGui/components/risks/risks.component.tsx
frontend/routes/viewerGui/components/risks/risks.container.ts

This fixes #1976
- As suggested call for `/:ts/mitigation/criteria` were moved to initialization of risk panel
- Additional filters were added base on `/:ts/mitigation/criteria` endpoint data

ISSUE #1976 - Add missing fields in risks filters

---

frontend/helpers/cookies.ts
frontend/helpers/webglChecker.ts
frontend/index.html
frontend/routes/app/app.component.tsx
frontend/routes/app/app.container.ts
frontend/services/unsupportedBrowserDetection.ts
frontend/support.ts

This fixes #1970
- User should only see the pop up in case of lack of support of WebGL 2.0 in browser.
- The information about reading the warning should be saved per user, it should appear for him only once and be saved in a cookie.

ISSUE #1970 - Update of browser support checking 

---

.azure/build-and-deploy.yaml

This fixes #2205 
lock the helm version, and bump kubectl to currently supported version
The pipelines can run again

ISSUE #2205

---

.azure/Docker/Dockerfile

This fixes #2212 
removed the /frontend folder, and added the /run folder
Docker image builds and runs correctly.

ISSUE #2212 remove frontend from docker image

---

backend/models/ticket.js

This fixes #2218
Basically the plugin sends in viewpoint :null on the payload and the backend logic doesn't seem to expect that.
It will now generate an empty viewpoints array if that happens.

ISSUE #2218 fix error 500 if viewpoint is set to null on issue creation

---

frontend/modules/viewpoints/viewpoints.sagas.ts

This fixes #2225
It's trying to go through show viewpoint as part of the initialisation of the model even when there's no viewpoint to set.
This is hitting some reference of variables of undefined object, which means the promise never fulfils. Hence the tree waits on it forever.

ISSUE #2225 only set viewpoint if there's a valid viewpoint

---

backend/VERSION.json

ISSUE #2258 add 4.10.0 revit plugin into supported version

---

frontend/globals/unity-util.ts

ISSUE #2084 - Make it possible to destroy and reinitialise the viewer

---

frontend/modules/sequences/sequences.redux.ts
frontend/modules/sequences/sequences.selectors.ts
frontend/modules/viewerGui/viewerGui.selectors.ts

This fixes #2322
- store previous Date in the state, and only use the state information of the current date if it is available
- this stops the break when the state of the current date is loading.
- views transformation take precedence over sequence transformation so the user can see the transformations of the issues when they have a sequence open.

Issue 2322 - 4.11.4  bug fixes

---

backend/models/helper/model.js
frontend/constants/chat.ts
frontend/modules/chat/channel.ts
frontend/modules/chat/chat.events.ts
frontend/modules/chat/chat.sagas.ts
frontend/modules/chat/teamspaces.chat.events.ts
frontend/modules/teamspaces/teamspaces.redux.ts
frontend/modules/teamspaces/teamspaces.sagas.ts
frontend/routes/teamspaces/teamspaces.component.tsx
frontend/routes/teamspaces/teamspaces.container.ts

This fixes #1199
I based on uncommented `ChatEvent.newModel` from BE. What I do not like about this is the fact that the event is sent to a channel named after a given teamspace and as a consequence, I have to assign myself to all teamspace channels on FE, hence the loop in the `teamspaces.sagas.ts` file.
It seems to me that a better solution would be to send this event to the channel of a user who should know about creating such a model, but it would require more work on the BE site.
If there is someone free to help with the BE part, we could handle the deletion and update of the model - these things are currently not working, no such events are sent from BE.

ISSUE #1199 - Add teamspace chat notifications & handle model create event

---

backend/middlewares/middlewares.js
backend/routes/maps.js

This fixes #2351 
HERE Maps are encouraging use of an `apiKey` over the previous `app_id` and `app_code`. Config needs the following information:
```
here: {
apiKey: <unique key>
}
``` 
- Try all HERE Maps layers

ISSUE 2351 - Update HERE Maps requests

---

backend/models/mitigation.js
backend/models/teamspaceSetting.js
backend/routes/teamspace.js

This fixes #2306 
- Invalid CSV file should not alter existing treatment suggestions
- Invalid CSV file should not be uploaded to teamspace settings for download
- Invalid CSV file should not update last upload timestamp in teamspace settings

ISSUE 2306 - Treatment CSV upload error handling

---

frontend/modules/tree/treeProcessing/processing.ts

This fixes #2366
- Avoid duplicate node entries when we're doing node selection
- fix problem where we are modifying the idToMeshes mapping due to the change to replace concat.

Issue 2366 - fix out of memory error on some mesh selection

---

backend/handler/db.js
backend/models/history.js
backend/test/integrated/revision.js

This fixes #2408
- altered the db api to take in sort, instead of grouping sort within projection (can be misleading)
- fix api call within `history.js`

Issue 2408 - fix sort in mongo db requests

---

demo/demo.css
demo/demo.js
demo/index.html
frontend/globals/unity-util.ts
frontend/internals/webpack/webpack.common.config.js

This fixes #2417
- the old function call should now work (i.e. demo from master branch)
- changed demo to take in api key instead of user credentials
- using the old demo in master, it should be able to connect to this version of the server (barring potential troubles with cookies)
- using this version of the demo, it should be able to connect to any staging versions of api servers
Demo test note: demo is hard coded to talk to production, you will have to edit index.html and demo.js with the right domain

Issue 2417 - backwards compatibility with the old way of hooking up the viewer

---

frontend/routes/board/board.component.tsx
frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetailsForm.component.tsx
scripts/db_migrations/v4.14/fixMitigationStatus.py

This fixes #2326
we need the following:
- A db migration script to check if there is any risk with `mitigation_status` set to `mitigation_status`, then set it to empty string.
- if we can also add a check to on POST/PATCH request to see if the status is something we recognise, that would be useful too.

ISSUE #2326 - Fix updating of mitigation status prop by kanban board

---

backend/response_codes.js
frontend/constants/revisions.ts

This fixes #2374
.bim export should now show as "3D REPO PLUGIN" instead of "NAVIS".

ISSUE #2374 rename Navis to 3D Repo plugin

---

frontend/internals/webpack/webpack.common.config.js
frontend/routes/app/app.component.tsx
frontend/routes/login/login.component.tsx

This fixes #2466 
- Removed the trigger to pop up the new version available dialog
- Set OfflinPlugin strategy to `network-first`, so it will only load the cache if there is no network version coming in

ISSUE #2466 remove newUpdate dialog

---

backend/VERSION.json

This fixes #2476, adding an entry for Unreal plugin to Version.json

ISSUE #2476 Added entry for Unreal to version json

---

backend/routes/model.js
frontend/modules/tree/treeProcessing/processing.ts
frontend/services/viewer/multiSelect.ts

This fixes #2490 #2487
- fixes show all on certain models
- revived multi select curosr
- new federation showing upload model dialog

Issue 2487 - 4.14.0 bug fixes

---

backend/models/ticket.js

This fixes #2251
- removed the generic "impose {}/[] on any data that is undefined" logic from clean function
- instead, we're only setting `comments` and `viewpoint` with this by default
- risks created in kanban/plugin on a model with no revision should no longer return a `{}` on `rev_id`

ISSUE #2251 fix rev_id data type

---

frontend/globals/unity-util.ts

This fixes #2509
The helper function in unityUtils is not returning the `end` value properly, causing this to be always returning the same as `chunkSize`. Functions that uses this relies on this value to do a slice into the array, meaning every iteration apart from the first and last (where end is undefined)  will always return an empty array.
all test cases mentioned in the issue (apart from Matt's) should now work

ISSUE #2509 fix chunking logic

---

frontend/routes/components/textField/index.ts
frontend/routes/components/textField/textField.component.tsx
frontend/routes/components/textField/textField.container.ts
frontend/routes/components/textField/textField.styles.ts
frontend/routes/modelSettings/modelSettings.component.tsx
frontend/routes/modelSettings/modelSettings.styles.ts
frontend/routes/profile/components/apiKeyForm.component.tsx
frontend/routes/profile/profile.styles.ts

This fixes #1979
Functionality was added to generic textField component used in many places in the application.
It can be enabled by adding `withCopyButton` property. However, it is worth mentioning that this was only tested for non-editable fields. Probably in the case of editable text fields, there would have to do some additional style adjustment.
It can be checked on modelID and apiKey (on user profile) fields.

ISSUE #1979 - Add copy to clipboard functionality

---

frontend/modules/sequences/sequences.helper.ts
frontend/modules/sequences/sequences.sagas.ts
frontend/modules/sequences/sequences.selectors.ts
frontend/routes/viewerGui/components/sequences/components/sequencePlayer/sequencePlayer.component.tsx
frontend/routes/viewerGui/viewerGui.component.tsx
frontend/routes/viewerGui/viewerGui.container.ts
frontend/services/dataCache.tsx

This fixes #2562
- Fixed frames prefetching: 
- Changed getSelectedFrame to return an index as well for easy access to the next frame
- Fixed indexeddb caching on states
- database is created by DataCacheService itself instead of viewerGui (that seemed very high coupling and breaks MVC)
- There's a problem with getValues not returning even when the promise has been resolved, so had to rewrite a yield into a promise.
- the test case mentioned in the issue should now be resolved

Issue 2562 frame stepping issues on sequences

---

frontend/modules/viewerGui/viewerGui.sagas.ts

This fixes #2596
- reinstate `put(ModelActions.fetchSettings(teamspace, model))` 
This is a temporary fix.
model should now load

ISSUE #2596 reinstate model settings fetch via modelActions

---

.azure/build-and-deploy.yaml

This fixes #2615 
- Updated helm chart to support configuration of the default subscription information via these two environment variables
APP_SUBSCRIPTIONS_BASIC_COLLABORATORS: "5"
APP_SUBSCRIPTIONS_BASIC_DATA: "100"
- Should deploy with the default to smaller subscription, but overridden by the dev environment settings. 
- tested on issue-400.dev.3drepo.io with 4gb quota and confirmed working.

#2615 update helm chart

---

backend/models/viewpoint.js
frontend/helpers/comments.ts
frontend/helpers/filtering.ts
frontend/routes/viewerGui/components/activities/activities.component.tsx
frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx

This fixes #2612
- `filterNestedData` was still looking for `subTasks`, this has been changed to `subActivities`
- risks screenshot reference was generating a typo on the URL, (risk instead of risks)
- append the original viewpoint on the viewpoint when we do a HTTP PATCH to update screenshot if we're not changing the viewpoint
- add a debounce on activities search (it was trying to search everytime the user types which was inefficient)
- rewrote `filterNestedData` into a standard loop instead of using reduce (it was really slow).
bugs identifies should now be fixed

Issue 2612 4.15.1 bug fixes

---

frontend/modules/risks/risks.redux.ts
frontend/routes/viewerGui/components/pinButton/pinButton.component.tsx

This fixes #2621
- Remove code that was causing position to revert back to undefined when you save a new risk with a valid pin
- When the pin button gets unmounted, if the button is active, reset the state.
- saving a pin when you create a new issue should now work
- Saving a new risk when you have added a pin without hitting "save pin" saves the pin anyway and should not error
- editing a pin from an existing risk should still work as intended
- If you leave the risk/issue without ending the pin drop activity, it should no longer get stuck on snapping mode.

ISSUE #2621 remove buggy code

---

frontend/routes/viewerGui/components/groups/groups.component.tsx

This fixes #2456 
- Now it doesnt deselect meshes when clicking the add group button
- Select some meshes , click the add group button, meshes should be still be selected and the user should be able to click save group right away

ISSUE #2456 - Now it doesnt deselect the selected nodes when creating a group

---

frontend/routes/viewerGui/components/previewDetails/previewDetails.component.tsx
frontend/routes/viewerGui/components/previewDetails/previewDetails.styles.ts

This fixes #2593
I fixed styling of the title, so that the second line would not be cut off. I also noticed that it is possible to add a title longer than we can display, so I also added a tooltip to this element.

ISSUE #2593 - Fix styling of ticket title & add tooltips

---

frontend/globals/globals.d.ts
frontend/helpers/arrays.ts
frontend/helpers/groups.ts
frontend/helpers/tree.ts
frontend/modules/groups/groups.redux.ts
frontend/modules/groups/groups.sagas.ts
frontend/modules/groups/groups.selectors.ts
frontend/package.json
frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx
frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.container.ts
frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetailsForm.component.tsx
frontend/routes/viewerGui/components/groups/groups.component.tsx
frontend/routes/viewerGui/components/groups/groups.container.ts
frontend/routes/viewerGui/components/previewDetails/previewDetails.component.tsx
frontend/services/validation/validation.ts

This fixes #2634 
- Refactored the groups edition component to be have a simpler  method to determine if the form is dirty or valid
- Added the more than 0 meshes selected and normal group type as criteria to prove that the form is valid
- Try to create or update a normal group to have 0 meshes selected, now the button is disabled all the time.

Issue #2634 - Fixed creating normal groups with 0 meshes and refactor

---

backend/middlewares/sessionCheck.js
backend/services/session.js
backend/utils.js

This fixes #2653
- session is now considered valid if the referrer came from api domain.
- refactored out the regex to get domain url to utils
- remove the last `/` from the domain so we can match:
-  referrer when it's just the domain name, e.g. `https://www.3drepo.io`)
- ignore port number on apiUrls.
- images should now show properly on issues report if api domain name is not the same as front end domain name.

ISSUE #2653 allow session to validate if the referrer is the api server

---

.travis.yml

This fixes #2759
Changed SSL installer location to a env var (that ultimately links to 3drepo drop box) so we don't run into this problem in the future

ISSUE #2759 fix ssl installer location

---

backend/handler/fs.js
backend/package.json

This fixes #2773 
Farmhash no longer used to generate a large random number. Math.random is being used instead. Not aware of any particular disadvantages of just relying on Math.random for folder names.
- Should work on private deployment
- Should distribute `fs` files across different folders randomly as before

ISSUE 2773 - remove dep on farmhash

---

frontend/src/v4/routes/components/textField/textField.component.tsx
frontend/src/v4/routes/viewerGui/components/issues/components/mainIssueFormTab/mainIssueFormTab.component.tsx
frontend/src/v4/routes/viewerGui/components/risks/components/mainRiskFormTab/mainRiskFormTab.component.tsx

This fixes #2714
Description field in Issues and Risks in both new and existing tickets cannot be longer than 660 chars
Create a new ticket and fill the description. You should not be able to type above 660 chars.
Edit the description of an existing ticket. You should not be able to type above 660 chars.

ISSUE #2714 - Description field is set to max 660 chars for issue and risks

---

backend/src/v4/3drepo.js
backend/src/v4/services/api.js

This fixes #2858
only initialise v5 services on the first instance of API server.
- we should no longer get crazy amount of notifications if the 3drepo.io server has multiple api services.

ISSUE #2858 only initialise v5 services on the first instance of api service

---

frontend/src/v4/helpers/risks.ts

This fixes #2847 
When there is a risk with invalid data (ie treatment status) , no white risk is displayed when it is clicked
Create a risk
Insert invalid data to one of its dropdown properties
Click on it in board. It should load properly with no white screen being displayed

ISSUE_2847 - no white screen is displayed if invalid data are present in risk

---

frontend/src/v4/modules/groups/groups.sagas.ts
frontend/src/v4/modules/viewerGui/viewerGui.sagas.ts

This fixes #2835 
-  When switching revisions fetch groups was counting the objects without waiting for the revision to be updated, thus it had the previous revision tree data and calculating the objects based on that data. Now it triggers fetch groups before updating the data revision and in fetch groups it waits for the revision to be updated
- get a smartgroup that matchets several revisions, when you switch the revision it should calculate correctly the objects count

ISSUE #2835 - Fixed groups not showing the correct object count when switching models 

---

backend/src/v5/middleware/dataConverter/schemas/groups.js
backend/tests/v5/unit/middleware/dataConverter/outputs/teamspaces/projects/models/commons/groups.test.js

This fixes #2862 
Bug fix added so that smart groups export Json has all dates in integer format
Find a smart group that has a createdAt property in date format and no updatedAt property in the database
Export the group as json and import it in another model
The export and import should be successful

ISSUE #2862 Smart groups export bug fix

---

backend/src/v5/processors/teamspaces/projects/models/containers.js
backend/src/v5/routes/teamspaces/projects/containers/containers.js
backend/tests/v5/e2e/routes/teamspaces/projects/containers/containers.test.js
backend/tests/v5/unit/processors/teamspaces/projects/models/containers.test.js
backend/tests/v5/unit/processors/teamspaces/projects/models/federations.test.js
frontend/src/v5/store/containers/containers.helpers.ts
frontend/src/v5/store/containers/containers.types.ts
frontend/test/containers/containers.fixtures.ts
frontend/test/containers/containers.sagas.spec.ts

This fixes #2919 
Units property renamed to units in container stats endpoint. Similar changes added to tests

ISSUE #2919 - units renamed to unit in container stats endpoint and tests

---

frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containerListItem/containerListItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containersList.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containersList.helpers.ts

This fixes #2931 
- Added the possibility to select a Container by selecting `View revisions`;
- On a selected container, the `View revisions` label is replaced by `Hide revisions`;
- Clicking on `Hide revision` the Container gets deselected.
Go to http://local.3drepo.io/v5/dashboard/<yourname\>/41575820-720c-11ec-80ce-b9c29790c4aa/t/containers;
- Clicking on the ellipses of a non-selected container and then on `View revisions` should select the container;
- Clicking on the ellipses of a selected container and then on `Hide revisions` should deselect the container

Issue 2931 - View revisions/hide revisions in container item menu

---

frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemButton/dashboardListItemButton.component.tsx
frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemText/dashboardListItemText.styles.ts
frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemTitle.component.tsx
frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemTitle.styles.ts
frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationListItem/federationListItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationsList.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationsList.styles.ts

This fixes #2904 
- Responsive desing for federations
- It hides the columns of the federations list as the user resizes the window
- Resize the window and see how it responds in this [link](https://issue-2904.dev.3drepo.io/v5/dashboard)

ISSUE #2904 - Responsive federations list

---

frontend/src/v5/ui/components/dashboard/dashboardList/dashboardList.styles.ts

This fixes #2928
The empty Favourite Federations/Containers list has the same height as with one item.
From the empty list add a federation/container to favourites.

ISSUE 2928 - The height of the empty favourites list should be the same as when it has just one item in containers and federations

---

backend/src/v5/services/swagger/swagger.js

This fixes #2961
Added /docs/openapi.json route to expose json OpenAPI definition automatically.
GET /docs/openapi.json 200 and openapi definition returned.

ISSUE #2961 Add json route for OpenAPI definition 

---

backend/src/v4/models/bcf.js
backend/src/v4/models/issue.js
backend/src/v4/models/ticket.js

This fixes #2975
- it's no longer enforcing a `rev_id` when there are no revisions
- `vp.extras` needs to be initialised or it will cause an error when the importer is trying to store `ViewSetupHints`
- `Priority` can sometimes be undefined within the BCF - it will now default to `None`
- The BCF provided should now pass (both with and without model revisions)

ISSUE #2975 fix bcf imports

---

.azure/build-and-deploy.yaml
.travis.yml

#2980 travis block merge when the rabbitmq is set

---

backend/src/v5/routes/teamspaces/projects/containers/revisions.js

This fixes #3014
Documentation for timezone added in revision upload endpoint

Issue 3014 - Documentation for timezone in revision upload

---

frontend/src/v4/routes/components/autosuggestField/autosuggestField.component.tsx

This fixes #2791
- use `indexOf(substring)` instead of comparing the first n length characters so we can find the field no matter whereabout it matches
- suggestions on smart group filter names should now show any fields that matches the search string

ISSUE #2791 smart group criteria should search the whole text for substring

---

backend/src/v5/middleware/dataConverter/multer.js
backend/src/v5/processors/teamspaces/projects/models/containers.js
backend/src/v5/routes/routesManager.js
backend/src/v5/routes/teamspaces/projects/containers/views.js
backend/src/v5/routes/teamspaces/projects/federations/views.js
backend/src/v5/utils/helper/typeCheck.js
backend/tests/v5/e2e/routes/teamspaces/projects/containers/views.test.js
backend/tests/v5/unit/utils/helper/typeCheck.test.js

This fixes #3027
Fetch container views endpoint implemented.
Swagger documentation and unit - e2e tests added.
The user should be able to fetch container views provided they pass correct details
The user should get an empty array if there are no views in a container
The user should get an error if they pass invalid details

Issue 3027 - Fetch container views endpoint 

---

frontend/src/v5/ui/components/shared/modals/templates/alertModal/alertModal.component.tsx

This fixes #3016
- Fixed the alert modal so that it can handle responses that do not contain the message in JSON format
- Set the API destination for a get request (e.g. `fetchContainers()` in _/services/api/containers.ts_) to a non-existent location. 
- Observe that the alert modal appears and can be exited.
- Set off a different error (e.g. attempt to delete one of the sample containers, or create a container with a name that already exists)
- Observe that the modal is unchanged

ISSUE #3016 - Page will go blank if the error from a fetch is 404

---

backend/src/v5/routes/teamspaces/projects/federations/groups.js
backend/src/v5/routes/users.js

This fixes #3048
Swagger doc in Update Avatar endpoint updated so that the user can browse for a file and attach it
The user should be able to browse for a file and attach it via swagger

Issue 3048 - Update Avatar swagger bug fix  

---

frontend/src/v5/store/containers/containers.helpers.ts
frontend/src/v5/ui/components/shared/revisionDetails/revisionDetails.component.tsx
frontend/src/v5/ui/controls/ellipsisMenu/ellipsisMenuItem/ellipsisMenutItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containerListItem/containerEllipsisMenu/containerEllipsisMenu.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containerListItem/containerListItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/latestRevision/latestRevision.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederationContainersList/editFederationContainersListItem/editFederationContainersListItem.component.tsx

This fixes #3113 
- When the container is empty and there's a revision that is queued now it shows the status in the containers list
- When the container is empty and there's a revision that is queued now it doesn't show the upload button in the revisions details and instead shows a message explaining the situation.
- When the revision is queued or being processed it has the upload new revision button disabled for that container in the ellipsis menu.

ISSUE #3113 - Managing queued status on empty containers

---

backend/src/v5/middleware/dataConverter/outputs/teamspaces/projects/models/commons/modelSettings.js
backend/src/v5/processors/teamspaces/projects/models/federations.js
backend/tests/v5/e2e/routes/teamspaces/projects/federations/federations.test.js
backend/tests/v5/unit/middleware/dataConverter/outputs/teamspaces/projects/models/commons/modelSettings.test.js
frontend/src/v5/ui/controls/formSelectView/formSelectView.styles.ts

This fixes #3114
- Updating a federation with a selected defaultView does not trigger errors anymore

Issue 3114 - Saving federations settings with an already set view throws an error

---

.travis.yml
backend/jest-mongodb-config.js

This fixes #3188
- bumped versions
Travis should pass

#3188 - update mongodb version to 5.0.8

---

backend/src/v5/models/loginRecord.js
backend/src/v5/utils/helper/userAgent.js
backend/tests/v5/unit/models/loginRecords.test.js
backend/tests/v5/unit/utils/helper/userAgent.test.js

This fixes #3195
Change in the way we parse user agent string so that an exception is not thrown when it is empty string
Making a login request with an empty user agent should not throw an unhandled exception

Issue 3195 - User agent parsing change

---

backend/src/scripts/migrations/4.26/addAndAssignDefaultRole.js
backend/src/scripts/migrations/4.26/index.js
backend/src/v4/constants.js
backend/src/v4/handler/db.js
backend/src/v4/models/user.js
backend/src/v5/models/roles.constants.js
backend/src/v5/models/users.js
backend/tests/v5/e2e/routes/teamspaces/teamspaces.test.js
backend/tests/v5/helper/services.js
backend/tests/v5/unit/models/users.test.js

This fixes #566
New users created in both v4 and v5 are assigned the default user role upon signup.
Existing users that don't have the role already are assigned it via a migration script.
Users created in tests are also assigned a default role.
A newly created user should have the default role assigned to them.
Existing users should be assigned the default role when migration script is run.

Issue 566 - Default role assigned to existing and new users

---

backend/tests/v5/drivers/handler/queue.test.js
backend/tests/v5/helper/services.js

This fixes #3214
impose a 10ms wait before we check for the results of the test, making sure the consumption of the queue/exchange messages has happened
- repeatedly running driver tests should no longer fail.

ISSUE #3214 address the intermittent driver test failures

---

frontend/src/v4/routes/viewerGui/components/risks/components/mainRiskFormTab/mainRiskFormTab.component.tsx

This fixes #3268 
- Added missing props in textield in mainRiskFromTab

ISSUE #3268 - Fixed crash when entering a  risk in v5 viewer

---

frontend/package.json
frontend/test/federations/federations.sagas.spec.ts

This fixes #2897 
- Removed silent param in jest tests
- Silencing console.log only in federations.saga.tests because faker is console logging an unnnecessary warning.

ISSUE #2897 - Removed silent for jest tests

---

backend/src/v4/models/user.js

This fixes #3283 
Typo on `settings` collection, meaning we were not fetching any model settings from the database, thus the quota calculation is always 0.
- quota endpoint should now give you the correct value

ISSUE #3283 typo on settings collection

---

.azure/build-and-deploy.yaml

This fixes #3323
Added the statements to allow it to build tagged releases again.
Next time we tag for release it should automatically build.

#3323 - adding in tag releases to automatically build

---

frontend/src/v4/constants/risks.ts
frontend/src/v4/routes/viewerGui/components/risks/components/riskDetails/riskDetailsForm.component.tsx
frontend/src/v5/ui/v4Adapter/overrides/cards/safetiBase/sequences.overrides.ts

This fixes #3319 
- Tweak the sequencing tab in V5 SafetiBase viewer so that it uses V5 style
- Fixed spacing around sequence labels and inputs

ISSUE #3319 - Safeti base - Sequencing

---

frontend/src/v5/services/realtime/container.events.ts
frontend/src/v5/services/realtime/federation.events.ts
frontend/src/v5/services/realtime/realtime.service.ts
frontend/src/v5/store/federations/federations.helpers.ts
frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containerListItem/containerListItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/federations.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationListItem/federationListItem.component.tsx

This fixes #2716
- Support containerSettingsUpdate realtime event in the frontend
- Support federationSettingsUpdate realtime event in the frontend
- Colaborate with another person changing the settings and see how they change in realtime in federations/containers list.

Issue 2716 - containerSettingsUpdate and federationSettingsUpdate realtime events support in the frontend

---

backend/src/scripts/utility/teamspaces/viewLicense.js

This fixes #3362
- added viewLicense command

#3362 - add viewLicense

---

backend/src/v5/utils/helper/yup.js
backend/tests/v5/unit/middleware/dataConverter/inputs/users.test.js

This fixes #3350
The maximum characters a username can have is now 63
Try to create an account with a username of more than 63 characters. An invalid arguments error should be thrown

ISSUE #3350 - Max username characters reduced from 63

---

backend/src/v4/models/chatEvent.js

This fixes #3408
in #3369 we introduced a boolean to `SESSIONS_REMOVED` event to denote if the session was removed by the user. This is so we can remove the session association from a socket, and we only send the loggedOut event to the user if it is not removed manually by the user
v4 chatEvent is not checking that flag thus this is happening
- users should no longer see the pop up if they manually logged out
- user should still see the pop up if they did log in else where (e..g different browser)
- v5 should be unaffected

ISSUE #3408 only send loggedOut  message if the event is not elective

---

frontend/.storybook/main.js
frontend/package.json

This fixes #3375 
- Now when build:test is run it builds storybook first
- Changed storybook webpack config to trigger a failure instead of a warning with wrong imports in stories

Issue 3375 - Build storybook in production

---

frontend/src/v5/services/api/containers.ts
frontend/src/v5/services/api/federations.ts
frontend/test/containers/containers.sagas.spec.ts
frontend/test/federations/federations.sagas.spec.ts

This fixes #3400
It is now possible to remove federations and containers from favourite

ISSUE #3400 - fix Remove favourite fed/container not working

---

backend/src/v5/services/modelProcessing.js

This fixes #3436
essentially, do the same thing that we already do for model updates
problem mentioned in the associated bouncer issue should now be resolved

ISSUE #3436 add a revId into the json we pass to the queue for federation edits

---

frontend/src/v5/ui/components/shared/breadcrumbsRouting/breadcrumbsRouting.component.tsx

This fixes #3424 
Opening an empty federation is the viewer, the breadcrumbs still shows the federations as last item options

ISSUE #3424 - breadcrumbs showing wrong data with empty federation

---

.azure/destroy.yaml
.github/workflows/onPRClose.yml

This fixes #3471 
- the action sends in the issue number as branchName now
- additional conditional branch protection for major branches
- hopefully now won't remove things it shouldn't and get the correct branch name to remove

#3471 - send in the branchName to the action and protect major branches

---

.github/workflows/onPRClose.yml

This fixes #3475
- set action azure pipelines action version to 1.2
- close pr fires action correctly.

#3475 - set version to 1.2

---

backend/src/scripts/migrations/4.26/storeUserAvatarInFileshare.js

This fixes #3485
ensure there's a binary buffer before moving the image
script should now run in prod

ISSUE #3485 ensure buffer exists before trying to move the data

---

frontend/src/v5/ui/components/shared/breadcrumbsRouting/breadcrumbsRouting.component.tsx

This fixes #3468
Clicking on the teamspace from the viewer correctly redirects to project selection page

ISSUE #3468 - fix teamspace breadcrumb on viewer not working for teamspace

---

frontend/src/v5/ui/components/dashboard/dashboardList/useOrderedList/useOrderedList.hooks.ts

This fixes #3488
The date sort for lists can now handle nullish values. If the lastUpdated value is **null** it is considered older than a **non-null** date.
Open either the containers list or federations list
Sort the lists by lastUpdated
Try a mixture of list items that have no lastUpdated value and items that have a lastUpdated value

ISSUE #3488 - Sorting list by 'Last Updated' can cause a crash if some of the values are null

---

frontend/package.json
frontend/src/v5/helpers/reducers.helper.ts
frontend/src/v5/store/.eslintrc.js
frontend/src/v5/store/teamspaces/teamspaces.redux.ts
frontend/yarn.lock

This fixes #3524 
Immer was included as a library to simplify the way redux reducers are written.
Teamspace reducers have been rewritten accordingly

Issue 3524 - Rewrite redux file to use Immer.js: Teamspaces

---

frontend/index.html

This fixes #3537
- forced http on live reload
livereload now works when https is used on the front end

#3537 - livereload on http

---

frontend/src/v4/routes/viewerGui/components/compare/compare.styles.ts

This fixes #3452 
Set the parent component of the slider (which has an absolute position) to use a relative position

Issue 3452 - Compare slider (Viewer) does not shrink with the card

---

frontend/src/v5/ui/routes/dashboard/projects/settingsForm/settingsForm.component.tsx

This fixes #3528
Opening the settings modal now shows the correct data even when opened the first time. Note that the problem was not just the description (e.g. surveyPoint).
Similarly, also the federation had the same problem but not for the description.
Go to container, open the settings modal and change the description. Save and refresh the page.
Opening the settings modal should change the newly inserted description

ISSUE #3528 - Settings modal shows the correct data on the first opening

---

frontend/src/v5/ui/routes/login/login.component.tsx
frontend/src/v5/ui/routes/routes.constants.ts

This fixes #3509 
The link to the release notes on the login page was a dead link. This PR updates the link so that it now works
Click the link on the login page

ISSUE #3509 - Update login page link to release notes

---

frontend/src/v5/ui/themes/global.ts

This fixes #3602 
reduced the height of the viewer canvas so that the 'powered by 3d repo' logo and coordinates are not off-screen
- open the viewer

ISSUE #3602 - In the V5 viewer the bottom of the canvas is hidden off-screen

---

frontend/src/v5/ui/routes/userSignup/userSignupForm/userSignupFormStep/userSignupFormStepTermsAndSubmit/userSignupFormStepTermsAndSubmit.component.tsx

This fixes #3594 
- updated the links to the legal papers at the end of the signup form to point to the new v5 pages
- do the signup form and click the links to the papers

ISSUE #3594 - update v5 signup form links to legal papers

---

frontend/src/v4/routes/viewerGui/components/gis/gis.component.tsx
frontend/src/v5/ui/v4Adapter/overrides/cards/gis.overrides.ts

This fixes #3522 
- fix styling of dropdown menu in main view
- Remove back button in GIS settings when it is disabled
- Remove ellipses when in GIS settings as it does nothing
- Navigate to the V5 viewer
- Open the GIS settings
- Fill out settings
- Navigate between the main screen and settings of GIS

ISSUE #3522 - Fix up GIS panel in V5 viewer

---

frontend/src/v4/routes/viewerGui/components/groups/groups.component.tsx
frontend/src/v4/routes/viewerGui/components/reportedItems/reportedItems.component.tsx
frontend/src/v5/store/containers/containers.helpers.ts
frontend/src/v5/ui/components/shared/revisionDetails/revisionDetails.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containerListItem/containerEllipsisMenu/containerEllipsisMenu.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containerListItem/containerListItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/uploadFileForm/uploadFileForm.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/uploadFileForm/uploadFileForm.helpers.ts
frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederationContainersList/editFederationContainersListItem/editFederationContainersListItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationListItem/federationListItem.component.tsx
frontend/src/v5/ui/routes/dashboard/teamspaces/teamspaceLayout/teamspaceQuota/teamspaceSeatsQuota.component.tsx

This fixes #3410
- Adds proper plural and singular forms where needed in strings (e.g. 1 revision, 2 revisions)
- Change upload modal headers to depend on the number of files being uploaded. The headers for when no files have been added are shown in the spec [here](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3096%3A48896) but were not implemented
- Go through the app and see if there are any strings that require this treatment that have been missed
- Test out the strings with different numbers of items

ISSUE #3410 - Use plurals/singulars where needed across V5

---

frontend/src/v5/ui/controls/modal/formModal/formDialog.component.tsx
frontend/src/v5/ui/controls/modal/formModal/formDialog.styles.ts
frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederationContainersList/editFederationContainersList.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederationContainersList/editFederationContainersList.styles.ts
frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederationModal.component.tsx

This fixes #3392 
- Custom horizontal scrollbar is not visible on edit federations modal
- accordion elements scale better with screen size
- The accordion title is still 1 line, as using multilines and truncating the title and not the container number was a difficulty
Open up the edit federation (try using both short and long federation names), and reduce the screen width

ISSUE #3392 - Edit Federation Modal uses default horizontal scrollbar, which is only visible at bottom of vertical scroll

---

backend/src/scripts/migrations/4.30/addVertexCountsToMeshBSONs.js
backend/src/v4/handler/db.js

This fixes #3580 
- Reduce concurrent updateOne requests to avoid out of memory error
- Should work on previously problematic teamspaces

ISSUE #3580 - reduce concurrent updating

---

backend/src/v4/services/frontend.js
frontend/src/v4/routes/subscription/components/subscriptionForm.component.tsx

This fixes #3546 
- Slightly changed route for static's to ensure that the headers aren't sent early
- Removed a broken image on the /billing/ route and slightly changed the wording
- tweaked favicon route settings
visit 
1. https://3drepo.local/favicon.ico
2. https://3drepo.local/dashboard/billing/subscription
and review the server log to see no further errors
*** further investigation showed it wasn't the /favicon.ico route itself, but the browser requesting sw.js ( I couldn't trace the reason for this) but the crash was caused by the 404 handling on /sw.js (or any other 404)

ISSUE #3546 - resolved crashes when static 404's

---

backend/src/v4/handler/db.js
backend/src/v4/handler/fs.js
backend/src/v5/utils/helper/models.js

This fixes #3638
- add a function all to remove all indicies before dropping the collection
- remove indicies within all collections before dropping a database
- should work as before
- deletion time should improve

Issue 3638 - remove indices before dropping a collection

---

scripts/dbMaintenance/repairFileShare.py

This fixes #3644
- Added all known toy folders
- repairFileShare.py acts correctly.

#3644 fix toy folders

---

backend/src/v4/models/user.js
backend/src/v5/utils/quota.js

This fixes #3579
Ticket resources are now taked into consideration in quota endpoints in v4 and v5
v4 endpoint now uses v5 method to return the quota
Calculate spaced used for a user without any ticket resources
Add some ticket resource
Calculate space used again
It should return an increased space used

ISSUE #3579 - Tickets resources taken into consideration in quota info

---

backend/src/v5/schemas/tickets/validators.js
backend/tests/v5/unit/schema/tickets/index.test.js

This fixes #3665
A view property of a custom ticket can now have clipping plane
Create a ticket with a view prop and add clippingPlanes property.
The ticket should be created and the clipping planes should be stored in the db

ISSUE #3665 - Clipping planes added in view prop of Custom Tickets

---

backend/package.json
backend/src/v4/services/api.js
backend/yarn.lock

This fixes #2578
- added a new library to use their middleware to handle any body parsing errors
- doing a POST request with invalid json should now return a 4xx error instead of gibberish 500

ISSUE #2578 handle invalid json errors gracefully

---

frontend/src/v5/ui/components/viewer/cards/card.styles.ts
frontend/src/v5/ui/controls/circleButton/circleButton.component.tsx
frontend/src/v5/ui/controls/circleButton/circleButton.styles.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketsForm.component.tsx

This fixes #3697 
- Add the header for the ticket details card
- Add icons for going back and cycling between neighbouring tickets
- Open a ticket to view the details
- Cycle between tickets (You can also cycle from first to last and vice versa)

ISSUE #3697 - Custom tickets - Details card header

---

frontend/src/v4/modules/viewerGui/viewerGui.redux.ts
frontend/src/v4/routes/viewerGui/viewerGui.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx

This fixes #3704 
Fixes crashes/bugs that occurred when changing Federation/Container/Revision when a panel is open.
This includes:
- Changing container while a ticket's details is expanded crashes the app 
- Viewing a group and changing model keeps the group open with details. Trying to update the group causes an error
- Opening the BIM panel and changing model to one that doesn't allow BIM results in the user being unable to close this panel
- Viewer crashes when switching between revisions when a sequence is open #3715
- Try to break the app in both V4 and V5 by having panels open and switching both revision/federation/container
(Note in v4 the container/federation can be changed in the same viewer instance by clicking on notifications)

ISSUE #3704 - Changing container while a ticket is expanded crashes the app 

---

backend/src/scripts/migrations/4.28/index.js
backend/src/scripts/migrations/4.28/removePermissionTemplates.js
backend/src/v4/models/permissionTemplates.js
backend/src/v4/models/user.js
backend/src/v4/routes/permissionTemplate.js
backend/tests/v4/integrated/permissionTemplate.js

This fixes #3735
Problem arises because anyone who signed up on v5 would not have permissionTemplates in their bson, but v4 logic still assumes its presence.
- hardcoded permissionTemplates in the code instead of trying to fetch it from the database
- v4 no longer add permissionTemplates in the user bson at sign up
- removed functions to add/remove permission templates as they are now constants (and was never used)
- migration script added to remove all permissionTemplates
- situation described in the issue should work for both
- users signed up via v4 endpoint
- users signed up via v5 endpoint

Issue 3735 - fix error 500 when the user does not have permissionTemplates

---

frontend/src/v5/store/teamspaces/teamspaces.selectors.ts
frontend/src/v5/ui/routes/dashboard/teamspaces/teamspaceLayout/teamspaceLayout.component.tsx

This fixes #3798 
When the user is not a teamspace admin, the fetch quota request is not triggered

ISSUE #3798 - quota is correctly hidden when user is not teamspace admin

---

frontend/src/v5/ui/components/shared/revisionDetails/components/revisionsListItemAuthor/revisionsListItemAuthor.component.tsx
frontend/src/v5/ui/components/shared/userPopover/userPopover.component.tsx

This fixes #3837 
- If the user that uploaded a revision is no longer part of the teamspace now it shows the username
- Hover over the username now displays "The user is not currently a teamspace member"

ISSUE #3837 - Fixed blank screen in revisions

---

.github/workflows/automaticTesting.yml

This fixes #3843 
updated action version
No longer getting a warning about old node version.

#3843 - use checkout/v3 for automaticTesting action

---

backend/src/v5/models/fileRefs.js
backend/tests/v5/unit/models/fileRefs.test.js

This fixes #3864
The bug is caused by an aggregate pipeline we perform to find all external references we need to remove when we remove a model. The aggregate produce data in the following format:
````js
[{
_id: "link type", // e.g. "fs" or "gridfs"
links: ["reference links"] //e.g. ["250/12/b9d175c7-d14b-4436-be83-d505aa2f17b2"] for fs
}]
````
In cases where there are a lot of meshes, where each mesh will typically produce 3 references, we may end up with a lot of links, which may be large enough for BSON sizes to exceed 16MB, hence the aggregate returns an error. The situation @Ramadyfm found had 366108 references in `scene.ref`
This PR fixes the problem by doing a standard `find` instead and let 3drepo.io build the reference objects.
This problem can be reproduced by creating dummy …

ISSUE #3864 Perform functions in a mongo aggregate on application level instead to support large models

---

frontend/src/v5/ui/controls/inputs/datePicker/baseCalendarPicker/baseCalendarPicker.component.tsx

This fixes #3858
Previously the text field of date pickers would have a default value of the current date. So an unset value would appear to have a value set. This PR prevents that behaviour and uses placeholder text.
This happened because the placeholder is only used when the value is null. The value being passed in was in fact undefined so the placeholder wasn't triggered
Create a custom ticket that has a date property. Observe the unset state of the text field

ISSUE #3858 - Unset dates on custom tickets show placeholder message instead of todays date

---

frontend/src/v5/ui/routes/viewer/theme.ts
frontend/src/v5/ui/themes/theme.ts

This fixes #3802
The error helper text used to overlap with the input it spanned over multiple lines. This PR fixes that
Open container/federation settings and type `$` inside `code`

ISSUE #3802 - multiline helper-text doesn't overlap input

---

.azure/build-and-deploy.yaml

This fixes #3892 
- changed chart to 4.28.2
- `/azp run` still works

Issue 3892 - update helm chart to 4.28.2

---

frontend/src/v4/routes/app/app.component.tsx

This fixes #3921
- Now when you enter /login it redirects to /v5/login
- Now when you enter /sign-up it redirects to /v5/signup

Issue 3921 - Redirect v4 login & signup to v5 login & signup

---

frontend/src/v4/modules/viewpoints/viewpoints.redux.ts
frontend/src/v4/modules/viewpoints/viewpoints.sagas.ts
frontend/src/v4/routes/components/viewsDialog/viewsDialog.component.tsx
frontend/src/v4/routes/teamspaces/components/modelGridItem/modelGridItem.component.tsx
frontend/src/v4/routes/viewerGui/components/views/components/viewItem/viewItem.component.tsx
frontend/src/v4/routes/viewerGui/components/views/views.component.tsx
frontend/src/v4/routes/viewerGui/viewerGui.component.tsx
frontend/src/v5/ui/routes/viewer/viewer.tsx

This fixes #3926
The projectId (as well as the revision) is passed down to the `viewItem`s and, if it is v5, used to generate the link to that view accordingly
Open the views card in the v5 viewer and create the link for a view.
Repeat for v4.

ISSUE #3926 - views in v5 generate links to v5

---

frontend/src/v5/ui/routes/viewer/tickets/tickets.component.tsx

This fixes #3934 
The problem was this:
- when opening the ticket card, the base templates where always fetched;
- the base template, however, does not have the information needed to render an actual ticket, which is fetched on opening the actual ticket;
- closing the ticket card (while the view was set on the ticket details) and then reopening it, forced the base templates to be refetched (wiping out the exisisting data), but without refetching the template details
Open up a ticket details, close the ticket card and re-open it

ISSUE #3934 - The custom ticket gets wiped out after closing the panel

---

backend/src/v5/middleware/sso/aad.js
backend/src/v5/middleware/sso/pkce.js
backend/src/v5/routes/sso/aad/index.js
backend/src/v5/services/sso/aad/index.js
backend/tests/v5/e2e/routes/sso/aad/aad.test.js
backend/tests/v5/e2e/routes/sso/sso.test.js
backend/tests/v5/e2e/routes/users.test.js
backend/tests/v5/helper/services.js
backend/tests/v5/unit/middleware/sso/aad.test.js

This fixes #3914
- All `*-post` routes (routes that are called by MS authenticator) are now a `HTTP POST` route so data can be stored within a body
- CSRF token is now enforced in the MS authenticator workflow to ensure it's the same session making it
- State is now hashed into a string so it's not obvious what the data is from the URL
- the workflow should function like before

Issue 3914 - SSO improvements

---

frontend/src/globals/unity-util.ts

This fixes #3971
This PR prepends the viewer initialisation promise chain with a function that deletes the /idbfs database. This is done before loading as the consequences of removing /idbfs on a running emscripten module are not known, and more importantly, emscripten loads the contents of /idbfs into memory at start-up, so start-up times are minimised by deleting the content before the viewer gets to this point.
This snippet will run every time the viewer runs from now on. The viewer does not use the System.IO namespace anymore, so there is nothing to be lost by removing this store each time.
With this in place, each time the viewer loads the /idbfs should be empty save for one or two small entries created at or after the last time the viewer was started.
Any records dating before the …

ISSUE #3971 - Delete /idbfs before viewer loads

---

frontend/src/v4/constants/viewerGui.ts
frontend/src/v4/modules/viewerGui/viewerGui.redux.ts
frontend/src/v4/routes/viewerGui/viewerGui.component.tsx

This fixes #3975 
- The left menu buttons were declare once so if you entered the app by just the '/' route it would declare the buttons for v4 instead of v5.

ISSUE #3975 - Fixed custom ticket button not showing

---

.azure/Docker/test.yaml
.azure/build-and-deploy.yaml
.azure/build.yaml

This fixes #2855
- staging environment CI/CD won't attempt to build tags
- tagged builds will build and push the container and not to attempt to push to staging environment

#2855 updated build process

---

frontend/src/v5/services/realtime/ticketComments.events.ts
frontend/src/v5/ui/routes/viewer/tickets/commentsPanel/comment/comment.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/commentsPanel/comment/comment.helpers.ts
frontend/src/v5/ui/routes/viewer/tickets/commentsPanel/commentsPanel.component.tsx

This fixes #3932
Realtime events have been added to custom ticket comments for creation and update (including deletion) of comments

Issue 3932 - Add realtime events to ticket comments

---

frontend/src/v4/modules/issues/issues.sagas.ts
frontend/src/v4/modules/risks/risks.sagas.ts
frontend/src/v4/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx
frontend/src/v4/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx

This fixes #3866
Updating a viewpoint in a risk/issue without updating the screenshot does not erase the existing one
In the viewer, pick a risk/issue with a viewpoint and a screenshot/image. Update the viewpoint, but when the dialog "do you want to update the screenshot" comes up, click "no" or simply close it. The screenshot should be the same as before

ISSUE #3866 - on update viewpoint existing image is not erased

---

frontend/src/globals/unity-util.ts

This fixes #3992
This PR introduces a thread-safe check around the `deleteDatabase()` call.
The check uses the persistent and shared `localstorage` feature, to flag whether a tab has previously cleared the cache. If so, the `clearIdbfs` resolves immediately. (This also has the benefit of saving time on start-up as clearing the idbfs database is a waste of time after it has been done once per-user.)
The value of the flag is a random id, which is initialised once and checked again before embarking on a clear, to provide a measure of thread safety since localstorage does not support CAS operations.

ISSUE #3992 Viewer seems to only support 1 browser tab

---

frontend/internals/webpack/webpack.dev.config.js
frontend/src/globals/unity-indexedbcache.ts

This fixes #4005
This PR changes how `IndexedDbCache` initialises its Worker. It now fetches the script itself and creates a blob URL, respecting the pages CORS settings, rather than asking the Worker to fetch the script (which is always done with "same-origin"). [This](https://stackoverflow.com/questions/58098143/why-are-cross-origin-workers-blocked-and-why-is-the-workaround-ok/60015898#60015898) allows the Worker to be instantiated when the `unity-util` and `indexeddbworker` are hosted on different origins (e.g. when the viewer is embedded).
This should be verified on as many browsers as possible to make sure the new way of instantiating the Worker is acceptable.
The new mechanism is the same whether running an embedded viewer, or a regular deployment, so only the normal deployment …

ISSUE 4005 IndexedDbCache cannot be created by an embedded viewer

---

backend/src/v4/logger.js

This fixes #4007
- Fixes the pathing required to create folders correctly.
- configure config.logfile.logDirectory
- run IO
- observe 'io-YYYY-MM-DD.log' created and populated.

#4007 - fix logDirectory 

---

.azure/build-and-deploy.yaml

This fixes #4032
- don't wait for the deployment
- `/azp run` should be faster and not hang about

#4032 don't wait for helm to complete during CD

---

backend/src/v4/response_codes.js
backend/src/v5/services/eventsListener/components/modelEvents.js
backend/tests/v5/unit/services/eventsListener/eventsListener.test.js

This fixes #4042
- removed excessive logging when we have an error in the responder in v4
- add logging if we caught an exception during event processing for model processing signals

Issue 4042 - log the error when we process event messages

---

frontend/src/v5/ui/components/shared/appBar/appBar.component.tsx
frontend/src/v5/ui/components/shared/appBar/appBar.styles.ts

This fixes #4036 
Tweaks the colour of the 3D Repo logo in the navbar so that it is now white
- Look at it

ISSUE #4036 - recolour navbar logo to white

---

frontend/src/main.tsx
frontend/src/v4/routes/app/app.component.tsx

This fixes #4025 
Moved the redirect logic so that V4 doesn't get rendered before redirecting.
Also fixed the login route redirect as this still had the 404 problem listed here #3991
Navigate to each of the following and observe if you see V4 load before seeing v5
- 3drepo.lan/
- 3drepo.lan/sign-up
- 3drepo.lan/login
After being redirected the isV5() function should be updated too. This can be tested by opening up a model and seeing if you get the 404 error (as described in #3991)

ISSUE #4025 - prevent v4 redirects briefly showing v4 interface

---

backend/src/v4/config.js
backend/src/v5/middleware/sessions.js
backend/src/v5/middleware/sso/aad.js
backend/src/v5/middleware/sso/index.js
backend/src/v5/services/swagger/swagger.schemas.js
backend/tests/v5/unit/middleware/sessions.test.js
backend/tests/v5/unit/middleware/sso/aad.test.js

This fixes #4070 
Small SSO changes in order for plugin SSO sessions to be stored properly in the database (ie correct userAgent, referer).
Log in via SSO from the plugin and inspect the session stored in the database
The session should not be a web session and have no referer

ISSUE #4070 - Sso changes for plugin compatibility

---

frontend/src/v5/store/containers/containers.redux.ts
frontend/src/v5/store/federations/federations.helpers.ts

This fixes #4082 and #4037
There were a few bugs caused by containers and federations being given incorrect roles in redux upon creation. I have changed it so that new containers/federations are automatically given the admin role. Only admins can create containers and federations
- Create a Federation.
- Without refreshing the page Open the edit federation modal. You should be able to see the add and remove buttons
- Create a Container.
- Without refreshing the page open the ellipsis menu. You should be able to see the 'upload revision' opinion.

ISSUE #4082 - New revision button not appearing on new containers

---

frontend/src/v5/ui/components/shared/revisionDetails/revisionDetails.component.tsx

This fixes #4105
Newly uploaded revision appears as first
Upload a revision and, without refreshing, check whether it is shown as first

ISSUE #4105 - sort revisions

---

frontend/src/v5/validation/shared/validators.ts

This fixes #3884 
- Required number inputs that are unset were not disabling the submit button. Upon clicking submit nothing would happen (or the browser would indicate that an input is required for submission)
- This was due to the validation for numbers requiring that the value was not null, so undefined values slipped through
On a ticket that has a required number field try various different inputs. E.g. 14, 0, -11
Should there maybe be options when creating a template for if the number input should be integer/decimal/positive/non-zero?

ISSUE #3884 - Custom Tickets Required number inputs that are unset do not disable submit button

---

frontend/src/v4/routes/board/board.component.tsx

This fixes #4092 
- Fixed the kanban board crashing to a white screen when selecting a federation/container
- This was because a ScrollArea was broken when changing the ScrollArea from a component file to a styled component
- Open the kanban board and select different containers/federation.
- Click on Issues/Risks
- Check that the scrollbars are all fine

ISSUE #4092 - Fix Kanban board crashing

---

backend/src/v5/models/modelSettings.js
backend/tests/v5/unit/models/modelSettings.test.js

This fixes #4119
= only trigger new revision event if import was a success
= update tests to reflect the new situation
- should no longer trigger NEW_REVISION if the model import failed
- should still trigger NEW_REVISION if the model import passed

ISSUE #4119 only trigger NEW_REVISION event if model import was a success

---

frontend/src/v4/routes/board/board.component.tsx
frontend/src/v5/services/routing/routing.tsx
frontend/src/v5/ui/components/shared/navigationTabs/projectNavigation/projectNavigation.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/containers.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containerListItem/containerEllipsisMenu/containerEllipsisMenu.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/federations.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationListItem/federationEllipsisMenu/federationEllipsisMenu.component.tsx

This fixes #4104
- [Remove the task tab on the projects page](https://github.com/3drepo/3drepo.io/issues/4104#issuecomment-1473757291)
- [Improve wording on selection message](https://github.com/3drepo/3drepo.io/issues/4104#issuecomment-1473759925)
- [Change wording on favourites](https://github.com/3drepo/3drepo.io/issues/4104#issuecomment-1473770002)
- View risks/tasks options in container/federations ellipsis menus take you to the relevant kanban board
- Access federation/containers kanban boards from the dashboard lists
- Check wording has updated in all occurrences

ISSUE #4104 - Project Page Improvements

---

frontend/src/v5/ui/routes/dashboard/projects/projectsList/createProjectModal/createProjectModal.component.tsx
frontend/src/v5/validation/projectSchemes/projectsSchemes.ts

This fixes #4101 
The user can no longer change the target teamspace when creating a project.
The teamspace is displayed in a disabled textfield as the user needs context of which teamspace it is being added to
- create a new project

ISSUE #4101 - Add project modal should not allow the user to change teamspace

---

frontend/src/v5/ui/components/shared/sso/microsoftText.component.tsx
frontend/src/v5/ui/components/shared/sso/microsoftText.styles.ts
frontend/src/v5/ui/components/shared/userMenu/editProfileModal/editProfileAuthenticationTab/editProfileAuthenticationTab.styles.ts
frontend/src/v5/ui/routes/login/login.component.tsx

This fixes 4012
The "NEW" chip has been removed from the SSO text
Go to the login page
Go to the edit profile modal, authentication tab

ISSUE #4012 - remove new chip from SSO text

---

frontend/src/v4/modules/compare/compare.selectors.ts

This fixes #4112
In the viewer, the compare button is only available if there are at least 2 revisions amongst the selected models
open a federation with only 1 container that has only 1 revision
open a federation that, given all the containers, has more than 1 revision

ISSUE #4112 - Disable compare button when there are not enough revisions selected

---

frontend/src/v5/store/teamspaces/teamspaces.redux.ts
frontend/src/v5/store/teamspaces/teamspaces.sagas.ts
frontend/src/v5/store/teamspaces/teamspaces.selectors.ts
frontend/src/v5/ui/components/teamspace/teamspaceList/teamspaceList.component.tsx
frontend/test/teamspaces/teamspaces.sagas.spec.ts
frontend/test/teamspaces/teamspaces.store.spec.ts

This fixes #4167 
A user that has not teamspace (because it was deleted) will not see the loading screen, but will be prompted to create a new teamspace
Delete the teamspace from the cmd and go the teamspace selection page.
To delete the teamspace of a user, you can:
- open the cmd and navigate to the `local` folder;
- call `.\run-io-backend-scripts.ps1 removeTeamspaceAndOwner --accounts <user>` where `<user>` is the user whose teamspace should be deleted

Issue 4167 - Better support for users without teamspace

---

frontend/src/v5/ui/components/dashboard/dashboardList/useOrderedList/index.ts
frontend/src/v5/ui/components/dashboard/dashboardList/useOrderedList/useOrderedList.helpers.ts
frontend/src/v5/ui/components/dashboard/dashboardList/useOrderedList/useOrderedList.hooks.ts
frontend/src/v5/ui/components/dashboard/dashboardList/useOrderedList/useOrderedList.types.ts

This fixes #4111 
The default sort is now a descending lastUpdated sort.
If the last updated is empty (null/undefined) then this is treated as new and placed at the top of the list
Check out both Federations and Containers lists
Change sort directions
When the sort is in last updated mode create a new container and see where it is placed in the list

ISSUE #4111 - Default sort for dashboard lists is by most recently updated

---

frontend/src/v5/store/containers/containers.redux.ts
frontend/src/v5/store/containers/containers.sagas.ts
frontend/src/v5/store/projects/projects.selectors.ts
frontend/src/v5/store/teamspaces/teamspaces.selectors.ts
frontend/src/v5/store/viewer/viewer.sagas.ts
frontend/src/v5/ui/components/shared/modalsDispatcher/templates/alertModal/alertModal.component.tsx
frontend/src/v5/validation/errors.helpers.ts
frontend/test/containers/containers.sagas.spec.ts
frontend/test/viewer/viewer.sagas.spec.ts

This fixes #4146
A project that does not grant access to the user is now correctly detected and the, on reaching an invalid model in the viewer, the user is redirected accordingly.
Within a shared teamspace where no model is accessible (unauthorised) and try to access one => the user should be redirected to the dashboard
Within a shared teamspace where at least one model is accessible, try to access an unaccessible one (unauthorised) => the user should be redirected to the project list

Issue 4146 - Project page does not show any data if we enter it in an error state

---

backend/src/v4/handler/externalServices.js
backend/src/v4/handler/fs.js
backend/src/v4/models/fileRef.js
backend/src/v4/models/jsonAssets.js

This fixes #4212
- on the supermesh.json_mpc route:
- we are now reading 100 files at a time instead of serially
- check if we already have a cache of the results in the fs, if not, generate it
- if we have to generate it , store a copy in the cache

ISSUE #4212 fetch all supermesh asset files in parallel

---

frontend/src/v5/ui/components/viewer/cards/tickets/pinDetails/pinDetails.component.tsx

This fixes #4197 
Clicking on the title was also triggering the edit mode.
The title click functionality has been removed as not conform with the rest of the inputs
In a custom ticket with a pin, click first on the button "create pin" and then on the title

Issue 4197 - Double click on Pin loses focus styling

---

frontend/src/v5/store/viewer/viewer.sagas.ts
frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederation.component.tsx

This fixes #4248  and #4250 
- Fixed a crash that occurred when opening a mixed permissions federation. When the containers stats are fetched only containers which the user has permissions to are used
-  Fixed a crash that occurred when editing a mixed permissions federation. Unassigned containers were showing up as 'undefined'. These are now filtered out
-
- Create a federation with containers A and B
- Set the permissions for a user so that they can view container A, but container B is 'unassigned'
- As that user attempt to edit the federation
- As that user attempt to view the federation
- Opening a federation with no containers will still show the 'Add containers' screen
- Opening a federation that contains only empty containers will still show the 'Upload revisions' screen

ISSUE #4248 - Fix crashes when a Federation contains an 'unassigned' container

---

frontend/src/v5/store/tickets/ticketsGroups.helpers.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/addOrEditGroup/groupSettingsForm.component.tsx/groupsCollectionSelect/groupsCollectionSelect.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/editGroupButton/editGroupButton.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupItem/groupItem.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groups.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groupsAccordion/groupsAccordion.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groupsAccordion/groupsAccordion.styles.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroupsContext.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroupsContext.helper.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroupsContext.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx

This fixes #4257
Groups override states are stored in a context which handles it.
Group Items/Group of groups can access such a state and use it to select /unselect overrides

Issue 4257 - Overrides in groupsTab

---

backend/src/v4/models/modelSetting.js
backend/src/v4/models/user.js

This fixes #4278
The reason why we get uncaught exception is we are pushing an array of promises instead of using the spread operator so we are concatenating the array. This is now addressed.
The functions are slightly rewritten for clarity as well.
We are also catching the situation where with the permissions, the user is not part of a teamspace and ignoring it - so having permissions for a zombie user should no longer stopping you from deleting an unrelated user.
The situation described in the issue should now be resolved

ISSUE #4278 catch errors properly

---

backend/src/v4/handler/fs.js
backend/src/v5/utils/helper/arrays.js
backend/tests/v5/unit/utils/helper/arrays.test.js

This fixes #4244
ensure we only delete a maximum of 10k files in one go
- deleting containers/projects should still work
- deletion requests where there are large models should no longer crash the server

ISSUE #4244 restrict the amount of files we delete in parallel

---

backend/src/scripts/migrations/5.4/index.js
backend/src/scripts/migrations/5.4/mergeSceneBinaries.js
backend/src/v5/services/filesManager.js
backend/tests/v5/unit/services/filesManager.test.js

This fixes #4293
- Following the schema in https://github.com/3drepo/3drepobouncer/issues/626, I've created a migration script to move all existing files to that schema and remove all existing files.
- The script should be pretty self healing - it only updates the database entries and remove existing files when the file has been committed. Running the script multiple times should not be an issue and will skip already processed scenes/stashes.
- should run successfully on all environments
- measuring tool that utilises the data (e.g. minimum distance, surface area) should work as before

Issue 4293 - migration script to reduce the amount of files we have

---

frontend/src/v4/modules/tree/treeProcessing/transforming.ts
frontend/src/v4/routes/viewerGui/components/tree/components/treeNode/treeNode.component.tsx

This fixes #4298
teamspace name is no longer prefixed onto container entries on the federated tree
- should show container name as expected
- buttons on the tree node should function as before

ISSUE #4298 do not append teamspace name onto the node name

---

frontend/src/v5/store/tickets/tickets.selectors.ts

This fixes #4271 
Tickets are sorted based on the creation date. Newer are first

ISSUE #4271 - sort tickets by creation date

---

frontend/src/v5/store/tickets/tickets.validators.ts
frontend/src/v5/ui/controls/dueDate/baseDueDate.component.tsx
frontend/src/v5/ui/controls/inputs/datePicker/baseCalendarPicker/baseCalendarPicker.component.tsx

This fixes #4308
- Changed due date to use timestamp
- Changed date property fields to use timestamp
- Should sent a timestamp instead of a string for dates
- update a due date (in existing and a new ticket)
- update a due date in the details ticket view  (in existing and a new ticket)
- update another type of date in the details ticket view  (in existing and a new ticket)

ISSUE #4308 - Now in tickets is sending a timestamp when the date fields are changed

---

backend/src/v5/routes/teamspaces/projects/models/common/tickets.groups.js

This fixes #4310 
change from PUT to PATCH on the comment
swagger should now reflect the correct HTTP verb and functions as expected

Issue 4310 - ticket groups edit should be a PATCH instead of PUT

---

backend/src/v4/models/sequenceActivities.js

This fixes #4332
serialise the resource IDs during the clean function
Activity details should now return serialised UUIDs

ISSUE #4332 serialise the resource IDs within activity details

---

backend/src/v5/services/mailer/templates/html/baseTemplate.html
backend/src/v5/services/mailer/templates/html/systemTemplate.html

This fixes #4233
turns out the logoDiv wasn't closed properly so the whole content div is being seen as a child of the logo div, hence the restricted width formatting
email should render correctly now

ISSUE #4233 fix email formatting

---

backend/src/v4/models/user.js

This fixes #4352
Small fix to make sure all project Ids returned from Get Account Data V4 endpoint are deserialized

ISSUE #4352 all project ids are deserialized in get account data endpoint

---

frontend/src/v5/ui/components/shared/modalsDispatcher/modalsDispatcher.styles.ts
frontend/src/v5/ui/components/shared/modalsDispatcher/templates/deleteModal/deleteModal.component.tsx

This fixes #4290
The delete modal listens for the submit response and displays a "waiting" message to inform the user until the former is  received
Delete a porject/federation/model

ISSUE #4290 - delete message informs the user while processing

---

frontend/src/v5/ui/components/shared/revisionDetails/revisionDetails.component.tsx

This fixes #3790
A container with all the revisions being empty still shows them
Open a container that has all the

ISSUE #3790 - show revisions when they are all voided

---

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketView/ticketView.component.tsx

This fixes #4388
Added the clipping state to the updated object when updating the camera on a ticket
Open a custom ticket with a view property.
Try updating camera/view when also setting a clipping plane

ISSUE #4388 - Save camera does not save clipping planes

---

frontend/assets/icons/filled/question-filled.svg.tsx
frontend/src/v5/ui/components/shared/appBar/appBar.component.tsx
frontend/src/v5/ui/components/shared/appBar/intercom/intercom.component.tsx
frontend/src/v5/ui/routes/index.tsx

This fixes #4377
- Removed the default navbar launcher in the bottom left of the app
- Added a '?' icon to the navbar which acts as an intercom launcher
- Try to open the intercom launcher

ISSUE #4377 - Move intercom launcher to navbar icon

---

backend/src/scripts/utility/fileshare/identifyZombieFiles.js
backend/tests/v5/scripts/fileshare/identifyZombieFiles.test.js

This fixes #4415
write zombie paths into a file in chunks to prevent creating a string that is longer than supported by nodejs.
- should function as before
- should no longer crash when there's a lot of zombies

ISSUE #4415 write the zombies in chunks

---

frontend/src/v4/constants/viewer.ts
frontend/src/v4/modules/viewerGui/viewerGui.redux.ts
frontend/src/v4/modules/viewerGui/viewerGui.sagas.ts
frontend/src/v4/modules/viewpoints/viewpoints.sagas.ts
frontend/src/v4/routes/modelSettings/modelSettings.component.tsx
frontend/src/v4/routes/viewerGui/components/toolbar/toolbar.component.tsx
frontend/src/v4/routes/viewerGui/components/toolbar/toolbar.container.ts
frontend/src/v4/routes/viewerGui/components/views/components/viewItem/viewItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/settingsModal/settingsModal.component.tsx

This fixes #4207 
- The 'house icon' in the viewer toolbar has been renamed from 'Extent' to 'Home'
- A model's default view' has been renamed to its 'home view'
- If the model has a home view set then clicking the 'home' button will set the camera to it. Otherwise it will show the extent.
Note: The renaming has only been done for 'Default View' at the model level. The custom ticket property 'Default View' has not been renamed
Try using the home button with different Home Views
Try using it with no Home View

ISSUE #4207 - Make extents button use the default view

---

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketView/ticketView.component.tsx

This fixes #4425 
Updating by any means the camera in a custom ticket does not affect other elements of the viewpoint
In the viewer, open a ticket with a Viewpoint input.
Test whether creating/updating/deleting the camera input affects the other values

ISSUE #4425 - updating/deleting camera does not affect image

---

backend/src/v4/models/notification.js

This fixes #4432
When a model has finished processing, we're sending notifications to anyone who has read access through v4's notification centre.
V4 is essentially pulling out the list of users within the teamspace and checking if each of them has read access. With #4342, `hasAccessToTeamspace` now checks if the user also satisfy any enhanced security settings, and if not it will throw an error. These errors are not being caught by the v4 logic thus we ended up with an unhandled promise rejection.
test case mentioned in the issue should no longer crash the server.

ISSUE #4432 put a try around access checkers

---

frontend/src/v4/modules/tree/tree.sagas.ts
frontend/src/v4/modules/tree/tree.selectors.ts

This fixes #2514
Update tree visibility icon when "show all" is clicked from anywhere
- Open the card;
- Hide a node; (the visibility icon should switch to "hidden")
- Click show all  (the visibility icon should switch back to "visible").

ISSUE #2514 - update tree visibility icons when "show all" is triggered

---

frontend/src/v5/store/currentUser/currentUser.sagas.ts
frontend/src/v5/store/users/users.redux.ts
frontend/test/currentUser/currentUser.fixtures.ts
frontend/test/currentUser/currentUser.sagas.spec.ts
frontend/test/users/users.store.spec.ts

This fixes #3886 
Updating currentUser updates respective user
- In the container tab, expand a container with a revision created by the currentUser;
- Update currentUser first name;
- You should see the change reflected in revision author

Issue 3886 - Updating currentUser updates respective user

---

frontend/src/v4/modules/viewer/betaViewer.helpers.ts
frontend/src/v4/modules/viewer/viewer.sagas.ts
frontend/src/v4/modules/viewer/viewer.selectors.ts
frontend/src/v4/routes/components/topMenu/components/visualSettingsDialog/visualSettingsDialog.component.tsx
frontend/src/v4/routes/components/topMenu/components/visualSettingsDialog/visualSettingsDialog.styles.ts
frontend/src/v4/services/viewer/viewer.tsx

This fixes #4448 
Unity 2023 has been added as an experimental feature.
The logic to run it is already in place, but the final user needed an option to decide whether or not to use it.
In Visual settings, a toggle was added to decide which unity version to use.
The setting is stored in the local storage, but not as part of the currentUser. Instead, the same value is used by all the users accessing the platform from the same machine, meaning User1 changes will reflect on User2 account as well
Open visual settings and set "use beta viewer" to true. Closing and re-opening the modal, refreshing the page, and even logging in with another account should still show the setting set to true

Issue 4448 - Add option to run Unity2023

---

frontend/src/v5/ui/themes/theme.ts

This fixes #4180
Clear date does not overlap year
Open a ticket with issue properties and click on due date, then click on the header (e.g. December 2023)

ISSUE #4180 - clear date is hidden when selecting the year

---

frontend/src/v5/ui/v4Adapter/overrides/cards/groups.overrides.ts
frontend/src/v5/ui/v4Adapter/overrides/cards/issues/properties.overrides.ts
frontend/src/v5/ui/v4Adapter/overrides/cards/safetiBase/treatments.overrides.ts
frontend/src/v5/ui/v4Adapter/overrides/cards/sharedStyles/selectMenus.overrides.ts
frontend/src/v5/ui/v4Adapter/overrides/cards/sharedStyles/shapes.overrides.ts
frontend/src/v5/ui/v4Adapter/overrides/cards/views.overrides.ts
frontend/src/v5/ui/v4Adapter/overrides/panelsMenu.overrides.ts
frontend/src/v5/ui/v4Adapter/overrides/preview/previewDetails.overrides.ts

This fixes #3959
V4 editable inputs using textarea now have some padding on the right to not overlap the buttons which are now vertically displayed to take less horizontal room
Go to ay v4 components that has a description input, such as groups or issues

ISSUE #3959 - v4 textarea text does not overlap buttons

---

backend/src/v4/models/invitations.js

This fixes #3813
Bug fix in invitation functionality. An error is not thrown anymore when a user has filled the invitation limit and tries to edit an invitation.
Invite as many people to 3D Repo as possible. eg if the limit is 50, send 50 invitations
Try to edit the permissions or job title of an existing invitation
An error should not be thrown anymore

ISSUE #3813 - Invitation limit bug fix

---

frontend/src/v4/routes/viewerGui/components/tree/components/treeNode/treeNode.component.tsx
frontend/src/v4/routes/viewerGui/components/tree/components/treeNode/treeNode.styles.ts

This fixes #4376 
Containers names in Tree are cut at the start instead of the end
Open a container in tree (viewer) with a name long enough;
Do the same with a federation with a container with a name long enough

ISSUE #4376 - Container name visibility in tree

---

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx

This fixes #4413 
Objects count in custom ticket groups (manual mode) is now correct
Open a ticket with groups, set the selection mode to manual and compare the objects count with a normal group. The numbers should match

ISSUE #4413 - The 'Selected Objects' count for a manual group in a ticket is wrong

---

frontend/src/v4/routes/viewerGui/components/risks/components/autoSuggestField/autosuggestField.component.tsx
frontend/src/v4/routes/viewerGui/components/risks/components/autoSuggestField/autosuggestField.styles.ts

This fixes #4461 
Autosuggest fields now position the items correctly (note that also some fields in "properties" for issue and in "risks" for safetibase were incorrectly positioned)
Open a risk ticket and check "risk factor", "element type", etc in the first tab and "type" and "stage" in the treatment tab

ISSUE #4461 - V4 autosuggest field is correctly positioned

---

frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx

This fixes #4400
The ticket count in the template chips now updates to reflect the number of tickets in the respective template that matches the search filters and completed state.
For a better explanation of how the numbers should work look at the comments in the issue
Check that the numbers are right when selecting different chips and using different/multiple search terms

ISSUE #4400 - Fix template chip ticket count not updating

---

frontend/src/v5/ui/components/shared/breadcrumbsRouting/breadcrumbsRouting.component.tsx
frontend/src/v5/ui/controls/breadcrumbs/breadcrumbs.helpers.ts

This fixes #4509
Remove the alphabetisation of the revision breadcrumb options
Open the revision breadcrumb options
Check the federations and containers breadcrumb options are still alphabetical

ISSUE #4509 - Revisions breadcrumbs are ordered by uploaded at

---

frontend/src/v4/routes/components/topMenu/components/visualSettingsDialog/visualSettingsDialog.component.tsx

This fixes #4496 
Presumably a merge cause the visual settings to display both an old input and the new viewer background input
The former has been removed
Open visual settings and check everything looks fine

Issue 4496- Visual settings UI issue

---

frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemButton/dashboardListItemButton.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationListItem/federationListItem.component.tsx

This fixes #4505
The buttons depicting the number of issues/risks on the federations dashboard list now take you to their respective kanban page
Try looking at different federations issues and risks pages by using these buttons

ISSUE #4505 - Add function to risks/issues buttons on federation list items

---

frontend/src/v4/constants/viewer.ts
frontend/src/v4/modules/viewer/betaViewer.helpers.ts

This fixes #4517
"undefined" was passed as a string and saved in the local storage.
Reading and parsing such a value was the problem since the value was a string
Change the viewer background color, save, and reset the settings

ISSUE #4517 - fix: reset visual settings crashes the app

---

frontend/src/v5/ui/controls/formModal/formModal.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederationContainersList/editFederationContainersListItem/editFederationContainersListItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederationContext.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederationModal.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationListItem/federationEllipsisMenu/federationEllipsisMenu.component.tsx

This fixes #4263
- A viewer cannot edit a federation but can still view the modal. Changes have been made so that it appears like a view federation modal when the user is a viewer. This includes:
- Ellipsis menu item says 'View Federation'
- Modal title changed to 'Viewing <federation>'
- Removed the submit button
- Disabled the 'group' autocomplete
View a federation as a viewer.
There should be nothing that suggests it is editable

ISSUE 4263 - View only federation has edit federation partial interface

---

frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx

This fixes #4545 
Custom ticket data is now correctly fetching upon opening a ticket details
Edit a ticket (edit some properties that do not belong to issue properties) and refresh the page.
The edit data should show up

Issue 4545 - fetch ticket data

---

backend/src/v5/services/mailer/templates/html/systemTemplate.html

This fixes #4540
logo size adjusted to be 50% of the div
system emails should now be formatted correctly

ISSUE #4540 fix logo size on system email templates

---

backend/src/v4/config.js
frontend/src/v4/modules/viewer/betaViewer.helpers.ts

This fixes #4573
- 4GB should be the default viewer
- 3drepo.io front end should only run with API servers within the same domain (whilst subdomain API service is still supported)

Issue 4573 - Issues around the 4GB viewer

---

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketView/ticketView.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groupToggle/groupToggle.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groupToggle/groupToggle.styles.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx

This fixes #4580 
- Fixes edition of groups in tickets
- Creation of new groups in new tickets
**1**
- Create a custom ticket with a default view and proceed to create 2 groups
- Refresh
- Try to edit one of the 2 groups
- The panel should be populated after the first click
**2**
- Click on  new ticket with a template with a viewpoint
- Without saving the new ticket create a group
- Edit the group
- The form should have the correct group data
**3**
- Click on  new ticket with a template with a viewpoint
- Without saving the new ticket create a group
- Try to create another group
- Both groups should appear and be editable

Issue 4580 - hot fix for groups issues

---

frontend/src/v4/routes/teamspaceSettings/teamspaceSettings.component.tsx

This fixes #4609 
Updating and saving anything in the teamspace reflects the state correctly
Go to teamspace settings, change something and press save

Issue 4609 - Updating teamsapce settings doesn't show new setting until component re-render

---

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupItem/groupItem.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groupsAccordion/groupsAccordion.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroupsContext.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroupsContext.ts

This fixes #4591
- When the user tries to hide all hidden groups, it should deselect any selected groups within the category
- Newly created hidden groups should be hidden by default instead of shown
- If the group you have selected is deleted, it should not auto select the next group
Test them

Issue 4591 - Custom ticket groups - UX Improvements

---

frontend/src/v4/constants/sequences.ts
frontend/src/v4/modules/sequences/sequences.helper.ts
frontend/src/v4/routes/viewerGui/components/sequences/components/sequencePlayer/sequencePlayer.component.tsx

This fixes #4637 
Added the "week" interval step to sequences card
Open a model with sequences, open any sequences from it, and check the week step is available and working correctly

ISSUE #4637 - add Week interval to sequences card

---

frontend/src/v4/constants/issues.ts
frontend/src/v4/constants/risks.ts
frontend/src/v4/modules/board/board.selectors.ts
frontend/src/v4/modules/issues/issues.redux.ts
frontend/src/v4/modules/issues/issues.selectors.ts
frontend/src/v4/modules/risks/risks.redux.ts
frontend/src/v4/modules/risks/risks.selectors.ts
frontend/src/v4/routes/components/filterPanel/filterPanel.component.tsx
frontend/src/v4/routes/viewerGui/components/issues/issues.component.tsx
frontend/src/v4/routes/viewerGui/components/reportedItems/reportedItems.component.tsx
frontend/src/v4/routes/viewerGui/components/risks/risks.component.tsx

This fixes #4584 
Instead of hiding closed items, set the filters to only show the open ones and make the filter selection immediately visible
- Open the issues list and see that the items visible at the beginning are the same as before the changes;
- Remove all the filters and you should be able to see all the issues, even the ones "closed" or "void"
- Repeat for risks (a risk is considered "close" depending on the treatment_status)

Issue 4584 - Issues and risks: show default filtering on the search

---

frontend/src/v5/services/actionsDispatchers.ts
frontend/src/v5/ui/routes/viewer/toolbar/buttons/toolbarButton.styles.ts
frontend/src/v5/ui/routes/viewer/toolbar/selectionToolbar/sectionToolbar.styles.ts
frontend/src/v5/ui/routes/viewer/toolbar/selectionToolbar/selectionToolbar.component.tsx
frontend/src/v5/ui/routes/viewer/toolbar/toolbar.styles.ts

This fixes #4567
Add clear selection button in the toolbar
Select (highlight) any objects in the viewer:
- the clear selection button should show up;
- clicking it should clear the selection

Issue 4567 - Add clear selection button

---

backend/src/v4/models/issue.js
backend/src/v4/models/report.js
backend/src/v4/models/risk.js

This fixes #4660 
Issue and Risk reports now include links that redirect to a v5 page rather than a v4 page
- Open a model with risks/issues
- Click on Create Report
- Click on Click to load risk/issue in 3D Repo or the screenshot in the report
- It should redirect to V5 viewer with the issue/risk selected

ISSUE #4660 - Issue and Risk reports now have V5 links

---

frontend/src/v5/store/tickets/tickets.validators.ts
frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsList/slides/ticketSlide.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx

This fixes #4621
Imagine this scenario:
- you edit the title of ticket;
- as the ticket is still focused, you change the ticket using the arrows
The ticket data is updated, but onBlur has not been called yet. By the time onBlur is called, the data is compromised as it refers to the new ticket, so the saving actions is triggered against the new ticket.
What I have done is to make sure that, before changing (or closing by any means) the current ticket, the data is saved
1. Edit the title -> as it is still focused, change ticket;
2. Edit the title -> as it is still focused, go back to the ticket list;
3. Edit the title -> as it is still focused, close the ticket card.
Repeat using other inputs.
The ticket should always be saved correctly. In case of `scenario 1`, make sure the next ticket is …

ISSUE #4621 - leaving a ticket saves unsaved changes

---

frontend/src/v4/modules/tree/tree.sagas.ts

This fixes #4649 
To prevent BIM panel showing no data (or previously selected node data), the metadata is constantly refreshed
- select a node and then open the bim card: the data should be visible;
- (from the previous scenario) close the bim card, select a different node, re-open the bim card: the data should be updated to the currently selected node

ISSUE #4649 - BIM card: show information even if node is selected before panel opens

---

frontend/src/v5/store/tickets/tickets.sagas.ts

This fixes #4684 
If more than one call to fetch tickets was executed concurrently, sagas was neglecting them all but the latest, meaning only the tickets from the last selected model were fetched
1. Find two models that share tickets of the same template
2. Try to open them both in tabular view with that template (you can also refresh once in the tabular view)

ISSUE #4684 - Selecting multiple models in tabular view only shows tickets for the last selected model

---

frontend/src/v5/validation/shared/validators.ts

This fixes #4667
Deleting a string property in a ticket (i.e. setting it to "", saving, and then receiving "null" from ws) was breaking the validation
Delete any string property and then try to delete a required property. Some "error" should be visible in the ticket and no modals should be triggered

ISSUE #4667 - fix: deleting a string input in ticket breaks validation

---

backend/src/v4/routes/invitations.js

This fixes #4465
Small API v4 doc fix in get invitations list enpoint
"project" is a valid guid instead of "Bim Logo"
The documentation is getInvitationsList endpoint should be correct

ISSUE #4465 - V4 small API doc fix

---

frontend/src/v5/store/projects/projects.sagas.ts

This fixes #4645 
- The project was created in redux before uploading an image, this caused the image to fail  because the first render was without an uploaded image. Moved after the image is uploaded to create the project in redux with a image already there
- Create a project with an image
- The image project is now visible without having to refresh

ISSUE #4645 - Fix of project image when creating the project

---

frontend/src/v5/ui/controls/actionMenu/actionMenuItemLink/actionMenuItemLink.component.tsx
frontend/src/v5/ui/controls/actionMenu/actionMenuItemLink/actionMenuItemLink.styles.ts

This fixes #4542 
The Visual Settings item was using a react-router-dom <Link /> which was removing search parameters on click. Since this option should not affect the URL I have avoided using it here
With url parameters in place try to open the visual settings

ISSUE #4542 - Opening the Visual Settings was clearing the URL params

---

frontend/src/v5/services/realtime/ticket.events.ts
frontend/src/v5/store/tickets/tickets.types.ts

This fixes #4699 
When the frontend receives a chat event that a ticket was updated, if the objects does not have standard _ids (i.e. revit or ifc ids) refetch the group
Create a container with an ifc (or revit) revision.
Create a manual group and then update it.
The object count should be correct.
Repeat with a federation that contains the aforementioned container

ISSUE #4699 - Frontend doesn't read ifc/revit ids in groups

---

frontend/src/v5/services/api/tickets.ts
frontend/src/v5/services/realtime/ticket.events.ts
frontend/src/v5/store/tickets/tickets.redux.ts
frontend/src/v5/store/tickets/tickets.sagas.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/tickets.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
frontend/test/tickets/tickets.sagas.spec.ts

This fixes #4689 
Revision Id is included as an optional search param when calling GET ticketGroup.
Since to avoid unnecessary calls to the backend, we were not re-fetching a group when it was already stored in redux, but different revisions have different object ids, the groups are cleared every time a different revision is selected
Open a container with 2 ifc/revit revisions (upload the same revision twice) and proceed to create a smart ticket group from either revision. Then switch revision. The object count should be the same.

ISSUE #4689 - add revision param to fetchTicketGroup

---

frontend/src/v4/routes/viewerGui/components/sequences/sequences.component.tsx
frontend/src/v4/routes/viewerGui/components/sequences/sequences.container.tsx

This fixes #4698
Exiting a sequence clears the transformations
Open a sequence and go to a frame that has transformations on, then exit the sequence.
The transformations should be cleared

ISSUE #4698 - Exiting a sequence clears the transformations

---

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesForm.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleFieldValues/fieldValueInput/fieldValueInput.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleFieldValues/ruleFieldValues.component.tsx

This fixes #4548
When you create a filter for a smart group the autofocus is now on the name field
When adding a value field the input is focused
Create a new smart group filter
- The autofocus should initially be on the name
- Adding new value fields should set the focus to the new field
Edit an existing smart group filter
- The autofocus should still be on the name no matter how many value fields exist
- Upon adding new value fields the focus switches to the new field input

ISSUE #4548 - Smart group value fields only get autofocus when adding a new field

---

frontend/src/v5/ui/routes/viewer/tickets/ticketDetailsCard/ticketDetailsCard.styles.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketDetailsCard/ticketsDetailsCard.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/tickets.component.tsx

This fixes #4720 
When ticket's title is too long, the surrounding (the back arrow and the `:Groups` text) are kept the same width, whereas the title takes up the remaining space and gets truncated if needed
- Open a ticket with a view and set the name to something long enough
- go to groups

ISSUE #4720 - truncate ticket's title when viewing groups

---

frontend/src/v4/routes/viewerGui/viewerGui.component.tsx
frontend/src/v4/routes/viewerGui/viewerGui.container.ts
frontend/src/v5/store/tickets/card/ticketsCard.redux.ts
frontend/src/v5/store/tickets/card/ticketsCard.selectors.ts
frontend/src/v5/ui/routes/viewer/tickets/newTicket/newTicket.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticket.context.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/tickets.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/tickets.constants.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/ticketView/ticketView.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx

This fixes #4748 
- Rollback to how ticket groups worked.
- Added isEditting group to avoid clashes when editing the group and showing the viewpoint.
- Creating a new ticket and editing the groups in the moment should work
**No regression bugs:**
- Selecting a ticket in the list should show the view, closing and opening the ticket card should not reset the view.
- Editing groups should work as expected

ISSUE #4748 -Fix crash when editing groups in new ticket

---

frontend/src/v5/store/tickets/card/ticketsCard.redux.ts
frontend/src/v5/store/tickets/card/ticketsCard.sagas.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketDetailsCard/ticketsDetailsCard.component.tsx

This fixes #4770 
- Revert gobackfromgroups to use the ticketcontext
- go into a a ticket that can contain groups
- edit groups
- go back -> now it shows the ticket form.

ISSUE #4770 - Fixed going back from group edition in ticketdetails

---

tools/release/git_release.py

This fixes #4768 
- git_release should keep untracked files

ISSUE #4768 - do not clean on git_release

---

backend/src/v5/routes/teamspaces/projects/models/common/tickets.js
backend/tests/v5/e2e/routes/teamspaces/projects/models/common/tickets.test.js
frontend/src/v5/services/api/tickets.ts
frontend/src/v5/store/tickets/tickets.redux.ts
frontend/src/v5/store/tickets/tickets.sagas.ts

This fixes #4798
- Updated front end to call with `filters` instead of `filter`
- Updated swagger so it is now correct
- Fixed the test - so it actually will detect if it is not working
- swagger should now work with the filter query
- front end should be fetching additional properties again

ISSUE #4798 Ensure everything is addressing the custom ticket query string as `filters` instead of `filter`

---

frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsList/slides/ticketSlide.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx

This fixes #4845 
Side panel was taking a copy of the ticket store in the state, so the data was updating together with the ticket in the state. Now the side panel receives the ticket id and uses it to reflect updates in the ticket from the store
Open a ticket that has custom modules and check the data is there when the ticket is first opened

ISSUE #4845 - side panel ticket is always up to date

---

frontend/src/v4/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx
frontend/src/v4/routes/viewerGui/components/groups/components/groupDetails/groupDetails.container.ts
frontend/src/v4/routes/viewerGui/components/groups/components/groupDetails/groupDetailsForm.component.tsx

This fixes #4702
New group (v4) objects counts matches the number of elements selected in the viewer and if, upon opening the group card, there are some objects selected, the group can be saved straight away
- Select some elements in the viewer
- Click on "new group"
- The save button should be enabled

ISSUE #4702 - New group objects counts reflects selected objects

---

backend/tests/v5/scripts/modelProcessing/cleanUpSharedDir.test.js

This fixes #4873
Instead of deducting the days from the date, calculate it in timestamp values to avoid confusion.
Autotest should now pass.

ISSUE #4873 fix autotest

---

backend/src/scripts/utility/modelProcessing/cleanUpSharedDir.js
backend/tests/v5/scripts/modelProcessing/cleanUpSharedDir.test.js
frontend/src/v5/ui/components/viewer/cards/tickets/sequencingProperty/sequencingProperty.component.tsx

This fixes #4842
- Fix conditionals which were rendering a 0 when false
- Open an existing ticket which has a sequence module
- Set one of the dates
- Clear the date
- The input should correctly show as empty with no trailing '0's

ISSUE #4842 - fix 0s appearing in cleared sequence fields

---

frontend/src/v4/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx

This fixes #4885
The "object count" value displayed in the expanded groups reflects the "totalSavedMeshes" value as store in redux as opposed to the currently selected objects
Exapnd an existing group and try to select more (or deselect the group's) meshes. The "objects count" value should not change

ISSUE #4885 - Existing group's object count reflects value in redux

---

frontend/package.json

This fixes #4899
If circular dependecies fail, the next 2 linting tests still pass.
I also removed the `--exclude /node_modules` from the dpdm command as it was having the opposite effect (node modules are ignored by default)
Create a circular dependency and a css error, then run the whole linting suite `yarn lint`. The test should output both the erros

ISSUE #4899 - all linting tests execute even if one fails

---

frontend/src/v5/store/tickets/tickets.selectors.ts
frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.component.tsx

This fixes #4896
Templates are fetched only once when landing one the page
- Open the tab network
- Go to the tickets table tab
- Select a template and a bunch of cons/feds
- Open the table
You should only see 1 requests to get templates

ISSUE #4896 - Fetching ticket template lists multiple times

---

backend/src/v5/processors/teamspaces/projects/models/federations.js
backend/tests/v5/e2e/routes/teamspaces/projects/models/common/general.test.js
backend/tests/v5/unit/processors/teamspaces/projects/models/federations.test.js

This fixes #4919
- return units in federation stats

ISSUE #4919 return units on federation stats as well

---

frontend/src/v5/ui/controls/chip/chipSelect/chipSelect.component.tsx

This fixes #4819
The problem was caused by the dropdown menu that allows you to select an option and immediately after, before the menu collapses, to select another option.
My best advice would be to slow down the closing animation of the menu and click repeatedly on the menu items. You can do pasting
```css
.MuiMenu-paper {
transition-duration: 2s !important;
}
```
inside the style tag of  `index.html`

ISSUE #4819 - can only select one option at a time

---

backend/src/v5/models/tickets.comments.js
frontend/src/v5/store/tickets/comments/ticketComments.helpers.ts
frontend/src/v5/store/tickets/comments/ticketComments.types.ts
frontend/src/v5/store/users/users.helpers.ts
frontend/src/v5/store/users/users.selectors.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/basicComment/basicComment.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/comment.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/commentNonMessageContent/commentNonMessageContent.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/commentReply/commentReply.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/otherUserComment/importedUserPopover/importedUserPopover.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/otherUserComment/importedUserPopover/importedUserPopover.styles.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/otherUserComment/otherUserComment.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/otherUserComment/otherUserComment.styles.ts
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/commentsPanel.component.tsx

This fixes #4866 
Imported tickets comments now display the original author, both in basic comments and in replies.
The userPopover also reflects this change
Import a ticket with a bunch of comments. Include comments with replies and make sure one of message you replied to, comes from a user with your username.
> i.e.
```js
{
"tickets": [
// ...
"comments": [
// ...
{
// ...
// comment reply
"message": "[_id]:- \"<id>\"\n[author]:- \"<SAME_AS_YOUR_UERNAME>\"\n[message]:- \"<message>\"\n[images]:- \"\"\n\n<reply>",
}
]
]
}
```
You will need to use swagger to import a ticket https://3drepo.lan/docs/#/Tickets/importTickets

ISSUE #4866 - Use imported data in comments when there is an imported ticket

---

backend/src/v5/schemas/tickets/index.js
backend/src/v5/utils/helper/yup.js
backend/tests/v5/unit/schemas/tickets/index.test.js
backend/tests/v5/unit/utils/helper/yup.test.js

This fixes #4917
Avoid transforming nulls to a date in the middleware
- when updating a date to null (i.e. removing the property, the property shoudl be removed now.

Issue 4917 - When dates are set to null, they shoudl be removed instead of being set to 0

---

backend/src/v5/models/tickets.js
backend/tests/v5/unit/models/tickets.test.js

This fixes #4803
The check to determine if we're updating or removing a property value is by just evaluating the value itself to a boolean. 0 evaluates to false therefore it was being treated as if it's set to null.
Logic has checked so we specifically check for null instead.
updating a number to 0 should no longer cause it to be unset.

ISSUE #4803 only unset the value if it's null

---

backend/src/v5/schemas/tickets/templates.js
backend/src/v5/utils/helper/arrays.js
backend/tests/v5/unit/schemas/tickets/templates.test.js

This fixes #4796
- values provided in `oneOf` and `manyOf` property should be unique
- names within custom statuses should be unique
- creating a template with duplicated values in `oneOf` or `manyOf` property should fail
- creating a template with custom status where there is a duplicate in `name` should fail

Issue 4796 - values in oneOf and manyOf should be unique

---

backend/src/v5/models/tickets.js
backend/tests/v5/unit/models/tickets.test.js

This fixes #4889
When removing a model (or project), remove ticket counter entries associated with the model
- counter entries associated with the model should be removed from the database
- other counters should remain

ISSUE #4889 when deleting a model, remove ticket counter for tickets within the model

---

backend/src/v4/models/bcf.js
backend/src/v4/models/ticket.js

This fixes #4953
- update logic is replacing the comments with the old ones if we're trying to add a system comment.
- `addPreExistingComment` has very different function parameter order to what `bcf.js` is expecting...
the situation mentioned in the issue should now work.

ISSUE #4953 BCF fixes

---

frontend/src/v5/ui/controls/virtualList/virtualList.component.tsx

This fixes #4980
The onScroll halts if the main container is not yet rendered
Switch from the federations to the containers tab. The typeError should no longer be printed and the virtual list should work as before

ISSUE #4980 - TypeError when revisiting tabs in Project

---

frontend/src/v4/services/viewer/viewer.tsx

This fixes #4987
This was a result of moving the viewer canvas further down the DOM so that it can easily be resized (e.g. with the 2D splitter).
Before the canvas was always present in the background and so never re-rendered. This changed caused the canvas component to be re-rendered whenever entering the viewer. This would cause the exact same canvas component to be re-added to the DOM.
Now the unity component is only added to the DOM if it doesn't already exist
Navigate to and from the viewer. See if it remains responsive. Look in the DOM and there should be just one `<canvas />` component

ISSUE #4987 - Fix viewer becoming unresponsive when renavigated

---

frontend/src/v4/routes/components/criteriaField/newCriterionForm/newCriterionForm.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesForm.component.tsx

This fixes #4989
The method for getting the model id didn't work in the groups card. So the form could not see if it should be disabled
Check the smart group fields are not disabled in both custom tickets and the groups card

ISSUE #4989 - fix group card smart group fields being incorrectly disabled

---

frontend/src/v4/routes/viewerCanvas/viewerCanvas.component.tsx
frontend/src/v5/helpers/functions.helpers.ts

This fixes #4753 
The action of removing/adding pins, or changing the selected one, was asynchronous, but treated as synchronous
- Have 2 tickets with a default pin set
- Select one ticket (ticket A), but do not expand it
- Then click on the other ticket's pin from the viewer
Ticket A's default pin should not be visible in the viewer

ISSUE #4753 - Default Pins for other tickets sometimes persist when opening ticket details

---

.azure/build-and-deploy.yaml
backend/src/v4/handler/elastic.js

This fixes #5026
- Update chart version
- `namespace` should appear in Elastic `io-actiity` records

ISSUE 5026 - Update io chart to v5.11.0

---

backend/src/v5/routes/teamspaces/projects/models/containers/revisions.js

This fixes #5050
In Revision list endpoint timestamp is now displayed as a number

ISSUE #5050 - Swagger fix to display timestamp as a number

---

frontend/src/v5/ui/routes/viewer/toolbar/buttons/buttonOptionsContainer/projectionButtons.component.tsx

This fixes #2475
Changing the projection mode from the the toolbar resets the view to "home view"
Change the projection mode

ISSUE #2475 - changing projection mode from toolbar goes to home view

---

frontend/src/v5/ui/routes/viewer/openDrawingFromUrl/openDrawingFromUrl.component.tsx
frontend/src/v5/ui/routes/viewer/viewer.tsx

This fixes #4993
Reaching a URL with a drawingId as a search param opens the drawings card
- Reach a URL with a drawingId as a search param (**not** in calibration mode) and refresh the page
- In the viewer, open a drawing, then calibrate a different drawing, and then cancel the calibration
In both cases, the drawings card should be open

ISSUE #4993 - expand drawings card if drawing id is in the URL

---

frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemTitle.styles.ts

This fixes #5024
Dashboard list items (drawings, cons, feds) use the same styling
Check all the dashboard list items share the same styling

Issue 5024 - Milestone 1 - Drawing's list have a different style for title than containers

---

frontend/src/v5/store/tickets/card/ticketsCard.selectors.ts
frontend/src/v5/ui/routes/viewer/tickets/newTicket/newTicket.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/tickets.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/coordsProperty/coordsProperty.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/coordsProperty/coordsProperty.helpers.ts

This fixes #5095
The unsavedTicket in redux is now updated as the new ticket's data updates.
So doing, the new ticket pins are removed only when the ticket view changes
Open a new ticket and drop a pin, then
- close the tickets card. The pins should still be there.
- save the ticket. The pins should display correctly
- go back to the list without saving the ticket. The pins should be gone

Issue 5095 - New ticket pins are visible when the tickets card is close

---

frontend/src/v5/services/realtime/drawingRevision.events.ts
frontend/src/v5/store/drawings/revisions/drawingRevisions.redux.ts
frontend/src/v5/store/drawings/revisions/drawingRevisions.types.ts
frontend/src/v5/ui/routes/dashboard/projects/drawings/drawingsList/drawingsListItem/drawingsListItem.component.tsx

This fixes #4901
Added real time events for drawing revisions
With 2 different users, have the same drawing item expanded and, using one user:
- change the status to void/non-void for any revisions of such a drawing;
- create a new revision for such a drawing.
The changes should be visible for the other user without refreshing the page

Issue 4901 - Drawing revisions realtime

---

frontend/src/v5/ui/components/shared/drawingRevisionDetails/drawingRevisionDetails.component.tsx

This fixes #5128
- Updated downloading of drawing to use the cross-site token.
- Updated the name of the file downloaded to match the file extension
- upload a .dwg and then try downloading it and open it

ISSUE #5128 - Fixed downloading a .dwg file

---

frontend/src/v5/ui/controls/inputs/select/select.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/drawings/drawingDialogs/drawingsDialogs.hooks.ts

This fixes #5129 
This bug was caused because by default MUI Selects search the children for the key that matches the value provided and use the label provided with that option. A collaborator does not have access to the drawing categories list, so the Categories Select had no children hence no matching child was found and no value was rendered.
I have fixed this by tweaking how our selects render the value. A select will still search the children for the matching key as before but it now has a fallback where it will render the value if no matching child is found. This will also fix a problem I found where the options of a select change (e.g. using the API to alter a custom ticket) and selects appearing empty when they in fact have a value that just no longer exists in the list.
I also …

ISSUE #5129 - [2D MVP] Milestone 1: Collaborators should be able to see drawing category

---

backend/src/v5/services/eventsListener/components/modelEvents.js
frontend/src/v5/services/realtime/drawingRevision.events.ts
frontend/src/v5/store/drawings/drawings.helpers.tsx
frontend/src/v5/store/drawings/drawings.selectors.ts
frontend/src/v5/store/drawings/revisions/drawingRevisions.helpers.ts
frontend/src/v5/store/drawings/revisions/drawingRevisions.redux.ts
frontend/src/v5/store/drawings/revisions/drawingRevisions.selectors.ts
frontend/src/v5/ui/components/viewer/drawingViewer/viewer2D.component.tsx
frontend/src/v5/ui/controls/thumbnail/thumbnail.component.tsx
frontend/src/v5/ui/controls/thumbnail/thumbnail.styles.ts
frontend/src/v5/ui/routes/dashboard/projects/drawings/drawingsList/drawingsListItem/drawingsListItem.component.tsx
frontend/src/v5/ui/routes/viewer/drawings/drawingsList/drawingItem/drawingItem.component.tsx
frontend/src/v5/ui/routes/viewer/drawings/drawingsList/drawingItem/drawingItem.styles.ts
frontend/src/v5/ui/routes/viewer/drawings/drawingsList/drawingsList.component.tsx
frontend/src/v5/ui/routes/viewer/drawings/drawingsList/drawingsListCard.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketItem/ticketItemThumbnail/ticketItemThumbnail.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketItem/ticketItemThumbnail/ticketItemThumbnail.styles.ts

This fixes #4841
Wire in backend calls for drawings card. This includes the thumbnail and the actual drawing image.
Realtime was also added, so changing the last active revision in a drawing (toggling the state or uploading a new revision) should update the drawing data accordingly.
**LIMITATION**: 
- Changing from 0 to 1+ revisions (and vice versa) is not yet detectable by the app. 
As such, imagine a drawing with 1 active revision. Setting such a revision to void should remove the drawing from the list, but it does not. The other way around also happens, that is, if a drawing has 1 void revision, setting that revision to active will not show the drawing in the list until refresh.
Drawing card should correctly display all the drawings with at least 1 (active) revision, their data, and …

Issue 4841 - Milestone 2: backend integration

---

frontend/src/v5/helpers/intl.helper.ts

This fixes #5140
Backend and frontend now use the same storage units, so the user see the right amount
Check the quota storage displayed matches what you should expect based on the network request value

Issue 5140 - Quota calculation should be in IEC units

---

frontend/src/v4/modules/viewerGui/viewerGui.redux.ts

This fixes #5102 
The check to see whether too many left panel cards are open wasn't first checking whether the updated panel belonged to the left panels. This meant any updated panel would see that there are already 2 left panels open and close the oldest
Open up a load of panels in the viewer. It should all function logically.

ISSUE #5102 - Clicking on a sequence task item affects other viewer cards

---

frontend/src/v5/store/projects/projects.sagas.ts
frontend/src/v5/store/teamspaces/teamspaces.sagas.ts
frontend/src/v5/ui/components/shared/modalsDispatcher/templates/alertModal/alertModal.component.tsx
frontend/src/v5/validation/errors.helpers.ts
frontend/test/projects/projects.sagas.spec.ts
frontend/test/teamspaces/teamspaces.sagas.spec.ts

This fixes #5120 
The user is now able to see al the teamspaces listed.
The user will only get an error message after trying to access an SSO teamspace if are not SSO linked, 
Create an SSO only teamspace and have a non-SSO user.
- Go to the homepage: the user should be able to see that teamspace;
- Try to access that teamspace: an alert modal should explain that the user cannot access that teamspace and they should be redirected to the homepage

Issue 5120 - Teamspaces list fails with a non SSO user for a teamspace with SSO access only

---

frontend/src/v4/routes/components/dateField/dateField.component.tsx
frontend/src/v5/services/intl.ts

This fixes #5150
The problem was caused because date values that were null were being passed to formatDate. I have fixed the base format date function so that it will only format the date if a date is actually provided
Look at date inputs that have their values unset. They should no longer read 1/1/1970 00:00

ISSUE #5150 - The dates in the date pickers show "1/1/1970 01:00" when they are not set

---

frontend/src/v4/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx

This fixes #5153
The onclick event for the risk card header was still being applied when in the kanban board. This caused goToViewpoint to be triggered when you are not in the viewer
- In the kanban try to clone a risk
- Click the headers of both risks and issues

ISSUE #5153 - Fixed clicking header of risk in kanban causes crash

---

frontend/src/v5/store/drawings/drawings.helpers.tsx
frontend/src/v5/ui/routes/dashboard/projects/drawings/drawingsList/drawingsListItem/drawingsEllipsisMenu/drawingsEllipsisMenu.component.tsx

This fixes #5174
- changed the ellipsis menu option for 'upload to drawing' so that it is only enabled when an active upload isn't ongoing
Try to upload a file to a drawing that currently has an ongoing upload (Tip: Pause the bouncer in docker to get a file stuck in the queue)

ISSUE #5174 - disable upload option when previous upload is still ongoing

---

frontend/src/v5/ui/routes/viewer/toolbar/toolbar.component.tsx

This fixes #5185
Comment out the UI for focus mode (so that it can quickly be reinstated if it is missed)
Focus mode should not be visible in the viewer toolbaar

ISSUE #5185 - Remove focus mode

---

frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsList/slides/ticketSlide.component.tsx

This fixes #5175
This was happening because the fetchTickets call was happening _after_ the fetchTicket call. fetchTicketsSuccess was then overwriting the more descriptive fetchTicket data.
- Ensure the data is accurate when refreshing tabular view with a ticket open
- Ensure that the bug described [here](https://github.com/3drepo/3drepo.io/pull/4961#issuecomment-2122727759) still does not occur (this is why the `useSelectedModels()` code was added)

ISSUE #5175 - Reaching tabular view with a ticket open does not display all the properties

---

backend/src/v5/utils/sessions.js
backend/tests/v5/unit/utils/sessions.test.js

This fixes #5199
- escape regex characters on the domain value before putting it through a regex match
-  added a unit test for this issue
Should no longer throw an exception if domain is an invalid regex pattern

ISSUE #5199 catch error from regex match

---

backend/src/v5/models/projectSettings.js
backend/tests/v5/helper/services.js
backend/tests/v5/unit/models/projectSettings.test.js

This fixes #5204
createdAt property is added to the project
Creating a new project should have createdAt property in it

ISSUE #5204 - createdAt property added in Projects

---

frontend/src/v5/ui/routes/dashboard/projects/calibration/calibrationContext.tsx
frontend/src/v5/ui/routes/dashboard/projects/drawings/drawingsList/drawingsListItem/drawingsListItem.component.tsx
frontend/src/v5/ui/routes/viewer/drawings/drawingCalibrationMenu/drawingCalibrationMenu.component.tsx
frontend/src/v5/ui/routes/viewer/toolbar/toolbar.component.tsx

This fixes #5191
Fixed the disabled state for calibration button when permission is lower than collaborator.
To prevent reaching the calibration in the viewer pasting a URL with `isCalibrating=true`, the context returns false if the user has no collaborator+ permissions
Try to access calibration with user on collaborator+: they should get access to calibration. All the other users should not

Issue 5191 - Milestone 3: permissions bug

---

backend/src/v5/handler/queue.js

This fixes #5241
Add some additional logging when the service starts, and when a message is put into the queue for easier diagnosis in the future
should function as before

ISSUE #5241 Add some logging in queue service

---

frontend/src/main.tsx
frontend/src/v5/ui/components/shared/appBar/appBar.component.tsx
frontend/src/v5/ui/components/shared/appBar/appBar.styles.ts
frontend/src/v5/ui/components/shared/modalsDispatcher/templates/alertModal/alertModal.component.tsx
frontend/src/v5/ui/routes/notFound/notFound.component.tsx

This fixes #5234
The 404 page was whitescreening when it fell outside of the /v5/ path. e.g. `/v5/dsada` worked but `/dsada` whitescreened.
This was because authentication is only done at the /v5/ level so the 'AuthenticatedRoute` for `<NotFound />` was failing.
I have changed the 404 page outside of the v5 route to be a regular `<Route />` and adapted the `<NotFound />` page to be suitable for unauthenticated users.
Try these urls:
- https://3drepo.lan/v5/nonexistentpage 
For authed user they should see the 404 page
For an unauthed user they should be redirected to login
- https://3drepo.lan/nonexistentpage 
For authed user they should see the 404 page
For an unauthed user they should see the 404 page whichhasbeen adapted for an unauthed user
The rest of the app should be as accessible …

ISSUE #5234 - Not Found page outside of /v5/ path whitescreening

---

frontend/src/v5/ui/controls/successMessage/successMessage.styles.ts

This fixes #5253 
The icon container was too small
Try to login with invalid credentials and check the icon

ISSUE #5253 - Error icon is missing

---

backend/package.json
backend/src/v5/utils/helper/userAgent.js

This fixes #5239
useragent package removed and its functionality is covered by ua-parser-js
Log in to 3d repo from a browser and from plugin
Inspect sessions in robo 3t
One should have webSession: true and another should have webSession: false

ISSUE #5239 - useragent package removed

---

backend/src/v5/models/modelSettings.js
backend/tests/v5/unit/models/modelSettings.test.js

This fixes #5289
- add default value for permissions for situatiosn when model does not have specific permissions.
- added test case in unit test
situation described in the issue should no longer happen

Issue 5289 - fix error 500 on getMembersWithPermissions/getJobsWithPermissions route

---

backend/src/v5/models/notifications.js
backend/tests/v5/unit/models/notifications.test.js

This fixes #5313
Sometimes during E2E test it's failing, with `MongoError: ns not found internal.notifications`
It's difficult to know where this comes from, my best guess is during initialisation of the function when we try to create an index on that collection.
So this issue puts a try/catch around it so it doesn't crash the server, but this may need further observation to see if it no passes now...
- e2e tests should no longer fail

ISSUE #5313 do not bring down the server if we failed to create index.

---

frontend/src/v5/ui/routes/dashboard/projects/containers/uploadContainerRevisionForm/uploadContainerRevisionForm.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/uploadContainerRevisionForm/uploadList/uploadListItem/uploadListItem.component.tsx
frontend/src/v5/validation/containerAndFederationSchemes/validators.ts

This fixes #5331
This bug was happening because the validation for existing tags was completely wrong. 
We were passing an array of revision tags to the validation context which was shared across all upload items, so it wasn't necessarily testing the tags within each selected container.
I have fixed this by selecting the revisions within the actual revisionTag validator
- Open the upload modal. Try to upload a file to a container with a revision tag that already exists on the container
- Try to upload directly to a container using a file with the same name as an existing revision in order to trigger the error
- Try adding multiple files with different destination containers. You should be able to have the same revision tag set for both and the errors should be independent (i.e. if …

ISSUE #5331 - Upload Container modal no longer warns if revision tag is already in use

---

frontend/src/v5/helpers/intl.helper.ts
frontend/src/v5/store/drawings/revisions/drawingRevisions.types.ts
frontend/src/v5/ui/components/shared/uploadFiles/uploadList/uploadListItem/uploadListItemTitle/uploadListItemTitle.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/containers/uploadContainerRevisionForm/uploadList/uploadListItem/uploadListItem.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/drawings/uploadDrawingRevisionForm/uploadList/uploadList.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/drawings/uploadDrawingRevisionForm/uploadList/uploadListItem/uploadListItem.component.tsx
frontend/src/v5/validation/containerAndFederationSchemes/containerSchemes.ts
frontend/src/v5/validation/drawingSchemes/drawingSchemes.ts

This fixes #5327 
- Changed how files are being validated when uploading a revision or a drawing
- Drag and dropping a small file in drawings or revisions uploads will not trigger a "max file size" error 
- Uploading a small file  by clicking browse in drawings or revisions uploads will not trigger a "max file size" error 
- Drag and dropping a large file in drawings or revisions uploads will trigger a "max file size" error 
- Uploading a large file  by clicking browse in drawings or revisions uploads will trigger a "max file size" error 
- Uploading a multipage pdf to drawings will show the "multipage pdf" warning

Issue 5327 - Fixed warnings when drag and dropping file not showing

---

backend/src/scripts/utility/teamspaces/sendDailyDigest.js
frontend/src/v5/ui/routes/viewer/handleTicketsCardSearchParams/handleTicketsCardSearchParams.component.tsx

This fixes #5343 
- renamed query param for filtering tickets
- set query to 'ticketCompleted' to true  and the list of tickets will show completed tickets

Issue 5343 - Renamed query param completed to ticketCompleted 

---

backend/src/v5/schemas/tickets/index.js
backend/tests/v5/unit/schemas/tickets/index.test.js

This fixes #5350
updates to `MANY_OF` ticket property validation:
- If the value is an empty array:
- On new ticket, strip the value
- On update ticket, set it to null (to remove the entry on the db)
The scenario described on the issue should no longer result in a `[]` inside the db

ISSUE #5350 ManyOf property: avoid storing empty array (`[]`) inside the database

---

backend/src/v4/routes/meta.js

This fixes #5463
Remove caching policy from metadata endpoints
Metadata should no longer be cached

ISSUE #5463 remove caching from metadata apis

---

frontend/src/v5/ui/routes/viewer/tickets/ticketDetailsCard/ticketsDetailsCard.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/coordsProperty/coordsProperty.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx

This fixes #5486
The order of ticket properties was affecting the conditional colour of pins.
Using `useWatch` was not enough as that relied on the "registered" fields. Calling "useForm.reset" was unregistering and reregistering the fields, and useWatch was not catching the value upon registration
Create a template that includes pins with conditional (configurable) colour and make sure to have some of them rendered before the conditional property, and some after. A valid template, for instance, could include the following:
- default pin (which colour depends on property "Pin condition")
- "Pin condition" property (which is part of the properties module)
- another conditional pin (defined after "Pin Condition")
<details>
<summary>(If you already have it, you may use the template "Pins With …

ISSUE #5486 - Incorrect pin colour until you click into the new ticket

---

frontend/src/v5/store/tickets/card/ticketsCard.sagas.ts

This fixes #5494
- Added default image as part of the properties needed in the first tickets fetch
- Create a ticket with detault image and add a image. go back to the list. refresh. the image should be there in the thumbnail in the list.

ISSUE #5494 - Added default image as part of the tickets fetch

---

frontend/src/v4/routes/viewer3D/viewer3D.component.tsx
frontend/src/v5/helpers/functions.helpers.ts
frontend/src/v5/store/containers/containers.sagas.ts
frontend/src/v5/store/drawings/drawings.sagas.ts
frontend/src/v5/store/tickets/card/ticketsCard.redux.ts
frontend/src/v5/ui/routes/viewer/defaultTicketFiltersSetter/defaultTicketFiltersSetter.component.tsx
frontend/src/v5/ui/routes/viewer/ticketFiltersSetter/ticketFiltersSetter.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketItem/ticketItem.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsListCard.component.tsx
frontend/src/v5/ui/routes/viewer/viewer.tsx

This fixes #5490 
- When the model is loading the ticket cards is not opened necessary opened. The fetch of filtered tickets was triggerered in that component , so that was moved to a component that is rendered in the viewer (`DefaultTicketFiltersSetter`)
- `DefaultTicketFiltersSetter` got renamed to `TicketFiltersSetter`
- `TicketFiltersSetter` now sets the filter for ticket codes based on url 
- Enter a model with pins from tickets, without opening the pins card the pins should be shown
- The pins should be from the tickets that matches de default criteria (no closed pins, etc)
- Email url should work;  the param for url emails is `?ticketSearch={ticketType}:{ticketNumber},{ticketType}:{ticketNumber},...` for example `/v5/viewer/teamSpace1/7b11d960-9b36-11ed-b559-0768f95e09ad/904de26e-fe …

ISSUE #5490 - Moved filters fetch to filters setter so that the tickets are available  on model load

---

frontend/src/v5/services/api/sso.ts
frontend/src/v5/services/sso.hooks.ts
frontend/src/v5/store/auth/auth.sagas.ts
frontend/src/v5/ui/routes/authPage/authPage.component.tsx
frontend/src/v5/ui/routes/authPage/authPage.styles.ts
frontend/src/v5/validation/userSchemes/loginSchemes.ts
frontend/src/v5/validation/userSchemes/validators.ts

This fixes #5496
Before logging in the user is now prompted to insert their email. This is not required, but if the value is incorrect, the button will be disabled

Issue 5496 - Pass email to IDP endpoint

---

backend/src/v5/middleware/auth.js
backend/src/v5/middleware/sessions.js
backend/src/v5/utils/sessions.js
backend/tests/v5/e2e/routes/teamspaces/projects/index.test.js
backend/tests/v5/helper/sessionTracker.js
backend/tests/v5/unit/middleware/auth.test.js
backend/tests/v5/unit/middleware/permissions/index.test.js

This fixes #5519
The CSRF cookie will now be extended everytime a validation occurs (i.e. ever authenticated endpoint). This should make the expiration time matches the session cookie.
Also fixed a bug where the isLoggedIn middleware is actually bypassing the ip/referer check.
- if the user refreshes their page after the initial 30mins, they should still be logged in

ISSUE #5519 extend the CSRF cookie upon validation

---

frontend/src/v5/services/sso.hooks.ts
frontend/src/v5/ui/routes/authPage/authPage.component.tsx

This fixes #5518 
- Added a fetching the url and redirecting state
- Added an error info box.
_regarding this, I tried it by hardcoding  an error in the code temporaly and the other one was by stopping the backend. I think in a branch you could turn off the network and click on login_

ISSUE #5518 - Added a loading state while fetching the eggfront link

---

frontend/src/v5/helpers/viewpoint.helpers.ts

This fixes #5353
Groups with full opacity (1), don't specify it. As the groups overrides are applied in order, the opacity from a fully visible group
was "undefined", hence, not applied.

ISSUE 5353 - Objects display mixed properties from ticket groups (opacity from one, colour from a different one)

---

backend/src/v4/config.js

This fixes #5593
- set basic subscription to have 0 data by default
NOTE: this will require latest of local repo if you're using it.
- When a new teamspace is created, it should contain 0 data subscription (previously 200)

ISSUE #5593 set basic data to 0 by default

---

frontend/src/v5/ui/routes/dashboard/projects/drawings/drawingDialogs/drawingForm.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/drawings/drawingDialogs/drawingForm.styles.ts
frontend/src/v5/ui/routes/dashboard/projects/drawings/uploadDrawingRevisionForm/sidebarForm/sidebarForm.component.tsx
frontend/src/v5/validation/drawingSchemes/drawingSchemes.ts
frontend/src/v5/validation/shared/validators.ts

This fixes #5603
Yup validation now triggers an error if the data type is invalid
TBD

ISSUE #5603 - Error message in Drawing calibration information setting is cryptic

---

backend/VERSION.json

This fixes #5626
- update current version to 5.18.0
- move 5.16.1 to supported versions

ISSUE #5626 update supported plugin versions

---

frontend/src/v5/ui/components/shared/modalsDispatcher/templates/imagesModal/imagesModal.styles.ts

This fixes #5629 
The margin in the image modal left a space to the side which wasn't blocking the click event thus caused the modal to close
I have replaced this margin with padding instead

ISSUE #5629 - fix clicking edge of image modal is causing it to close

---

frontend/src/v5/ui/routes/dashboard/projects/tickets/selectMenus/containersAndFederationsFormSelect.component.tsx
frontend/src/v5/ui/routes/dashboard/projects/tickets/selectMenus/templateFormSelect.component.tsx

This fixes #5675
For both the container/federation select and the template select if only one option exists this value is automatically set

ISSUE #5675 - Tabular View: Preset model/template if only one option exists
