3drepo/3drepo.io

frontend/components/issues/js/issue.component.js
Solves this: https://github.com/3drepo/3drepo.io/issues/750#issuecomment-367032247
=> ISSUE #754 - fix selected pruneNodes for multi-mesh objects

scripts/db_migrations/v2.10/invoiceMigration.js
a migration script to change the item names of the invoices
@Charence nothing much to it... if you want to take a look
=> ISSUE #844 invoice migration script

backend/models/invoice.js, backend/routes/invoice.js, pug/invoice.pug
1. Show country on invoice;
2. Remove invoice PDF from DB.
=> Issue 860 - Fix invoice template to show country and don't cache on DB

frontend/components/issues/js/issues.service.ts
1. Restore code for hiding closed issues.
2. Fix convertActionValueToText
=> Issue 866 - Fix issue status change display and status notifications

frontend/components/revisions/pug/revisions-dialog.pug
Add model name in revisions dialog.
=> ISSUE #871 - Add model name in revisions dialog.

frontend/components/groups/js/groups.component.ts, frontend/components/issues/js/issues.service.ts, frontend/components/tree/js/tree.component.ts, frontend/components/tree/js/tree.service.ts
This will allow people to click on issues and have the tree panel respond as would be expected; expanding all nodes and scrolling to/selecting the correct nodes
=> ISSUE #873 - fix expandToSelection

frontend/components/account/js/account-profile.component.ts, frontend/components/account/pug/account-profile.pug
Fix the issue with it saying incorrect user name and password when old password is wrong
Nicer error messages for trying to save password which is too short
=> Issue 838 - Better handling of incorrect profile passwords

backend/models/user.js, frontend/components/sign-up/js/sign-up.component.ts, frontend/components/sign-up/pug/sign-up.pug
Also makes password label consistent with other required inputs
=> Issue #806 - Fix error always being 'Email required' at signup

frontend/globals/unity-util.ts
Also makes it cleaner / more extensible in future by moving check to a function
=> ISSUE #852 - Add Invalid typed array length as unity error

frontend/components/issues/js/issues.component.ts
Use bind to preserve scope. This is probably the cause of any current issue / chat server errors.
=> ISSUE #868 - Bind issue functions to the issues component scope

frontend/components/account/js/account-billing.component.ts, frontend/components/account/pug/account-billing.pug
Catch request failures (log them) and also show an error message for users
=> ISSUE #857 - Better handling of failing API calls on Billing page

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
@Charence @JamesMilnerUK  see what you think.
Make sure you read the raw .md not the generated html or it won't make much sense (as most of it is in the comments!)
=> Issue 865 - Pull request template and issue template

scripts/db_migrations/v2.10/groupSchemaChange.js, scripts/db_migrations/v2.10/undoGroupSchemaChange.js
Where it doesn't detect already migrated groups properly
Also added a script to undo the schema change...
=> ISSUE #916 fix bug on schema change script

backend/models/helper/model.js
This fixes #930
Updated the sample model IDs to the latest ones
new users will now have the new version of the sample models.
This requires the bouncer to have the latest dumps.
=> ISSUE #930 update sample project model IDs

frontend/components/panel/pug/panel-card-option-menu.pug
This fixes #929 
Remove tick from menu options that specify noToggle
Open Issues option menu
=> ISSUE #929 - Remove tick from menu options that specify noToggle

frontend/components/issues/js/issues.service.ts
This fixes #1001
The bug happened because jobsDeferred promise is no longer used but it is still being referenced by getJobColor.
Also removed some redundant variables and curious if conditions.
Job color strip should now change colour when you change job assignment
=> ISSUE #1001 fix job colour not updating

backend/models/group.js, backend/models/issue.js, backend/routes/issue.js, frontend/components/compare/js/compare.component.ts, frontend/components/compare/js/compare.service.ts, frontend/components/compare/pug/compare.pug, frontend/components/groups/js/groups.component.ts, frontend/components/groups/pug/groups.pug
This fixes #1011 
This PR addresses the bugs identified in #1011 
All bugs in that issue should now pass (baring the sample project related stuff)
=> Issue 1011 - 2.11.4 bug fixes

frontend/components/home/js/auth.service.ts
This fixes #1013
- Consistently display login error messages
- Login with incorrect credentials
=> ISSUE #1013 - Login page does not flag 1st error

backend/models/helper/model.js
This fixes #1017 
This is part of https://github.com/3drepo/3drepobouncer/issues/253
Importing sample project should now show you groups correctly
=> ISSUE #1017 Fix sample project

frontend/components/compare/js/compare.service.ts
This fixes #1020
Fixes the bug with compare tool in 2.11.5
see #1020
=> Issue 1020 - 2.11.5 bug fix

frontend/components/panel/js/panel.component.ts, frontend/components/panel/js/panel.service.ts, frontend/components/panel/pug/panel.pug, frontend/components/right-panel/pug/right-panel.pug
=> ISSUE #1022 - Rename Meta to BIM on UI

frontend/components/viewpoints/js/viewpoints.component.ts, frontend/components/viewpoints/js/viewpoints.service.ts, frontend/components/viewpoints/pug/viewpoints.pug
This fixes #1034 
- Move getThumbnail from component to service for viewpoints
- Create a saved viewpoint
- Load model with saved viewpoints
=> ISSUE #1034 - Move getThumbnail from component to service for viewpoints

frontend/components/groups/js/groups.service.ts, frontend/components/panel/js/panel.component.ts
This fixes #1046 
Add colour override to new groups if everything is also overridden
1. Select colour override all
2. New groups should also be overridden
=> ISSUE #1046 - Add colour override to new group

config/config_sample.js
This fixes #1070 
Removed the following from config sample:
- os
- test_helper_api
- unity settings
=> Issue 1070 - updating config sample 

.gitignore
=> ISSUE #1101 - ignore yarn.lock

config/config_sample.js
=> ISSUE #1072 - HTTPSredirect flag added to config_sample

README.md
This fixes #1107
Update readme:
- Updated some information that was no longer relevant
- Removed some junk
- moved some sections around (e.g. license and contribution should be at the bottom... imo)
Instead of reading the changelist, probably easier to just read this: https://github.com/3drepo/3drepo.io/tree/ISSUE_1107
=> Issue 1107 update readme

backend/db/db.js
This fixes #1125
Add config option to extend timeout
- it should still connect regardless whether you specified it or not
=> Issue 1125 - Add option to extend socket timeout

frontend/components/account/js/account-federations.component.ts, frontend/components/account/js/account-model.component.ts, frontend/components/account/js/account-user-management.component.ts, frontend/components/account/js/account.service.ts, frontend/components/account/pug/federation-dialog.pug, frontend/components/account/pug/model-dialog.pug, frontend/components/home/js/state-manager.config.ts, frontend/components/projects-permissions/js/projects-permissions.component.ts
This fixes #1086 
I started work from #1085 branch. #1085   PR is not merged yet, but I need these changes to develop this feature.
- Added redirection from teamspaces to models/federations permissions
=> Issue 1086 - Redirection from Teamspaces' View

frontend/components/account/css/account.css, frontend/components/account/pug/account-info.pug
This fixes #1087 
The same situation like before. I had to create this branch from #1083  branch. #1083  PR is not merged yet, but I need these changes to continue my work.
- Added max-width to user panel for larger resolutions
=> ISSUE 1087 - User panel

scripts/db_migrations/v2.18/convertUnityAssets.py
This fixes #1142
- UnityAssets.json moved out of mongo gridFS into a bson in `stash.unity3d`
=> Issue 1142 - UnityAssets.json moved out of gridFS

frontend/components/account/pug/account.pug, frontend/components/home/js/home.component.ts
This fixes #1149 
- Added the return url after logged in
=> ISSUE #1149 - When logged off if you are entering a model related url page it will redirect to that page once you've logged in

README.md
This fixes #1073 
- README corrections
=> ISSUE #1073 - fixed typos, added detail re: config for running

backend/routes/issue.js, frontend/components/account/js/account-model.component.ts, frontend/components/account/js/account.component.ts, frontend/components/docs/pug/docs.pug, frontend/components/groups/js/groups.component.ts, frontend/components/groups/pug/groups.pug, frontend/components/home/js/state-manager.config.ts, frontend/components/home/js/state-manager.run.ts, frontend/components/home/js/state-manager.service.ts, frontend/components/home/pug/home.pug, frontend/components/issues/js/issues-list.component.ts, frontend/components/issues/js/issues.service.ts, frontend/components/issues/pug/issue.pug, frontend/components/issues/pug/issues-list.pug, frontend/components/panel/js/panel-card.component.ts, frontend/components/tree/js/tree.service.ts, frontend/components/tree/pug/tree.pug, frontend/components/viewer/js/viewer.service.ts, frontend/css/ui.css
This fixes #1167 
Fixes various bugs detailed within the issue
=> Issue 1167 - 2.17.2 bug fixes

frontend/components/model/js/model.component.ts
This fixes #1162 
- Load model settings and setup panels before loading model viewer
- Load model
=> ISSUE #1162 - Load model settings and setup panels before loading model

frontend/components/panel/js/panel.service.ts, frontend/components/risks/js/risk-item.component.ts, frontend/components/risks/js/risks.service.ts, frontend/components/risks/pug/risk-item.pug
This fixes #1187 
- Check user permissions for risk update on frontend
- New mitigation status icons
- Change mitigation statuses
- Make assoc activity a textarea
- Firefox date picker bug not fixed
See #1187
=> ISSUE 1187 - Bug fixes

frontend/components/sign-up/js/sign-up.component.ts
This fixes #1194
ensure password and email matches before sending
=> ISSUE #1194 2.17.5 bug fix

frontend/components/groups/js/groups.component.ts, frontend/components/groups/js/groups.service.ts
This fixes #1202
Group count should now be correct
=> Issue 1202 groups count fix

frontend/services/api/index.ts
This fixes #1204
- Added missed property in axios config
=> Issue 1204: Missed property in axios config

frontend/components/compare/js/compare.component.ts, frontend/components/compare/pug/compare.pug, frontend/components/panel/js/panel.component.ts, frontend/components/panel/js/panel.service.ts, frontend/components/panel/pug/panel-card.pug
=> Issue 1209

backend/models/risk.js
This fixes #1213 
- Allow feds with empty models
- Create and load fed with empty model
=> ISSUE #1213 - Catch errors when loading sub-model risks

backend/models/group.js
This fixes #1227
- added early rejects to avoid unnecessary queries
=> ISSUE #1227 early reject to avoid extra queries

backend/mailer/mailer.js, backend/mailer/templates/uponVerified.js, backend/models/user.js
This fixes #1238
Generate a welcome email with instructions for users
- Upon verify, an automated email message should be sent to the user
- It should say "Hello <firstname>", with the first name formatted to be standard pronoun format (i.e. first letter in caps for each word)
=> Issue 1238 - Generate a welcome email

backend/models/issue.js
=> ISSUE #1257 - Fix midddlewares being an empty object in model/issue.js

frontend/package.json, frontend/routes/app/app.component.tsx, frontend/routes/components/previewListItem/previewListItem.component.tsx, frontend/routes/components/previewListItem/previewListItem.styles.ts, frontend/styles/colors.ts
List item component for Issues/SafetiBase panel in the viewer (UI)
=> Issue 1264: Migration - preview list item

backend/mailer/templates/importError.js, backend/models/helper/model.js, backend/services/queue.js
This fixes #1308
When an import fails it will now send the user who uploaded the import to the email notification
=> Issue 1308 send user info to mail alert on failed imports

frontend/routes/components/newCommentForm/newCommentForm.component.tsx, frontend/routes/components/newCommentForm/newCommentForm.styles.ts, frontend/routes/components/previewListItem/previewListItem.component.tsx
New comment component for Issues panel in the viewer (UI)
=> Issue 1271: Migration - new comment form

frontend/components/home/css/home.css, frontend/components/home/pug/home.pug
Fix sign-up container height bug [issue](https://github.com/3drepo/3drepo.io/issues/1317)
=> Issue 1317 - Sign up form doesn't scale

backend/models/issue.js, backend/models/modelSetting.js, backend/routes/issue.js, frontend/main.ts
This fixes #1314 
- Support for clipping planes in BCF export
- Improve BCF filenames
- Create issue with clipping planes and export (try to import back into 3D Repo or other software)
=> ISSUE 1314 - Clipping planes support in BCF export

backend/package.json
This fixes #1300 
Update lodash to get rid of the security alert
=> Issue 1300 - Lodash update

frontend/routes/components/notifications/components/notificationItem/notificationItem.component.tsx
=> ISSUE #1332 - Swaped the hover messages in notifications items in 'mark as read' to 'mark as unread'

backend/response_codes.js, frontend/modules/dialog/dialog.redux.ts
This fixes #1327
- Display the right error message for unverified user:
- Also fixes error dialogs which was errored out previously.
=> ISSUE #1327 fix verification error message

frontend/modules/userManagement/userManagement.redux.ts, frontend/modules/userManagement/userManagement.sagas.ts, frontend/modules/userManagement/userManagement.selectors.ts, frontend/routes/users/users.component.tsx, frontend/routes/users/users.container.ts
=> ISSUE #1330 - Users limit

frontend/routes/teamspaces/components/modelItem/modelItem.component.tsx, frontend/routes/teamspaces/components/revisionsDialog/revisionsDialog.component.tsx
=> Issue 1337 - use 24 hr clock formatting

frontend/routes/angularBindings.ts
**Description**
Removed duplicated Password Change component
=> ISSUE #1354 - Password Change page issue

backend/routes/accountPermission.js, backend/routes/auth.js, backend/routes/group.js, backend/routes/history.js, backend/routes/invoice.js, backend/routes/issue.js, backend/routes/issueAnalytic.js, backend/routes/job.js, backend/routes/maps.js, backend/routes/meta.js, backend/routes/model.js, backend/routes/notification.js, backend/routes/payment.js, backend/routes/permissionTemplate.js, backend/routes/project.js, backend/routes/risk.js, backend/routes/subscriptions.js, backend/routes/teamspace.js, backend/routes/user.js, backend/routes/viewpoint.js
This fixes #1367 
- Some end points are missing the starting sub-directories (whatever you call them).
- Removed documentation for paypal endpoint - this is not something we want to intentionally expose to clients
- Remove documentation for maps - this is not something we want to encourage the clients to use on their platform (essentially they'd be abusing our API keys)
No actual code changes.
=> Issue 1367 - API Doc end point fixes

frontend/routes/components/topMenu/components/userMenu/userMenu.component.tsx
This fixes #1371
- Add new icon to menu 
- Change menu title from 'User manual' to Support.
- Change underlying page link to latest support page on 3D Repo website.
to new support page.
New menu 
Old Menu
=> ISSUE #1371 - Change menu icon and title to new Support link.

frontend/components/height-setter/js/height-setter.component.ts, frontend/components/panel/js/panel.component.ts, frontend/components/panel/pug/panel.pug
=> Issue 1393: Missing panel's gap

frontend/routes/components/panel/panel.styles.ts
=> Issue 1395: Remove scrollbars from login form

backend/models/job.js, backend/test/integrated/job.js
This fixes #1322
- using the same regex as https://github.com/3drepo/3drepo.io/pull/1400
- see https://github.com/3drepo/3drepo.io/pull/1400
=> Issue 1322 - Add validation on job name

frontend/modules/risks/risks.redux.ts, frontend/modules/risks/risks.sagas.ts, frontend/routes/viewer/components/risks/risks.component.tsx
=> Issue 1406

frontend/routes/teamspaces/components/uploadModelFileDialog/uploadModelFileDialog.component.tsx
=> ISSUE #1405 - Fix the lastes version shown in the upload model form

scripts/db_migrations/v3.4/moveRiskViewpoints.js
This fixes #1413
Added a migration script that will copy the viewpoint to the points array, making it inline with issues
=> ISSUE #1413 add migration script for risk viewpoints

frontend/routes/components/filterPanel/filterPanel.styles.ts
=> ISSUE #1420 - Fixed the filtered items in risks not showing in firefox

backend/config.js, backend/models/paypal.js, frontend/modules/risks/risks.sagas.ts, frontend/modules/risks/risks.selectors.ts, frontend/modules/tree/tree.sagas.ts
=> Issue 1453 - 3.4.0 fixes

backend/config.js, backend/routes/config.js, frontend/components/home/js/analytic.service.ts, frontend/components/home/js/home.component.ts, frontend/components/home/js/state-manager.run.ts, frontend/components/home/js/state-manager.service.ts
=> Issue 1429 - GA cross site linkage

backend/logger.js, backend/response_codes.js
This fixes #1455 
- Shorter timestamp
- Added place to log metadata
It now looks like this:
=> ISSUE #1455 - Better logging

backend/config.js, backend/routes/config.js, frontend/package.json, frontend/routes/app/app.component.tsx, frontend/routes/app/app.container.ts, frontend/routes/components/liveChat/index.ts, frontend/routes/components/liveChat/liveChat.component.tsx, frontend/routes/components/liveChat/liveChat.container.tsx, frontend/services/clientConfig.ts
=> ISSUE #1445 - Added live chat

frontend/routes/viewer/components/panelButton/panelButton.component.tsx
https://github.com/3drepo/3drepo.io/issues/1468
Always pass a boolean value as an active prop in panel button.
=> ISSUE #1468 - Risk/Issue Warning

backend/models/meta.js, frontend/components/model/js/model.component.ts, frontend/modules/model/model.redux.ts, frontend/modules/model/model.sagas.ts, frontend/modules/model/model.selectors.ts, frontend/routes/viewer/components/toolbar/toolbar.component.tsx, frontend/routes/viewer/components/toolbar/toolbar.container.ts
https://github.com/3drepo/3drepo.io/issues/1465
Move fetching meta keys outside fetching settings action.
Also, when metaKeys array is empty, then BIM button is disabled.
=> ISSUE #1465 - Get meta keys issue

frontend/components/revisions/css/revisions.css, frontend/components/revisions/pug/revisions-dialog.pug
- Style revisions dropdown button 
- Fix dialog header issue
=> ISSUE #1473 - Revisions dropdown style

scripts/db_migrations/v3.6/moveModelsToFS.py, scripts/db_migrations/v3.6/removeAllS3Refs.js
This fixes #1459 
- DB migration from GridFS to file system
=> ISSUE 1459 - GridFS DB migration to File System

backend/models/report.js, frontend/routes/components/logList/components/log/log.component.tsx, resources/pug/report.pug
=> ISSUE #1479 - Added screenshots in comments when showing the issues/risks report

frontend/modules/tree/tree.sagas.ts
=> ISSUE #1484 - Fixed clicking on background doesnt deselect components

scripts/db_migrations/v3.6/moveModelsToFS.py
This fixes #1487
- Add an overwrite flag. If there is an existing `fs` reference in the database, it will only overwrite it if this flag is set to true.
@keifgwinn In the past running this script will 100% overwrite any existing entries. If `overwrite` is set to false then it will allow us to rerun this script, skipping any files that are already moved (e.g. if the script died in the middle, or we want to run this while production is running - new models being imported would already have entries)
=> ISSUE #1487 introduce overwrite flag

frontend/routes/viewer/components/reportedItems/reportedItems.component.tsx
=> ISSUE #1472 - No entry -> No entries

backend/models/issue.js, backend/models/risk.js, frontend/components/height-setter/js/height-setter.component.ts, frontend/helpers/searching.ts, frontend/routes/viewer/components/reportedItems/reportedItems.component.tsx
This fixes #1493
Fix bugs found in #1493
=> Issue 1493 3.5.1 bug fixes

backend/models/bcf.js, backend/models/issue.js, backend/models/risk.js, frontend/components/tree/js/tree.service.ts, frontend/helpers/issues.ts, frontend/helpers/permissions.ts, frontend/helpers/risks.ts, frontend/modules/model/permissions.selectors.ts, frontend/routes/components/dateField/dateField.component.tsx, frontend/routes/components/topMenu/topMenu.component.tsx, frontend/routes/viewer/components/issues/components/issueDetails/issueDetailsForm.component.tsx, frontend/routes/viewer/components/pinButton/pinButton.component.tsx, frontend/routes/viewer/components/pinButton/pinButton.container.ts, frontend/routes/viewer/components/pinButton/pinButton.styles.ts, frontend/routes/viewer/components/previewDetails/previewDetails.component.tsx, frontend/routes/viewer/components/risks/components/riskDetails/riskDetailsForm.component.tsx, frontend/routes/viewer/components/views/components/viewItem/viewItem.component.tsx, frontend/routes/viewer/components/views/views.component.tsx, frontend/routes/viewer/components/views/views.container.ts, frontend/styles/colors.ts
=> Issue 1497 3.5.2 bug fixes

backend/models/notification.js, frontend/components/viewer/js/viewer.component.ts, frontend/components/viewer/js/viewer.service.ts, frontend/constants/issues.ts, frontend/globals/viewer.ts, frontend/helpers/model.ts, frontend/modules/issues/issues.sagas.ts, frontend/modules/model/model.redux.ts, frontend/modules/model/model.selectors.ts, frontend/routes/components/customTable/components/cellSelect/cellSelect.component.tsx, frontend/routes/viewer/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewer/components/issues/components/issueDetails/issueDetails.container.ts, frontend/routes/viewer/components/issues/components/issueDetails/issueDetailsForm.component.tsx, frontend/routes/viewer/components/issues/issues.component.tsx, frontend/routes/viewer/components/issues/issues.container.ts
=> Issue 1501 - 3.6.0 bug fixes

frontend/globals/unity-util.ts, frontend/globals/viewer.ts, frontend/routes/components/linkableField/linkableField.component.tsx, frontend/routes/components/logList/components/log/log.styles.ts, frontend/routes/viewer/components/bim/components/metaRecord/metaRecord.styles.ts
=> Issue 1503 - Fix not working hlinks

backend/routes/issue.js, backend/routes/risk.js, backend/test/integrated/chatServer.js, backend/test/integrated/impliedPermission.js, backend/test/integrated/issue.js, backend/test/integrated/notifications.js, backend/test/integrated/risk.js, frontend/helpers/forms.ts, frontend/helpers/issues.ts, frontend/helpers/risks.ts, frontend/modules/issues/issues.sagas.ts, frontend/modules/risks/risks.sagas.ts, frontend/routes/viewer/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewer/components/issues/components/issueDetails/issueDetailsForm.component.tsx, frontend/routes/viewer/components/risks/components/riskDetails/riskDetails.component.tsx, frontend/routes/viewer/components/risks/components/riskDetails/riskDetailsForm.component.tsx, frontend/services/api/issues.ts, frontend/services/api/risks.ts
=> Issue 1496 - Changed issues/risks to only send the fields that are being updated

frontend/routes/components/liveChat/liveChat.component.tsx
=> ISSUE #1516 - Fixed dialogs not opening when livechat api fails

backend/3drepo.js
=> ISSUE #1520 add umask support

frontend/routes/viewer/components/previewListItem/previewListItem.component.tsx
This fixes #1523 
- Fixes erroneous flagging of due date expiry
- Old issues with unset due date should not be shown as expired
=> ISSUE 1523 - Fix due date expiry check

frontend/modules/issues/issues.sagas.ts, frontend/routes/viewer/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewer/components/pinButton/pinButton.component.tsx, frontend/routes/viewer/components/risks/components/riskDetails/riskDetails.component.tsx
=> ISSUE #1527 - Issue pins now work after saving when creating thw issue

backend/models/fileRef.js
This fixes #1550 
Delete files when removing model
- Check files have been deleted when model is deleted
=> ISSUE 1550 - Delete files when removing model

backend/models/fileRef.js, backend/models/helper/model.js
This fixes #1549
- Added a check to see if the ref has a flag to indicate the resource should not be deleted.
- updated model IDs
- This requires https://github.com/3drepo/3drepobouncer/issues/330
- Importing toy project should wokr. This should show the latest toy project with smart group examples.
=> Issue 1549 - toy project update

backend/models/helper/model.js
This fixes #1518 
- Use synchronous fs deletion methods instead of async ones
- Upload a model -> temp files in sharedData should be deleted
=> ISSUE 1518 - Attempt to resolve deletion errors from sharedData

frontend/components/model/js/model.component.ts, frontend/modules/viewer/viewer.redux.ts, frontend/modules/viewer/viewer.sagas.ts, frontend/services/api/viewer.ts, frontend/services/viewer/viewer.ts
=> ISSUE #1548 - Get heli speed on init

backend/models/helper/model.js, backend/models/notification.js, backend/test/helpers/bouncerHelper.js, backend/test/integrated/notifications.js, frontend/routes/components/notifications/components/notificationItem/notificationItem.component.tsx
=> Issue 1511 - grouping of upload model notifications

backend/middlewares/getPermissionsAdapter.js, backend/response_codes.js, backend/routes/teamspace.js, backend/services/chat.js, backend/test/integrated/federation.js, backend/test/integrated/group.js, backend/test/integrated/model.js
=> ISSUE #1541 - Errors are thrown if the account or the model are not found

frontend/components/model/js/model.component.ts, frontend/modules/compare/compare.sagas.ts, frontend/services/formatting/formatDate.ts
=> Issue 1570 - Bugs in 3.9.0

frontend/routes/components/linkableField/linkableField.component.tsx, frontend/routes/components/textField/textField.component.tsx, frontend/routes/components/textField/textField.styles.ts, frontend/routes/viewer/components/issues/components/issueDetails/issueDetailsForm.component.tsx, frontend/routes/viewer/components/risks/components/riskDetails/riskDetailsForm.component.tsx
=> Issue 1530 - Hyperlinks in editable fields in issues

frontend/routes/components/textField/textField.styles.ts
=>  ISSUE #1580 - Position of edit button

scripts/db_migrations/v3.10/deleteGridFSFiles.py
This fixes #1526 
GridFS deletion script
=> ISSUE 1526 - GridFS deletion script

backend/handler/fs.js, backend/package.json, backend/routes/resources.js, frontend/components/chat/js/chat.channel.ts, frontend/components/viewer/js/viewer.service.ts, frontend/helpers/issues.ts, frontend/modules/issues/issues.redux.ts, frontend/modules/issues/issues.sagas.ts, frontend/routes/components/logList/components/log/log.component.tsx, frontend/routes/viewer/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewer/components/pinButton/pinButton.component.tsx
This fixes #1605
fixes bugs detailed in the issue.
=> Issue 1605 - 3.9.3 bug fixes

frontend/routes/viewer/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewer/components/issues/components/issueDetails/issueDetailsForm.component.tsx
=> ISSUE #1614 - 3.9.4 bug list

backend/3drepo.js, backend/config.js, backend/models/helper/model.js, config/test/config.js
This fixes #1611
- Allow the public protocol to differ from internal (e.g. https on the outside and http on the inside)
- Fixed a minor non fatal bug where we try to delete files without a corID (toy project import)
See #1611 for necessary config updates
=> Issue 1611 - public protocol support

frontend/modules/issues/issues.sagas.ts
=> ISSUE #1617 - Fixed when collaborating in real time other user unable to open resource

frontend/components/viewer/js/viewer.component.ts, frontend/helpers/colorOverrides.ts, frontend/modules/groups/groups.redux.ts, frontend/modules/groups/groups.sagas.ts, frontend/modules/groups/groups.selectors.ts, frontend/routes/viewer/components/groups/groups.component.tsx, frontend/routes/viewer/components/groups/groups.container.ts
=> Issue 1606 - Fixes the override colours in groups

backend/middlewares/chat.js, backend/models/comment.js, backend/models/issue.js, backend/models/viewpoint.js, backend/routes/issue.js, backend/routes/risk.js, frontend/modules/risks/risks.sagas.ts, frontend/services/api/issues.ts, frontend/services/api/risks.ts
=> Issue 1499 - Risks comments endpoint

frontend/routes/teamspaces/components/revisionsDialog/revisionsDialog.component.tsx, frontend/routes/teamspaces/components/revisionsDialog/revisionsDialog.container.ts, frontend/routes/teamspaces/components/revisionsDialog/revisionsDialog.styles.ts
=> ISSUE #1634 - Added a loading state to revision list

frontend/routes/components/selectField/selectField.component.tsx, frontend/routes/viewer/components/compare/components/compareDiffItem/compareDiffItem.component.tsx, frontend/routes/viewer/components/compare/components/compareDiffItem/compareDiffItem.styles.ts, frontend/routes/viewer/components/compare/components/revisionsSelect/revisionsSelect.component.tsx, frontend/routes/viewer/components/compare/components/revisionsSelect/revisionsSelect.styles.ts
=> ISSUE #1618 - Fixed the compare diff revisions styles

frontend/modules/reducers.ts, frontend/modules/sagas.ts, frontend/modules/starred/index.ts, frontend/modules/starred/starred.contants.ts, frontend/modules/starred/starred.redux.ts, frontend/modules/starred/starred.sagas.ts, frontend/modules/starred/starred.selectors.ts, frontend/modules/teamspaces/teamspaces.redux.ts, frontend/modules/teamspaces/teamspaces.selectors.ts, frontend/modules/viewerGui/viewerGui.sagas.ts, frontend/routes/components/starIcon/starIcon.component.tsx, frontend/routes/components/starIcon/starIcon.styles.ts, frontend/routes/teamspaces/components/modelGridItem/modelGridItem.component.tsx, frontend/routes/teamspaces/components/modelGridItem/modelGridItem.container.ts, frontend/routes/teamspaces/components/modelGridItem/modelGridItem.container.tsx, frontend/routes/teamspaces/components/modelGridItem/modelGridItem.styles.ts, frontend/routes/teamspaces/teamspaces.component.tsx, frontend/routes/teamspaces/teamspaces.container.ts, frontend/routes/teamspaces/teamspaces.styles.ts, frontend/routes/viewerGui/components/bim/bim.container.ts, frontend/routes/viewerGui/components/bim/components/metaRecord/metaRecord.component.tsx, frontend/services/api/models.ts
=> Issue 1619 Teamspaces: Starred items

frontend/globals/unity-util.ts, frontend/package.json, frontend/services/viewer/pin.ts
This fixes #1643
Update unity doc to conform with typedocs formatting.
- Running `yarn docs` on the front end folder should now produce decent looking unity docs.
- Should be no functional change to the app.
=> Issue 1643 - Update unity docs

backend/routes/history.js
=> ISSUE 1624 - Remove update revision tag

.gitignore, backend/middlewares/keyAuthentication.js, backend/response_codes.js, backend/utils.js
This fixes #1560
- Should show the full endpoint instead of just the part that express cares about.
- Stream response should now show full end point as well.
=> Issue 1560 - Logging improvement

backend/mailer/templates/forgotPassword.js, backend/mailer/templates/uponVerified.js, backend/mailer/templates/verifyUser.js, resources/pug/invoice.pug, resources/pug/refund.pug
This fixes #1655 
Change address to the latest 3D Repo address.
=> ISSUE #1655 Update addresses

frontend/modules/risks/risks.sagas.ts, frontend/routes/viewer/components/risks/components/riskDetails/riskDetailsForm.component.tsx
=> ISSUE 1648 - Updateable risk likehood/consequence

frontend/helpers/groups.ts, frontend/helpers/issues.ts, frontend/helpers/risks.ts, frontend/routes/viewer/components/groups/components/groupDetails/groupDetails.component.tsx, frontend/routes/viewer/components/groups/components/groupDetails/groupDetails.styles.ts, frontend/routes/viewer/components/groups/components/groupDetails/groupDetailsForm.component.tsx, frontend/routes/viewer/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewer/components/issues/components/issueDetails/issueDetailsForm.component.tsx, frontend/routes/viewer/components/previewDetails/previewDetails.component.tsx, frontend/routes/viewer/components/previewListItem/previewListItem.component.tsx
https://github.com/3drepo/3drepo.io/issues/1604
Also fixed _Number of objects_ and _Last updated_ in group details
=> Issue 1604 - Details properties names

frontend/modules/auth/auth.sagas.ts
=> ISSUE #1666 - Remove session expired dialog

.travis.yml, frontend/internals/webpack/tools/loaders.js, frontend/internals/webpack/webpack.common.config.js, frontend/package.json
=> Issue 1665: New build command

frontend/components/model/js/model.component.ts
=> ISSUE #1663 - Model loading blocks viewer loading

frontend/routes/teamspaces/components/federationDialog/components/subModelsTable/subModelsTable.component.tsx, frontend/routes/teamspaces/components/federationDialog/components/subModelsTable/subModelsTable.styles.ts, frontend/routes/teamspaces/teamspaces.component.tsx
=> Issue 1662 - Federation dialog misalignment

frontend/modules/groups/groups.sagas.ts, frontend/modules/issues/issues.sagas.ts, frontend/routes/viewer/components/groups/components/groupDetails/groupDetails.component.tsx, frontend/routes/viewer/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewer/components/previewDetails/previewDetails.component.tsx, frontend/routes/viewer/components/risks/components/riskDetails/riskDetails.component.tsx
=> ISSUE #1540 - Clear name placeholder in preview details on focus

frontend/modules/groups/groups.sagas.ts, frontend/modules/groups/groups.selectors.ts
=> ISSUE #1671 - Fixed when editing a group the selection of the group disappeared

frontend/helpers/groups.ts, frontend/modules/groups/groups.sagas.ts, frontend/routes/components/textField/textField.component.tsx, frontend/routes/viewer/components/groups/components/groupDetails/groupDetails.component.tsx, frontend/routes/viewer/components/groups/components/groupDetails/groupDetails.styles.ts, frontend/routes/viewer/components/groups/components/groupDetails/groupDetailsForm.component.tsx
=> Issue 1675 - fixed group saving problems

frontend/helpers/issues.ts
=> ISSUE 1678 - Fix pin colours

backend/VERSION.json
=> ISSUE #1684 replace 3.10 support with 3.12

frontend/modules/auth/auth.sagas.ts, frontend/modules/currentUser/currentUser.sagas.ts, frontend/modules/viewer/viewer.redux.ts, frontend/modules/viewer/viewer.sagas.ts, frontend/routes/components/topMenu/components/userMenu/userMenu.component.tsx, frontend/routes/components/topMenu/components/visualSettingsDialog/visualSettingsDialog.component.tsx, frontend/routes/components/topMenu/components/visualSettingsDialog/visualSettingsDialog.styles.ts
This fixes #1682
fixes bugs listed in this issue.
all bugs should be fixed.
=> Issue 1682 3.11.3 bug fixes

frontend/helpers/issues.ts
=> ISSUE 1690 - Revert colour logic for getStatusIcon in issue

frontend/modules/model/model.selectors.ts, frontend/modules/viewerGui/viewerGui.redux.ts, frontend/modules/viewerGui/viewerGui.sagas.ts, frontend/routes/components/dialogContainer/components/revisionsDialog/revisionsDialog.component.tsx, frontend/routes/viewerGui/components/revisionsSwitch/revisionsSwitch.component.tsx, frontend/routes/viewerGui/components/revisionsSwitch/revisionsSwitch.container.ts, frontend/routes/viewerGui/viewerGui.component.tsx
=> ISSUE #1673 - Using revision instead of master/head in requests

frontend/helpers/issues.ts
=> ISSUE 1687 - Fix issue pin colours

backend/models/helper/model.js, backend/models/modelSetting.js, backend/models/notification.js, backend/routes/model.js, backend/test/helpers/bouncerHelper.js, backend/test/helpers/models.js, backend/test/integrated/notifications.js, frontend/modules/teamspaces/teamspaces.sagas.ts, frontend/routes/components/notifications/components/notificationItem/notificationItem.component.tsx, frontend/routes/teamspaces/components/modelItem/modelItem.component.tsx
=> ISSUE #1200 - Federations are now hooked up to chat events

backend/models/helper/model.js
=> ISSUE #1728 - Fixed getsubmodels name for compare card

frontend/modules/groups/groups.sagas.ts
=> Issue 1716 - Smart group UI problems

frontend/routes/modelsPermissions/modelsPermissions.component.tsx
=> ISSUE #1733 - Fixed permissions not visibles with new simplebar

frontend/routes/app/app.component.tsx, frontend/routes/viewerCanvas/viewerCanvas.component.tsx, frontend/routes/viewerCanvas/viewerCanvas.styles.ts
=> ISSUE #1726 - Fixed the model showing on background in dashboard

backend/models/user.js, backend/routes/auth.js, backend/test/integrated/login.js, frontend/modules/auth/auth.sagas.ts, frontend/routes/login/login.component.tsx
=> ISSUE #1718 - Added support to login using email

frontend/modules/dialog/dialog.redux.ts, frontend/routes/app/app.component.tsx, frontend/routes/app/app.container.ts, frontend/routes/components/dialogContainer/components/newUpdateDialog/newUpdateDialog.component.tsx, frontend/routes/components/dialogContainer/components/newUpdateDialog/newUpdateDialog.styles.ts, frontend/serviceWorkerExtras.js
=> Issue 1720 - Show update dialog

frontend/routes/components/avatar/avatar.component.tsx, frontend/routes/components/avatar/avatar.styles.ts
This fixes #1740
Test with account without avatar and also account with avatar
=> ISSUE 1740 - Reinstate person icon for avatar placeholder

frontend/routes/components/staticPageRoute/staticPageRoute.component.tsx, frontend/routes/components/staticPageRoute/staticPageRoute.styles.ts
=> ISSUE #1736 - Added static nav dropdown in static pages header

frontend/routes/projects/projects.styles.ts
=> ISSUE #1743 - Fixed users list cut off in user management

frontend/routes/subscription/components/subscriptionForm.component.tsx, frontend/routes/subscription/subscription.styles.ts
=> ISSUE #1474 - added a warning sign in billing regarding paypal

frontend/routes/teamspaces/teamspaces.contants.ts
This fixes #1757
- Add extra default model types to the front end
=> ISSUE #1757 add extra model types

frontend/globals/unity-util-external.ts, frontend/globals/unity-util.ts, frontend/globals/viewer.ts, frontend/internals/webpack/webpack.prod.config.js, frontend/modules/tree/tree.redux.ts, frontend/modules/tree/tree.sagas.ts, frontend/modules/tree/tree.selectors.ts, frontend/modules/tree/treeProcessing/transforming.ts, frontend/modules/tree/treeProcessing/treeProcessing.ts, frontend/modules/viewerGui/viewerGui.sagas.ts, frontend/modules/viewerGui/viewerGui.selectors.ts, frontend/routes/viewerGui/components/viewerLoader/viewerLoader.component.tsx
=> ISSUE 1721: Fix viewer & model loader

frontend/modules/groups/groups.sagas.ts
=> ISSUE #1761 -  3.15.1 bug fixes

backend/models/bcf.js, backend/models/issue.js, backend/models/ticket.js, backend/routes/issue.js, frontend/modules/issues/issues.sagas.ts, frontend/package.json, frontend/routes/viewerGui/components/issues/issues.component.tsx, frontend/services/export.ts
This fixes #1764 
- fix front end where it errors when you try to do a BCF Import
- fix backend where it returns 500 internal error on BCF Export if you have an issue without a viewpoint
- fix backend where it returns 500 internal error on BCF Import if you have an issue without a screenshot
- option to use numbers instead of ids as query string to allow a lot of issues to be queried together.
=> Issue 1764 - BCF Fixes

backend/mailer/templates/forgotPassword.js, frontend/modules/bim/bim.sagas.ts, frontend/modules/chat/channel.ts, frontend/modules/model/model.sagas.ts, frontend/modules/teamspaces/teamspaces.redux.ts, frontend/routes/teamspaces/components/modelGridItem/modelGridItem.component.tsx, frontend/routes/viewerGui/components/tree/components/treeNode/treeNode.component.tsx, frontend/routes/viewerGui/components/tree/tree.component.tsx
This fixes #1767
see issue.
2 of the bugs are deemed non urgent and been pushed to their own issues
=> Issue 1767 - 3.15.2 bug fixes

backend/VERSION.json
=> ISSUE #1773 add 4.0.0 as a supported version

backend/models/fileRef.js, backend/models/group.js, frontend/modules/tree/treeProcessing/processing.ts, frontend/modules/tree/treeProcessing/transforming.ts, frontend/modules/tree/treeProcessing/treeProcessing.constants.ts, frontend/modules/tree/treeProcessing/treeProcessing.ts, frontend/modules/viewerGui/viewerGui.sagas.ts, frontend/routes/viewerGui/components/tree/components/treeNode/treeNode.component.tsx
This fixes #1777
Fix issues listed in #1777
=> Issue 1777 - 4.0.0 bug fixes

frontend/modules/teamspaces/teamspaces.selectors.ts
This fixes #1771
- Fix filtering by model types & codes
=> ISSUE #1771 - Fix filtering by model types & codes

frontend/modules/risks/risks.sagas.ts
=> ISSUE #1784 - Fixed error when creating a risk

frontend/helpers/issues.ts, frontend/modules/groups/groups.sagas.ts, frontend/modules/model/model.sagas.ts, frontend/modules/teamspaces/teamspaces.redux.ts, frontend/modules/teamspaces/teamspaces.sagas.ts, frontend/modules/viewerGui/viewerGui.sagas.ts, frontend/routes/modelSettings/modelSettings.component.tsx, frontend/routes/modelSettings/modelSettings.styles.ts, frontend/routes/teamspaces/components/projectDialog/projectDialog.component.tsx, frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetailsForm.component.tsx, frontend/routes/viewerGui/components/previewListItem/previewListItem.component.tsx, frontend/routes/viewerGui/components/previewListItem/previewListItem.styles.ts, frontend/routes/viewerGui/components/views/components/viewItem/viewItem.component.tsx, frontend/routes/viewerGui/viewerGui.component.tsx, frontend/services/validation/validation.ts
=> Issue 1779: Minor UI Issues

frontend/routes/components/filterPanel/filterPanel.component.tsx
=> ISSUE #1789 - Handle unsupported query formats

backend/models/group.js
This fixes #1793 
Problem affected federations
=> ISSUE 1793 - IFC GUIDs bug for smart groups in federations

backend/models/project.js
=> ISSUE #1805 - Added the property '_id' in  models/project.js 

backend/models/user.js, backend/routes/auth.js
=> ISSUE 1804 - Do not require admin for getting avatar

frontend/helpers/searching.ts, frontend/routes/viewerGui/components/reportedItems/reportedItems.component.tsx
=> Issue 1798 - Issues/risks bugs

backend/models/bcf.js, backend/models/fileRef.js, backend/models/issue.js, backend/models/risk.js, backend/models/ticket.js, backend/routes/issue.js, backend/routes/risk.js, backend/test/integrated/issue.js, backend/test/integrated/risk.js, frontend/modules/issues/issues.sagas.ts, frontend/modules/risks/risks.redux.ts, frontend/modules/risks/risks.sagas.ts, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.container.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetailsForm.component.tsx, frontend/services/api/issues.ts, frontend/services/api/risks.ts
=> Issue 1788 - Attach resources to risk and refactor of risk, issues to use tickets

frontend/modules/model/model.selectors.ts
=> ISSUE #1815 - Fixed go back from a model and getting a blank page

frontend/routes/components/panel/panel.styles.ts, frontend/routes/dashboard/dashboard.styles.ts
=> ISSUE #1796 - Fixed margin in profile page

frontend/routes/viewerGui/components/issues/issues.component.tsx, frontend/routes/viewerGui/components/risks/risks.component.tsx
=> Issue 1803 - Fixed back button on new issues and risks

frontend/modules/currentUser/currentUser.selectors.ts, frontend/modules/model/model.redux.ts, frontend/modules/model/model.selectors.ts, frontend/routes/app/app.styles.ts, frontend/routes/board/board.component.tsx, frontend/routes/board/board.styles.ts, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.container.ts, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.styles.ts, frontend/routes/viewerGui/components/previewDetails/previewDetails.component.tsx, frontend/routes/viewerGui/components/previewDetails/previewDetails.styles.ts, frontend/routes/viewerGui/components/previewListItem/previewListItem.component.tsx, frontend/routes/viewerGui/components/previewListItem/previewListItem.styles.ts, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.styles.ts
This fixes #1808
- Fix checking user permissions in issue form
- Fix issue with a title that overlaps the information.
- Fix cards jumping around the screen when changing the topic to group them.
- Update popup size for issue details
=> ISSUE #1808 - Issues functionality in Kanban Board & Model Viewer

frontend/modules/tree/treeProcessing/processing.ts, frontend/modules/tree/treeProcessing/transforming.ts
=> Issue 1812 tree bug fixes

backend/models/helper/model.js, backend/response_codes.js, frontend/constants/revisions.ts
=> ISSUE #1810 spm support

.gitignore, scripts/reporting/statsGen/dbStats.js, scripts/reporting/statsGen/genStats.js, scripts/reporting/statsGen/newUsersPerMonth.js, scripts/reporting/statsGen/package.json, scripts/reporting/statsGen/teamspaceActivity.js, scripts/reporting/statsGen/teamspaceQuota.js, scripts/reporting/statsGen/userList.js, scripts/reporting/statsGen/utils.js
=> Issue 1832 - generate stats reports

frontend/constants/issues.ts, frontend/helpers/issues.ts
This fixes #1818
- Low priority is now yellow
- closed issues are now green.
=> ISSUE #1818 change issue colours

frontend/routes/viewerGui/components/risks/risks.component.tsx
=> ISSUE #1843 - Fixed risk going blank when editing a pin

frontend/helpers/issues.ts, frontend/helpers/risks.ts, frontend/modules/canvasHistory/canvasHistory.redux.ts, frontend/routes/components/filterPanel/filterPanel.component.tsx, frontend/routes/viewerGui/components/issues/issues.component.tsx
=> Issue 1853 - 4.1.3 Bug list 2 fixes

frontend/routes/teamspaces/teamspaces.component.tsx
This fixes #1839
- Fix updating of visible items in the models search result
=> ISSUE #1839 Fix updating of visible items in models search result

frontend/modules/issues/issues.sagas.ts
=> ISSUE 1855 Remove unnecessary issue API calls

frontend/modules/teamspaces/teamspaces.redux.ts, frontend/modules/userManagement/userManagement.selectors.ts, frontend/routes/projects/projects.component.tsx, frontend/routes/projects/projectsPermissions/projectsPermissions.component.tsx
This fixes #1856
- Fix updating of state during create project action
=> ISSUE #1856 - Fix updating of state during create project action

frontend/routes/viewerGui/components/compare/components/compareFilters/compareFilters.styles.ts
This fixes #1867
- Fix layout bug in compare panel
=> ISSUE #1867 Fix layout bug in compare panel

frontend/modules/jobs/jobs.redux.ts, frontend/modules/jobs/jobs.sagas.ts, frontend/routes/components/colorPicker/colorPicker.component.tsx, frontend/routes/jobs/jobs.component.tsx, frontend/routes/jobs/jobs.container.ts, frontend/routes/projects/projects.component.tsx, frontend/routes/projects/projects.styles.ts
This fixes #1863
- Fix layout issue on Projects permissions tab
- Fix fetching jobs and colors on Jobs tab
=> ISSUE #1863 Fix layout issue

backend/routes/history.js, backend/routes/risk.js
=> ISSUE 1877 - Update backend docs

frontend/routes/teamspaces/teamspaces.component.tsx
=> ISSUE #1875 - Fixed teamspaces not remembering the state of the component

backend/routes/auth.js
=> ISSUE #1891 - If the user logs in outside the browser it doesnt kickout the logged web user

frontend/modules/chat/subscriptions.ts
=> ISSUE #1884 - Fixed suscriptions in chat

frontend/routes/viewerGui/components/gis/gis.component.tsx, frontend/routes/viewerGui/components/groups/groups.component.tsx, frontend/routes/viewerGui/components/listNavigation/listNavigation.component.tsx, frontend/routes/viewerGui/components/listNavigation/listNavigation.styles.ts, frontend/routes/viewerGui/components/panelBarActions/menuButton/menuButton.component.tsx, frontend/routes/viewerGui/components/panelBarActions/panelBarActions.component.tsx, frontend/routes/viewerGui/components/reportedItems/reportedItems.component.tsx
This fixes #1886 
The following are missing the lock button:
=> ISSUE #1886 - Add lock button to panels subpages

backend/models/ticket.js, backend/models/user.js, backend/test/integrated/issue.js
=> Issue 1883 - minor changes to make plugin work better

frontend/modules/issues/issues.redux.ts, frontend/modules/issues/issues.selectors.ts, frontend/modules/risks/risks.redux.ts, frontend/modules/risks/risks.selectors.ts, frontend/modules/viewerGui/viewerGui.sagas.ts, frontend/routes/viewerCanvas/viewerCanvas.component.tsx
=> ISSUE #1921 - Dev 4.3.4 Bugs

frontend/routes/viewerGui/components/reportedItems/reportedItems.component.tsx
This fixes #1906 
Navigation buttons disappear when penultimate issue closed
=> Issue 1906 - fix navigation buttons on issues/risks

frontend/routes/viewerGui/components/revisionsSwitch/revisionsSwitch.component.tsx, frontend/routes/viewerGui/components/revisionsSwitch/revisionsSwitch.styles.ts
=> ISSUE #1756 - Fix centering issue of revision indicator

frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetailsForm.component.tsx
=> ISSUE #1848 - Remove adjusting date format feature in due date field

backend/VERSION.json
This fixes #1928
bump repo4unity.dll version support
=> ISSUE #1928 unity dll version bump

frontend/modules/issues/issues.sagas.ts, frontend/modules/issues/issues.selectors.ts, frontend/modules/risks/risks.sagas.ts, frontend/modules/risks/risks.selectors.ts
=> ISSUE #1931 - Fixed pin dissapearing

backend/routes/resources.js, backend/test/integrated/resources.js
=> Issue 1936 - Fixes resource available after user logged out

run/3drepo.yml
=> ISSUE #1941 revert yml file to same as prod

frontend/modules/issues/issues.redux.ts, frontend/modules/risks/risks.redux.ts
=> Issue 1935 - Fixed blank page when attaching resource to brand new issue/risk

frontend/routes/board/board.component.tsx, frontend/routes/board/board.styles.ts, frontend/routes/components/textField/textField.component.tsx, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.styles.ts, frontend/routes/viewerGui/components/previewListItem/previewListItem.component.tsx
=> ISSUE #1938 - Kanban Board fixes

backend/models/ticket.js
=> ISSUE #1956 remove due_date if it's null

backend/models/fileRef.js
=> Issue 1960 - remove files in resources and sequences upon model deletion

backend/VERSION.json
=> ISSUE 1950 - VBA version

frontend/modules/viewpoints/viewpoints.sagas.ts
=> ISSUE #1948 - Issue card bugs

frontend/routes/viewerGui/components/issues/issues.component.tsx, frontend/routes/viewerGui/components/issues/issues.container.ts
=> ISSUE #2000 - bugs fixes 4.5.3

scripts/db_migrations/v4.6/changeIssueTypesAndRiskCategoriesDatatype.js
This fixes #2002 
this fixes the migration script, it was filtering out all issues/risks with no comments.
=> ISSUE #2002 fix migration

frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx
=> ISSUE #2005 - Fixed viewpoints not being send when posting comments

frontend/globals/unity-util.ts
=> ISSUE #2007 - Fix mapinitialise not being called in unity

frontend/modules/risks/risks.sagas.ts, frontend/routes/viewerGui/components/previewListItem/previewListItem.component.tsx
=> ISSUE #1980 - Fixed warning message in risks when closed by another user

frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx
=> ISSUE #1982 - Fixed save button being enabled when a new smart groups

frontend/routes/components/screenshotDialog/components/drawingHandler/handleCalloutDrawing/handleCalloutDrawing.component.tsx, frontend/routes/components/screenshotDialog/components/drawingHandler/handleLineDrawing/handleLineDrawing.component.tsx, frontend/routes/components/screenshotDialog/components/drawingHandler/handlePolygonDrawing/handlePolygonDrawing.component.tsx, frontend/routes/components/screenshotDialog/components/drawingHandler/handleShapeDrawing/handleShapeDrawing.component.tsx, frontend/routes/components/screenshotDialog/components/erasing/erasing.component.ts, frontend/routes/components/screenshotDialog/components/typingHandler/typingHandler.component.tsx, frontend/routes/components/screenshotDialog/screenshotDialog.component.tsx
=> ISSUE #1952 - Handle both touch and mouse events in markup tool

frontend/routes/components/customTable/components/cellSelect/cellSelect.component.tsx, frontend/routes/components/selectField/selectField.component.tsx, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetailsForm.component.tsx
=> Issue #1977 - Fixed cell select issues

frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.styles.ts
=> Issue #1992  - Line in description field in groups

frontend/routes/components/selectField/selectField.component.tsx
=> ISSUE #2013 - Added support for multilevel items in cell select

frontend/routes/components/selectField/selectField.component.tsx
=> ISSUE #2020 - Fix opening visual settings makes the page to go blank 

backend/models/bcf.js, backend/models/issue.js, backend/models/ticket.js, backend/routes/issue.js
=> ISSUE #2033 - Added Last updated timestamp to issues and risks endpoints

backend/routes/model.js
=> ISSUE #2041 - Updated documentation on create model

backend/routes/issue.js
=> ISSUE #2055 - Fix wrong apiName properties in api documentation

backend/models/viewpoint.js, backend/utils.js
This fixes #2042 
clean is being called, but it's missing all the clean conditions because the 2nd optional parameter was overwritten by the index due to the forEach loop.
listViewpoints should now return views with IDs stringified
=> Issue 2042 fix viewpoints not returning a stringify ID

frontend/routes/viewerGui/components/previewDetails/previewDetails.component.tsx
=> ISSUE #1994 - Do not render toggle container when expanding is disabled

frontend/routes/components/customTable/customTable.styles.ts, frontend/routes/components/modelItem/modelItem.component.tsx, frontend/routes/components/permissionsTable/permissionsTable.component.tsx
=> ISSUE #2011 - Improving styling for displaying model names in invitation user modal

backend/routes/model.js
=> ISSUE #2023 - fixed upload model documentation

backend/models/group.js, backend/models/issue.js, backend/models/ticket.js, backend/routes/group.js, backend/routes/issue.js, backend/routes/risk.js
=> Issue #2057 - Add query parameter for filtering lists

frontend/modules/compare/compare.sagas.ts
=> ISSUE #2031 - Fixed in compare sagas not showing hidden models when testing for clashes

frontend/routes/viewerGui/components/measurements/components/measuringType/measuringType.component.tsx, frontend/routes/viewerGui/components/measurements/components/measuringType/measuringType.container.ts
=> ISSUE #2025 - Disable clipping tool if measurement is activated

backend/handler/fs.js, backend/models/bcf.js, backend/models/ticket.js, frontend/globals/unity-util.ts, frontend/helpers/browser.ts, frontend/modules/board/board.sagas.ts, frontend/modules/board/board.selectors.ts, frontend/modules/teamspaces/teamspaces.redux.ts, frontend/routes/components/selectField/selectField.component.tsx, frontend/routes/components/topMenu/components/visualSettingsDialog/visualSettingsDialog.component.tsx, frontend/routes/teamspaces/components/modelGridItem/modelGridItem.component.tsx
This fixes #2058
Fixes all bugs noted in #2058
=> Issue 2058 - 4.7.1 bug fix

backend/constants.js, backend/models/issue.js, backend/routes/issue.js, backend/test/integrated/issue.js, backend/test/integrated/risk.js
=> ISSUE 2071 - Backend for void status

frontend/modules/issues/issues.sagas.ts, frontend/modules/risks/risks.sagas.ts
=> Issue 2076 - fixed risks and issues events kept susbcribed from previous models

backend/models/ticket.js
This fixes #2085
Fixes problem with setting the camera for toy project existing issues
=> ISSUE #2085 check validity of legacy viewpoint data

scripts/dbMaintenance/repairFileShare.py
This fixes #2064
Remove references which are unrepairable
=> ISSUE #2064 remove unrepairable refs

frontend/routes/components/messagesList/messagesList.component.tsx, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx
=> ISSUE #2088 - Fix grey area not appearing in risks and issues when no comment

backend/models/comment.js
=> ISSUE #2096 - Fixed creation of system comments

frontend/modules/issues/issues.sagas.ts, frontend/modules/risks/risks.sagas.ts, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx
=> Issue #2103 - Fixed posting comments wihout camera position

frontend/modules/groups/groups.redux.ts, frontend/modules/groups/groups.sagas.ts, frontend/modules/groups/groups.selectors.ts, frontend/modules/issues/issues.redux.ts, frontend/modules/issues/issues.sagas.ts, frontend/modules/issues/issues.selectors.ts, frontend/modules/risks/risks.redux.ts, frontend/modules/risks/risks.sagas.ts, frontend/modules/risks/risks.selectors.ts, frontend/routes/components/submitButton/submitButton.component.tsx, frontend/routes/viewerGui/components/commentForm/commentForm.component.tsx, frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx, frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.container.ts, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.container.ts, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.container.tsx, frontend/routes/viewerGui/components/viewerPanel/viewerPanel.styles.ts
This fixes #1953
Complete it for the following actions:
=> ISSUE 1953 - Add pending status for save buttons

frontend/modules/model/model.redux.ts, frontend/modules/model/model.sagas.ts, frontend/routes/components/dialogContainer/components/dialog/dialog.component.tsx, frontend/routes/components/dialogContainer/components/loadingDialog/loadingDialog.component.tsx, frontend/routes/components/loader/loader.component.tsx, frontend/routes/teamspaces/components/uploadModelFileDialog/uploadModelFileDialog.component.tsx, frontend/routes/teamspaces/components/uploadModelFileDialog/uploadModelFileDialog.container.ts, frontend/routes/teamspaces/components/uploadModelFileDialog/uploadModelFileDialog.styles.ts
=> ISSUE #2098 - Add uploading model status in upload model dialog

frontend/modules/risks/risks.sagas.ts
=> ISSUE #2117 - Fix risk data prepare after save

frontend/routes/components/messagesList/components/message/components/footer/footer.component.tsx, frontend/routes/components/messagesList/components/message/components/userMessage/userMessage.component.tsx, frontend/routes/components/messagesList/components/message/message.component.tsx, frontend/routes/components/messagesList/messagesList.component.tsx, frontend/routes/components/messagesList/messagesList.styles.ts, frontend/routes/viewerGui/components/commentForm/commentForm.component.tsx, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.styles.ts, frontend/routes/viewerGui/components/previewDetails/previewDetails.component.tsx, frontend/routes/viewerGui/components/previewDetails/previewDetails.styles.ts, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.styles.ts
=> ISSUE 2107 - Comments Issue

frontend/helpers/model.ts, frontend/routes/modelSettings/modelSettings.component.tsx, frontend/routes/teamspaces/components/modelDialog/modelDialog.component.tsx
=> ISSUE 2028 - Custom error message for model code field

backend/routes/issue.js
This fixes #2142
- Corrected API endpoint information
- Added missing parameters
=> ISSUE #2142 fix screenshot api documentation

frontend/routes/components/filterPanel/filterPanel.component.tsx, frontend/routes/components/filterPanel/filterPanel.styles.ts, frontend/routes/components/fontAwesomeIcon/fontAwesomeIcon.styles.ts, frontend/routes/components/fontAwesomeIcon/index.tsx, frontend/services/fontAwesome.ts
This fixes #2155 
Use filter icon instead
Check search criteria textbox
=> ISSUE 2155 - Use filter icon

frontend/helpers/searching.ts, frontend/modules/issues/issues.selectors.ts, frontend/modules/risks/risks.selectors.ts, frontend/routes/board/board.component.tsx, frontend/routes/viewerGui/components/reportedItems/reportedItems.component.tsx
=> ISSUE #2120 - Add risks/issues number field to query search

backend/routes/issue.js, backend/routes/risk.js, backend/routes/view.js
=> Issue 2163 - Update apidocs for refelcting viewpoints changes

scripts/db_migrations/v4.10/addRiskNumbers.py, scripts/db_migrations/v4.10/cleanIssues.py
This fixes #2178 
Already tested.
=> ISSUE 2178 - hotfix v4.10 DB migration scripts

frontend/helpers/risks.ts, frontend/routes/board/board.component.tsx, frontend/routes/viewerGui/components/previewListItem/previewListItem.component.tsx
=> ISSUE #2186 - Fixed kanban board getting a white screen 

frontend/routes/app/app.component.tsx
=> ISSUE #2202 - Fixed white screen in kanban

frontend/modules/tree/tree.sagas.ts
=> ISSUE #2192 - Fixed meshesToUpdate of undefined error

.azure/Docker/Dockerfile, .azure/Docker/src/init.sh, .azure/build-and-deploy.yaml
This fixes #2210 
Updated init.sh to start using the ./run/run_app script to start  node
test container should start
=> ISSUE #2210 run run_app script to start

frontend/modules/tree/tree.sagas.ts
=> ISSUE #2217 - Changed the logic for waiting to be ready in tree sagas

.azure/build-and-deploy.yaml
=> ISSUE #2222 - DevOps triggers shouldn't include all issues 

frontend/routes/viewerGui/components/commentForm/commentForm.component.tsx
=> ISSUE #2184 - Fix case sensitivity in user search in comments

frontend/helpers/comments.ts, frontend/package.json, frontend/routes/components/messagesList/components/message/components/markdownMessage/markdownMessage.renderers.tsx
=> ISSUE #2197 - Fix clickable URL in comments section

.azure/Docker/Dockerfile, .azure/Docker/src/init.sh, .azure/build-and-deploy.yaml, .azure/build.yaml, .azure/deploy.yaml
This fixes #2227 #2222 #2205 #2106 #2210
=> ISSUE #2227 - merge DevOps to master

frontend/routes/passwordChange/passwordChange.component.tsx, frontend/routes/passwordChange/passwordChange.styles.ts
=> ISSUE #2167 - Add back to login button after password reset

backend/models/user.js
This fixes #2177
- search for known user e-mail address with different casing should work
=> ISSUE 2177 - Case insensitive e-mail search

frontend/helpers/comments.ts, frontend/helpers/issues.ts, frontend/package.json, frontend/routes/viewerGui/components/measurements/components/measureItem/measureItem.component.tsx
=> ISSUE #2175 - Upgrade typescript

frontend/modules/risks/risks.redux.ts
=> ISSUE #2231 - Fix updating of risks comments

frontend/modules/issues/issues.redux.ts, frontend/modules/risks/risks.redux.ts
=> ISSUE #2249 - Fix problem with doubled comments appearing

frontend/helpers/comments.ts, frontend/modules/issues/issues.selectors.ts, frontend/modules/risks/risks.selectors.ts, frontend/routes/components/messagesList/components/message/components/footer/footer.component.tsx, frontend/routes/viewerGui/components/commentForm/commentForm.component.tsx, frontend/routes/viewerGui/components/commentForm/commentForm.styles.ts
=> ISSUE #2185 - Add character counter and abbreviate screenshot url in comments

backend/models/modelSetting.js, backend/models/project.js, backend/routes/model.js, backend/routes/project.js, backend/test/integrated/collaboration.js, backend/test/integrated/project.js, frontend/modules/userManagement/userManagement.constants.ts, frontend/modules/userManagement/userManagement.redux.ts, frontend/modules/userManagement/userManagement.sagas.ts, frontend/routes/components/permissionsTable/permissionsTable.component.tsx, frontend/routes/modelsPermissions/modelsPermissions.component.tsx, frontend/routes/projects/projectsPermissions/projectsPermissions.component.tsx, frontend/services/api/models.ts, frontend/services/api/projects.ts
=> ISSUE #2139 - Fix permissions update in user management

frontend/helpers/html.ts, frontend/routes/components/notifications/notifications.component.tsx, frontend/routes/components/panel/panel.component.tsx, frontend/routes/components/topMenu/components/mainMenu/mainMenu.component.tsx, frontend/routes/components/topMenu/components/mainMenu/mainMenuButton/mainMenuButton.component.tsx, frontend/routes/components/topMenu/topMenu.component.tsx, frontend/routes/components/treeList/treeList.component.tsx, frontend/routes/teamspaces/components/projectItem/projectItem.component.tsx, frontend/routes/teamspaces/components/teamspaceItem/teamspaceItem.component.tsx, frontend/routes/teamspaces/components/tooltipButton/tooltipButton.component.tsx, frontend/routes/teamspaces/teamspaces.component.tsx, frontend/routes/viewerGui/components/commentForm/commentForm.component.tsx, frontend/routes/viewerGui/components/compare/compare.component.tsx, frontend/routes/viewerGui/components/gis/gis.component.tsx, frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx, frontend/routes/viewerGui/components/groups/groups.component.tsx, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewerGui/components/issues/issues.component.tsx, frontend/routes/viewerGui/components/measurements/measurements.component.tsx, frontend/routes/viewerGui/components/panelButton/panelButton.component.tsx, frontend/routes/viewerGui/components/reportedItems/reportedItems.component.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx, frontend/routes/viewerGui/components/risks/risks.component.tsx, frontend/routes/viewerGui/components/sequences/sequences.component.tsx, frontend/routes/viewerGui/components/toolbar/toolbar.component.tsx, frontend/routes/viewerGui/components/tree/tree.component.tsx, frontend/routes/viewerGui/components/viewerPanel/viewerPanel.component.tsx, frontend/routes/viewerGui/components/views/components/viewItem/viewItem.component.tsx, frontend/routes/viewerGui/components/views/views.component.tsx, frontend/routes/viewerGui/viewerGui.component.tsx
=> Issue 2236 - Defined ids for html elements 

frontend/routes/components/viewsDialog/viewsDialog.component.tsx, frontend/routes/components/viewsDialog/viewsDialog.styles.ts, frontend/routes/teamspaces/components/modelGridItem/modelGridItem.component.tsx, frontend/routes/teamspaces/components/modelGridItem/modelGridItem.container.ts, frontend/routes/viewerGui/components/views/components/viewItem/viewItem.component.tsx
=> ISSUE #2260 - Add share button in teamspace views

frontend/routes/viewerGui/viewerGui.component.tsx
=> ISSUE #2264 - Disable Issue card auto load

backend/models/ticket.js
=> ISSUE #2232 - Fix broadcasted data for viewpoint update

frontend/modules/groups/groups.sagas.ts, frontend/routes/viewerGui/components/groups/components/groupDetails/groupDetails.component.tsx, frontend/routes/viewerGui/components/groups/groups.component.tsx, frontend/routes/viewerGui/components/groups/groups.styles.ts, frontend/routes/viewerGui/components/previewItemInfo/previewItemInfo.component.tsx, frontend/routes/viewerGui/components/previewItemInfo/previewItemInfo.styles.ts, frontend/routes/viewerGui/components/previewListItem/previewListItem.component.tsx
This fixes #2263 
- Disable actions hiding for group card
- Move remove group action inside group details
=> ISSUE #2263 - Group Card changes

backend/constants.js, backend/models/risk.js, backend/models/ticket.js, backend/routes/issue.js, backend/routes/risk.js, backend/test/helpers/risks.js, backend/test/integrated/issue.js, backend/test/integrated/risk.js, backend/utils.js
=> Issue #2241 - Search query parameters for issues and risks

frontend/routes/components/resources/attachResourcesDialog/attachResourcesDialog.component.tsx
=> ISSUE 2244 - URL check regex bug

.azure/build-and-deploy.yaml
This fixes #2282 
Typo in config file is putting files in the wrong place. This resolves that.
=> ISSUE #2282 update helm chart

frontend/helpers/comments.ts
=> ISSUE #2287 - handle null action value

frontend/helpers/colors.ts, frontend/helpers/groups.ts, frontend/helpers/viewpoints.ts, frontend/modules/issues/issues.sagas.ts, frontend/modules/risks/risks.sagas.ts, frontend/modules/viewpoints/viewpoints.redux.ts, frontend/modules/viewpoints/viewpoints.sagas.ts, frontend/modules/viewpoints/viewpoints.selectors.ts
=> Issue #2284 - Removed unnecessary fetchs for viewpoints groups

frontend/routes/app/app.component.tsx
=> ISSUE #2215 - Fixed navigation

backend/models/invitations.js, frontend/routes/components/permissionsTable/permissionsTable.component.tsx
=> ISSUE 2294 - user management bug fixes

backend/models/ticket.js, backend/models/viewpoint.js, backend/test/integrated/issue.js, backend/test/integrated/risk.js, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetails.component.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetails.component.tsx, frontend/services/api/default.ts
=> ISSUE #2237 - Fix screenshots updating

backend/models/ticket.js, frontend/modules/sequences/sequences.sagas.ts, frontend/modules/sequences/sequences.selectors.ts
=> Issue 2305 - 4.11.1 bug fixes

frontend/modules/sequences/sequences.sagas.ts, frontend/modules/viewpoints/viewpoints.redux.ts, frontend/modules/viewpoints/viewpoints.sagas.ts, frontend/routes/app/app.component.tsx, frontend/routes/viewerGui/components/views/components/presetViews/presetViews.component.tsx, frontend/routes/viewerGui/components/views/views.component.tsx, frontend/routes/viewerGui/components/views/views.container.ts
=> ISSUE #2309 - Fixed bugs 4.11.2

frontend/modules/activities/activities.sagas.ts
This fixes #2320
- use sequence model ID instead of current model ID
=> Issue 2320 - fix api error when opening an activity within a federation

frontend/modules/sequences/sequences.redux.ts, frontend/modules/sequences/sequences.sagas.ts, frontend/modules/sequences/sequences.selectors.ts
=> ISSUE #2327 - Fixed flashing of frame states in sequences

.azure/Docker/Dockerfile
This fixes #2337 
set the folder to be owned by root but group permissions let node read
Everything should work as normal but be more secure.
=> #2337 updated dockerfile to remove write

frontend/routes/viewerGui/components/tree/components/treeNode/treeNode.styles.ts, frontend/routes/viewerGui/components/tree/tree.component.tsx
=> ISSUE #2173 - Fix showing multi-select cursor on tree panel

frontend/modules/tree/tree.sagas.ts
=> ISSUE #1426 - Disable clearing selection on background click when accum mode on

frontend/routes/components/intercom/intercom.component.tsx
=> ISSUE #2360 - Removed fixed left aligment in intercom

frontend/modules/board/board.sagas.ts, frontend/modules/risks/risks.selectors.ts
=> Issue 2357 - Fixed risk not showing the correct data in kanban board

frontend/modules/issues/issues.selectors.ts, frontend/modules/risks/risks.selectors.ts, frontend/routes/board/board.helpers.tsx, frontend/routes/components/filterPanel/filterPanel.component.tsx, frontend/routes/viewerGui/components/groups/groups.component.tsx, frontend/routes/viewerGui/components/issues/issues.container.ts, frontend/routes/viewerGui/components/listNavigation/listNavigation.component.tsx, frontend/routes/viewerGui/components/reportedItems/reportedItems.component.tsx, frontend/routes/viewerGui/components/risks/risks.container.ts
=> Issue #2350 - Filter menus issues with dates

frontend/routes/login/login.component.tsx
=> ISSUE #2363 - Fixed redirect with query params

frontend/routes/app/app.component.tsx, frontend/routes/login/login.component.tsx, frontend/routes/login/login.container.ts
=> ISSUE #2369 - Fixed race condition that caused public pages to lose the messagge

backend/models/scene.js, backend/test/integrated/scene.js
=> ISSUE 2400 - Get mesh bug and tests

backend/models/role.js
=> ISSUE #2383 - Removed mongoose from model/role

frontend/modules/jobs/jobs.redux.ts, frontend/routes/jobs/jobs.component.tsx, frontend/routes/jobs/jobs.container.ts
=> ISSUE #2399 - Fix fetching of jobs on teamspace change 

frontend/modules/board/board.selectors.ts, frontend/modules/issues/issues.selectors.ts, frontend/modules/risks/risks.selectors.ts
=> ISSUE 2442 - Fixed showing void risks in kanban board e

backend/models/accountPermissions.js, backend/models/group.js, backend/models/user.js, frontend/modules/teamspaces/teamspaces.sagas.ts, frontend/routes/components/dialogContainer/components/suggestedTreatmentsDialog/suggestedTreatmentsDialog.component.tsx
This fixes #2455
Fix bugs detailed in bug list
=> Issue 2455 4.13.2 bug list

.azure/build-and-deploy.yaml
This fixes #2468
- Updated helm chart reference
SSLs automatically generated should match configuration.
=> ISSUE #2468 - M7 Pen Test use of wildcard SSL

backend/VERSION.json
This fixes #2497
add powerbi to versioning endpoint
=> ISSUE #2497 add powerbi to versioning

.azure/build-and-deploy.yaml
This fixes #2499 
- Added tags to build command
=> ISSUE #2499 update build to include tags

backend/models/user.js, backend/models/userBilling.js, backend/routes/auth.js, frontend/modules/auth/auth.sagas.ts
=> ISSUE 2505 - Hotfix for T&Cs and billing

.azure/build-and-deploy.yaml
=> #2510 update helm chart to 0.10.6

backend/models/helper/model.js, backend/response_codes.js
This fixes #2519
new error code added in bouncer for identifying geometry that cannot be processed
=> ISSUE #2519 add new error code

backend/models/unit.js, frontend/constants/model-parameters.ts
This fixes #2526
- Changed order of model units
Check order of units.
=> ISSUE #2526 - fix unit selection order to metric first

frontend/index.html, frontend/styles/global.ts
This fixes #2530 
Please see comments in issue. In particular: https://github.com/3drepo/3drepo.io/issues/2530#issuecomment-801071587
=> ISSUE #2530 - static pages print bug

backend/models/issue.js, backend/models/risk.js, backend/test/integrated/issue.js, frontend/routes/viewerGui/components/issues/components/issueDetails/issueDetailsForm.component.tsx, frontend/routes/viewerGui/components/issues/components/mainIssueFormTab/mainIssueFormTab.component.tsx, frontend/routes/viewerGui/components/risks/components/mainRiskFormTab/mainRiskFormTab.component.tsx, frontend/routes/viewerGui/components/risks/components/riskDetails/riskDetailsForm.component.tsx, frontend/routes/viewerGui/components/updateButtons/updateButtons.component.tsx
=> ISSUE 2528 - allow commenter to change issue/risk pin/viewpoint

.gitattributes
This fixes #2575 
<!-- Add a high level description of the changes made (possibly quite similar to task list if it was a feature) 
e.g.
- Added azure pipeline to take the staging branch during merges.
- shouldn't accept changes on branches in future, and changes will need to be made directly on the staging branch in future for updates
=> ISSUE #2575 - add .azure/build-and-deploy.yaml to .gitattributes 

frontend/modules/viewerGui/viewerGui.sagas.ts
=> ISSUE #2598 - Fix fetching data during model loading

.travis.yml, backend/test/integrated/notifications.js, backend/test/integrated/upload.js
This fixes #2605
- commented out unstable notification tests
- commented out front end tests
- rejigged .travis.yml to run linter/type check as a separate job (so they can be ran in parallel
nothing should be affected, the tests should hopefully pass 100% now.
=>  Issue 2605 comment out unstable tests

scripts/db_migrations/v4.16/fixSequencesActivities.py, scripts/db_migrations/v4.16/removeOldActivitiesFiles.py
This fixes #2607 
- Fixed the dry run for fixSequencesActivities.py and removeOldActivitiesFiles.py
- Added a little more information when running a dry run of  fixSequencesActivities.py
- Run fixSequencesActivities.py with the the sixth parameter to true (or with just 5 parameters) to run in dryrun mode
- Run removeOldActivitiesFiles.py with the the sixth parameter to true (or with just 5 parameters) to run in dryrun mode
=> ISSUE #2607 - Fixed dryrun for sequence migration scripts

frontend/routes/components/screenshotDialog/components/tools/tools.styles.ts
=> ISSUE #2522 - Fix hiding of disabled screenshot tools

backend/models/user.js
This fixes #2626 
- Changed User.addTeamMember to accept email as well as username.
- In the frontend in usermanagement add a team member using an existing email in the system
=> ISSUE #2626 - Added support for adding team members by email

frontend/routes/components/screenshotDialog/components/drawingHandler/handleCalloutDrawing/handleCalloutDrawing.component.tsx
=> ISSUE #2565 - Make callout text background white

backend/models/user.js
This fixes #2644
cherry picked changes from #2626 to create a hotfix
This feature should work like staging.
=> ISSUE #2644 - Added support for adding team members by email (hotfix)

frontend/routes/login/login.component.tsx, frontend/routes/passwordChange/passwordChange.component.tsx, frontend/routes/profile/components/passwordChangeForm.component.tsx, frontend/routes/signUp/signUp.component.tsx
=> ISSUE #2563 - change autocomplete attributes

backend/models/project.js
=> ISSUE #2561 - Return project id in proper format after creating it

backend/package.json
This fixes #2664
remove deasync from package.json. it's not used.
=> ISSUE #2664 remove deasync from dependency

backend/models/user.js, backend/utils.js
This fixes #1914
Email verification token Id reduced from 128 chars to 32 chars and a method for generating random ids is added to utils to be reused by other places
=> ISSUE_1914 - Email Verification token reduced in size and reusable method for ID added

frontend/routes/viewerGui/components/pinButton/pinButton.component.tsx
=> ISSUE #2673 - Fixed blank page on existing an issue after clicking add pin

backend/routes/auth.js
This fixes #2675
- use `sessionCheck` instead of relying on whether `req.session` exists when we check if someone's logged in.
- test case identified in the issue should now work
=> ISSUE #2675 fix flickering on custom domain

frontend/routes/modelSettings/modelSettings.component.tsx
This fixes #2270
- enabled editing of Unit field
=> ISSUE #2270 - Allow editing of Units in Model Settings

.travis.yml
This fixes #2702
- make travis use focal
- use mongo provided by travis
- travis should pass as before
=> Issue 2702 focal update

frontend/src/v4/styles/global.ts
=> ISSUE #2726 - Fixed background colour

backend/src/v4/models/view.js
This fixes #2794
The bug was introduced due to the screenshot endpoint was always returning the screenshot within the first viewpoint (i.e. the issue screenshot).
This was due to views.js was doing a `findOne` directly to mongo api instead of going through the `db.js` interface, and the parameters have changed when the driver was upgraded
NOTE: i didn't change everything to use the api in `db.js` as that would take too long and considering we're moving to v5, this part of the code will be rewritten anyway.
screenshot endpoint should now return the correct image.
=> Issue 2794 - fix screenshot endpoint returning incorrect screenshot

backend/src/v4/config.js, backend/src/v4/handler/db.js
=> ISSUE #2860 - MongoDB replicaset

backend/src/v4/config.js, backend/src/v4/handler/db.js
This fixes #2860
essentially the same PR as https://github.com/3drepo/3drepo.io/pull/2861, but we're merging to master for a hotfix
=> Issue 2860 - Replica set connection fix (merging to master)

.azure/build-and-deploy.yaml
This fixes #2884
Helm chart updated
Branches operational with replicaset.
=> ISSUE #2884 - bump helm chart

frontend/src/v5/services/intl.ts
This fixes #2893
- Added handling of formatjs error messages
=> ISSUE #2893 - Removed unwanted warning from formatjs when the selected language is english

.azure/build-and-deploy.yaml, backend/src/v4/handler/db.js
This fixes #2917
Cherry picked 26569045cacc43b6d174d612f3890d1de7608ff8 to master
=> ISSUE #2917 password is encoded before log in to allow @ symbol in it

backend/src/v5/routes/teamspaces/projects/containers/containers.js, backend/src/v5/routes/teamspaces/projects/federations/federations.js, backend/src/v5/services/swagger/swagger.schemas.js
This fixes #2966 
Replaced float with number
- pass validation in https://editor.swagger.io/ for https://staging.dev.3drepo.io/docs/openapi.json
=> #2966 replace float with number

backend/src/v5/services/swagger/swagger.schemas.js
This fixes #2964 
Resolved the formatting
=> ISSUE #2964 replace newline with br

backend/src/v4/mailer/templates/importError.js
This fixes #2969 
Added the correlation ID to the subject line
Email sent with new subject line
=> #2969 add corID to subject line

backend/src/v4/mailer/templates/importError.js
This fixes #2990
- swap corId to account
=> ISSUE #2990 corId -> account on subject line for import errors

frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationListItem/federationEllipsisMenu/federationEllipsisMenu.component.tsx, frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationListItem/federationListItem.component.tsx
This fixes #
- Fixed label;
- Share federation triggers the share modal
=> ISSUE #2999 - fix share federation

frontend/src/v5/ui/components/shared/projectNavigation/index.ts, frontend/src/v5/ui/components/shared/projectNavigation/projectNavigation.component.tsx, frontend/src/v5/ui/components/shared/projectNavigation/projectNavigaton.styles.ts, frontend/src/v5/ui/routes/dashboard/projects/header/header.component.tsx
=> ISSUE #2957 - Renamed topNavigation to projectNavigation

backend/src/v4/models/invitations.js
This fixes #3010
- moved index creation to when the file is executed (i.e. init)
- removed write concern specification
- sign up should no longer error
- create invitations should still work
=> ISSUE #3010 create index at init, remove primary write concern

backend/src/v4/handler/elastic.js
This fixes #3037 
- changed submission method
- added more detailed logging output
Can submit with a reduced api key
=> ISSUE #3037 - update elastic method

backend/src/v4/handler/elastic.js
This fixes #3041
- added licenseKey field to elastic record, read from repoLicense config file.
- elastic records created if configured regardless of the license key configuration.
=> #3041 Add license key to elastic

tools/release/git_release.py
This fixes #3046 
Removed lines 70-75
unused tags will not be updated.
=> #3046 remove unused tagging

backend/src/v4/services/chat.js, frontend/.eslintrc.js, frontend/package.json, frontend/src/main.tsx, frontend/src/v5/services/api/default.ts, frontend/src/v5/services/realtime/federation.events.ts, frontend/src/v5/services/realtime/realtime.service.ts, frontend/src/v5/store/federations/federations.redux.ts, frontend/src/v5/store/federations/federations.types.ts, frontend/src/v5/ui/routes/dashboard/projects/federations/federations.component.tsx, frontend/yarn.lock
This fixes #3003 
- Provides a way to subscribe to realtime events
- Added an example of how to use it in federations
=> ISSUE #3003 - Realtime service for v5 

.azure/build-and-deploy.yaml
This fixes #3076
Updated helm chart
Deployment successful.
=> #3076 - update helm version and chart to current values

frontend/src/v4/routes/profile/components/apiKeyForm.component.tsx
This fixes #3126
- API key is now hidden
=> ISSUE #3126 - hide API key

backend/package.json, backend/yarn.lock
This fixes #3151
Upgraded the elastic modules
Service boots and reports to elastic properly
=> Issue 3151 - Elastic modules upgrade

backend/src/v4/handler/elastic.js
This fixes #3198 again
- reverted document level change, and changed the mapping. 
- login records created correctly.
=> #3198 - revert document change, changed mapping instead

frontend/src/v4/routes/components/textField/textField.component.tsx
This fixes #3218
- fixes bug in v4 viewer where viewing the issue window caused a crash
- View the issue window in v4 viewer
=> ISSUE #3218 - prevent crash in v4 viewer

frontend/src/v4/routes/components/dialogContainer/components/dialog/dialog.component.tsx, frontend/src/v5/ui/themes/theme.ts
This fixes #3246 
- Fixed error when trying to open a different modal that is not an alert modal
=> ISSUE #3246 - Fixed error when trying to update the screenshot in v5

frontend/src/v4/routes/components/starIcon/starIcon.styles.ts, frontend/src/v4/routes/viewerGui/components/bim/bim.component.tsx, frontend/src/v5/ui/v4Adapter/overrides/bim.overrides.ts, frontend/src/v5/ui/v4Adapter/v4Overrides.styles.ts
This fixes #3225
- Adds styling to the BIM card in the v5 viewer
- Open the BIM viewer.
- Click different segments
- Favourite/Unfavourite items
=> ISSUE #3225 - Viewer facelift - BIM Card

frontend/src/v5/ui/v4Adapter/overrides/cards/issues/sequences.overrides.ts
This fixes #3244
Added margin between tabs and the 4d fields
=> ISSUE #3244 - add spacing between tabs and 4d fields

frontend/src/v5/ui/v4Adapter/overrides/leftPanel.overrides.ts, frontend/src/v5/ui/v4Adapter/overrides/panelsMenu.overrides.ts
This fixes #3264 
The border radius of the right panel now matches the left panel one.
The height of the search bar was fixed
=> ISSUE #3264 - Adjust panels border radius and searchbar height

frontend/src/v4/services/api/default.ts, frontend/src/v5/services/api/default.ts, frontend/src/v5/services/routing/routing.tsx, frontend/src/v5/store/auth/auth.redux.ts, frontend/src/v5/store/auth/auth.sagas.ts, frontend/src/v5/store/auth/auth.selectors.ts, frontend/src/v5/ui/components/authPage/authPage.component.tsx, frontend/src/v5/ui/routes/dashboard/index.tsx, frontend/src/v5/ui/routes/index.tsx, frontend/yarn.lock
This fixes #3220 
- Added a new `<AuthenticatedRoute />` component that redirect to login if the user is not authenticated and sets the returnURL
- Now after login the user gets redirected to returnURL
=> Issue 3220 - Authenticated routes and redirection refactored

frontend/src/v4/routes/components/filterPanel/filterPanel.styles.ts
This fixes #3169
Removed the gap in the v4 viewer suggestions list
=> ISSUE #3169 - fix gap in v4

config/test/config.js, config/testV5/config.js
This fixes #3412
Using a new set of ethereal credentials for testing
v5 test suite should now pass again
=> ISSUE #3412 update credentials for tests

frontend/src/v5/ui/routes/userSignup/userSignupWelcome/userSignupWelcome.styles.ts
This fixes #3352
Too long email does not overflow its container
=> ISSUE #3352 - fix email verification overflow

frontend/src/v5/services/intl.ts, frontend/src/v5/services/realtime/federation.events.ts, frontend/src/v5/services/realtime/realtime.service.ts, frontend/src/v5/store/federations/federations.types.ts, frontend/src/v5/ui/routes/dashboard/projects/containers/containers.component.tsx, frontend/src/v5/ui/routes/dashboard/projects/federations/federations.component.tsx, frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationListItem/federationListItem.component.tsx
This fixes #3345 
- Added the realtime event subscription when a federation was processed
=> ISSUE #3345 - Added realtime event for new federation revision

.azure/destroy.yaml
This fixes #3477
- Fixed the use of multiple conditions, it wasn't expanding correctly as it appeared it should by the documentation
- should work now
=> #3477 - destroy pipeline operating correctly now

frontend/src/v5/store/federations/federations.sagas.ts, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListHeaderLabel/dashboardListHeaderLabel.component.tsx, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemButton/dashboardListItemButton.component.tsx, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemText/dashboardListItemText.component.tsx, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemContainerTitle/dashboardListItemContainerTitle.component.tsx, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemFederationTitle/dashboardListItemFederationTitle.component.tsx, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemTitle.component.tsx, frontend/src/v5/ui/components/shared/revisionDetails/components/revisionsListHeaderLabel/revisionsListHeaderLabel.component.tsx, frontend/src/v5/ui/components/shared/revisionDetails/components/revisionsListItem/revisionsListItem.component.tsx, frontend/src/v5/ui/components/shared/revisionDetails/components/revisionsListItem/revisionsListItem.styles.ts, frontend/src/v5/ui/components/shared/revisionDetails/components/revisionsListItemAuthor/revisionsListItemAuthor.component.tsx, frontend/src/v5/ui/components/shared/revisionDetails/components/revisionsListItemButton/revisionsListItemButton.styles.ts, frontend/src/v5/ui/components/shared/revisionDetails/components/revisionsListItemCode/revisionsListItemCode.component.tsx, frontend/src/v5/ui/components/shared/revisionDetails/components/revisionsListItemText/revisionsListItemText.component.tsx, frontend/src/v5/ui/components/shared/revisionDetails/components/revisionsListItemText/revisionsListItemText.styles.ts, frontend/src/v5/ui/components/shared/revisionDetails/revisionDetails.component.tsx, frontend/src/v5/ui/components/shared/revisionDetails/revisionDetails.styles.ts, frontend/src/v5/ui/controls/fixedOrGrowContainer/fixedOrGrowContainer.component.tsx, frontend/src/v5/ui/controls/fixedOrGrowContainer/fixedOrGrowContainer.styles.ts, frontend/src/v5/ui/controls/fixedOrGrowContainer/index.ts
This fixes #3455
- Aligned description column in revision list.
- Fixed ellipsis in description in revision list.
- Added the capability to set the width of the columns in percentage units.
=> Issue 3455 - Description column aligned

frontend/src/v5/store/currentUser/currentUser.redux.ts
This fixes #
Rewrite redux file to use immer
=> ISSUE #3549 - Rewrite redux file to use Immer.js: CurrentUser

frontend/src/v5/store/containers/containers.redux.ts
This fixes #3548 
Containers redux file uses Immer
=> Issue 3548 - Rewrite redux file to use Immer.js: Containers

frontend/src/v5/store/federations/federations.redux.ts
This fixes #3550 
Redux file now uses Immer
=> Issue 3550 - Rewrite redux file to use Immer.js: Federations

frontend/src/v5/store/users/users.redux.ts
This fixes #3553
Rewrite redux file to use Immer
=> ISSUE #3553 - Rewrite redux file to use Immer.js: Users

frontend/src/v5/store/revisions/revisions.redux.ts, frontend/test/revisions/revisions.store.spec.ts
This fixes #3552 
Re-write redux file
=> ISSUE #3552 - Rewrite redux file to use Immer.js: Revisions

frontend/src/v4/constants/viewerGui.ts, frontend/src/v4/routes/viewerGui/viewerGui.component.tsx, frontend/src/v5/ui/components/viewer/cards/card.styles.ts, frontend/src/v5/ui/components/viewer/cards/cardContent.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/tickets.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/tickets.tsx
This fixes #3582 
-  Added a version of the cards just for v5 components
=> Issue 3582 - V5 Card, tickets example

backend/src/v5/middleware/dataConverter/inputs/users.js, backend/src/v5/utils/webRequests.js, backend/tests/v5/unit/middleware/dataConverter/inputs/users.test.js, backend/tests/v5/unit/utils/webRequests.test.js
This fixes #3592
Captcha post request now is made with url-encoded params and works properly 
In v5 (capctha enabled) sign up using the UI
The account should be successfully created
=> ISSUE #3592 - Captcha Bug fix 

frontend/src/v5/ui/components/viewer/cards/cardContext.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/tickets.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/tickets.constants.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsListCard.component.tsx
This fixes #3656
- Provided a way to switch card views inside the same card and pass data
- Added an example for this in the ticket's card
=> ISSUE #3656 - Created a card context to switch card views and pass data between them

config/testV5/config.js
This fixes #3669
Refresh credentials to make the tests working again
=> Issue 3669 update test credentials

frontend/src/v5/services/api/tickets.ts, frontend/src/v5/store/tickets/tickets.redux.ts, frontend/src/v5/store/tickets/tickets.sagas.ts, frontend/src/v5/store/tickets/tickets.selectors.ts, frontend/src/v5/store/tickets/tickets.types.ts, frontend/src/v5/ui/routes/viewer/tickets/tickets.component.tsx, frontend/test/tickets/tickets.sagas.spec.ts, frontend/test/tickets/tickets.store.spec.ts
This fixes #3666 
- Added fetch ticket integration/test/example
- Added update ticket  integration/test/example
- Added create ticket  integration/test/example
- Added fetch template  integration/test/example
=> Issue 3666 - Integration with all the missing tickets api

.azure/Docker/Dockerfile
This fixes #3744
- Added less to image
- less is present as a command
=> #3744 added less to container

.github/workflows/automaticTesting.yml
This fixes #3809
- changed github action runner to supported combination
- the backend test cases =D
=> ISSUE_3809 - backend test runner OS change

frontend/src/v5/ui/routes/dashboard/projects/settingsForm/settingsForm.component.tsx, frontend/src/v5/validation/containerAndFederationSchemes/settingsSchemes.ts, frontend/src/v5/validation/containerAndFederationSchemes/validators.ts
This fixes #3803 
- GIS values do not accept text inputs
- GIS values are not required and can be empty (if so they are mapped to 0)
=> Issue 3803 - GIS fields are not required and refuse text inputs

frontend/src/v4/constants/routes.ts, frontend/src/v4/modules/dialog/dialog.redux.ts, frontend/src/v4/modules/viewerGui/viewerGui.sagas.ts
This fixes #3768
Redirect to teamspace now redirects to the actual teamspace where the error was raised
See the issue #3768
=> ISSUE #3768 - fix redirect to teamspace dialog in v5 

frontend/src/v5/ui/controls/searchSelect/searchSelect.component.tsx
This fixes #3770 
The searchbar now keeps the focus while typing
=> Issue 3770 - Searchbar in multiselect loses focus

backend/src/v4/models/user.js
This fixes #3900 
Should fix local install with admin in users
=> ISSUE #3900 - return if TS settings missing in listAccounts

frontend/src/v5/ui/controls/searchSelect/searchSelect.component.tsx, frontend/src/v5/ui/controls/searchSelect/searchSelect.styles.ts
This fixes #3907 
The search input is sticky and the whole box comes with a max height
Edit the assignees list
=> ISSUE #3907 - Search Select shows about 6 items at most

frontend/src/v5/store/currentUser/currentUser.selectors.ts, frontend/src/v5/ui/components/intercom/intercom.component.tsx
This fixes #3954
Intercom should work as usual
1) Log in, refresh the page, the intercom should still be there
2) Click on the intercom, the content should load correctly
=> ISSUE #3954 - fix intercom

backend/src/scripts/migrations/5.0.2/addVertexCountsToSuperMeshBSONs.js, backend/src/scripts/migrations/5.0.2/index.js
This fixes #3961
- added a migration script to pull out the vertice count of supermeshes from `m_map`.
Verified working with @mosment3DRepo
=> Issue 3961 - add migration script to 

backend/tests/v5/scripts/modelProcessing/resetProcessingFlags.test.js, backend/tests/v5/scripts/users/removeUnverifiedUsers.test.js
This fixes #4052
disconnect from DB for the tests that needs them to ensure jest doesn't hang
backend tests should now pass
=> ISSUE #4052 disconnect from db after tests

backend/src/v5/routes/teamspaces/projects/models/common/general.js
This fixes #4054 
- fix v5 docs
=> ISSUE 4054 - fix docs

frontend/src/v5/store/federations/federations.selectors.ts, frontend/src/v5/ui/routes/viewer/checkLatestRevisionReadiness/checkLatestRevisionReadiness.container.tsx, frontend/src/v5/ui/routes/viewer/viewer.tsx
…ners
This fixes #4057 
- Cherry picked fix from #3931
=> ISSUE #4057 - Release candidate 5.0.7

frontend/src/v5/ui/routes/dashboard/projects/containers/uploadFileForm/uploadList/uploadListItem/components/uploadListItemDestination/uploadListItemDestination.component.tsx
This fixes #4021
As an admin, you could not upload to containers
Go to a project where you are the admin and try to upload
=> ISSUE #4021 - show containers in upload revision autosuggest list

.github/workflows/chatOperations.yml
This fixes #4214
- Adding the ability to trigger workflow dispatch from chat operations
/deploy issues deploy-command workflow dispatch
/destroy issues destroy-command workflow dispatch
=> #4214 add chatOperations workflow

frontend/src/v5/ui/controls/inputs/datePicker/baseCalendarPicker/baseCalendarPicker.component.tsx, frontend/src/v5/ui/controls/inputs/inputController.component.tsx
This fixes #4107
Test all the properties, in particular date, text, and numberfield
=> Issue 4107 - Changing tickets correctly sets the value of properties

frontend/src/v5/services/actionsDispatchers.ts, frontend/src/v5/store/federations/federations.sagas.ts, frontend/src/v5/store/viewer/viewer.redux.ts, frontend/src/v5/store/viewer/viewer.sagas.ts, frontend/test/containers/containers.fixtures.ts, frontend/test/federations/federations.fixtures.ts, frontend/test/test.helpers.ts, frontend/test/viewer/viewer.sagas.spec.ts, frontend/test/viewer/viewer.store.spec.ts
This fixes #4114 
- Added a new saga testing framework
- Added tests for viewer
- Fixed a bug in viewer sagas
=> Issue 4114 - Improved saga testing and added tests for viewer (v5)

frontend/src/globals/unity-util.ts, frontend/src/v4/helpers/pins.ts, frontend/src/v4/routes/viewerCanvas/viewerCanvas.component.tsx, frontend/src/v4/services/viewer/viewer.tsx, frontend/src/v5/store/tickets/card/ticketsCard.selectors.ts, frontend/src/v5/store/viewer/viewer.sagas.ts, frontend/src/v5/ui/components/viewer/cards/tickets/pinDetails/pinDetails.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/tickets.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/properties.helper.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketItem/ticketItem.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsListCard.component.tsx, frontend/src/v5/ui/routes/viewer/viewer.tsx
This fixes #4128 
- Now the custom tickets pins appear on the model load
- Clicking on a custom ticket pin opens the card with the ticket info
- Clicking on the background deselect the pins and cancel actions in the pin card (in the case you were creating a new ticket it gets canceled)
=> Issue 4128 - Clicking on custom ticket pins

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/basicComment/basicComment.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/commentMarkDown/commentMarkDown.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/commentReply/commentReply.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/commentReply/commentReply.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/currentUserComment/currentUserComment.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/comment/quotedMessage/quotedMessage.styles.ts
This fixes #4122
- User can mock quoted messages
- The author (You) appears when a user replies to their own messages 
- Create a quoted comment
- Reply to your own comment
- Have another user replying to your own comment
=> Issue 4122 - comments improvement

frontend/src/v5/store/dialogs/dialogs.redux.ts
This fixes #4136
Remove dependency in Redux dialogs
=> ISSUE #4136 - remove redux dependency in dialogs

frontend/src/v5/ui/routes/login/login.component.tsx
This fixes #4144
On normal login, SSO params are cleared out
=> ISSUE #4144 - clear SSO params on normal login

.azure/build-and-deploy.yaml, .azure/build.yaml, .azure/destroy.yaml
This fixes #4199
updated settings
=> ISSUE 4199 - fix CI/CD

.azure/build-and-deploy.yaml
=> ISSUE 4240 - update chart to use netapp

frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx, frontend/src/v5/ui/routes/viewer/viewer.tsx
This fixes #4236 
Removed the ticket state being reset upon clicking viewer background
Open a ticket
Click the background
You are still there
=> ISSUE #4236 - Clicking on the background of the viewer is kicking the user out of custom ticket details

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/chipRule/chipRule.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/chipRule/chipRule.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
This fixes #4268
Editing/Creating group rules is disabled for non admin users
=> Issue 4268 - Readonly smart groups rules in group form

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/addOrEditGroup/groupSettingsForm.component.tsx/groupsCollectionSelect/groupsCollectionSelect.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/newCollectionForm/newCollectionForm.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/newCollectionForm/newCollectionForm.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx, frontend/src/v5/validation/groupSchemes/groupSchemes.ts
This fixes #4272
Add functionality to the "create collection" button
=> Issue 4272 - Custom Ticket:Group - Create Collection

frontend/src/v4/modules/board/board.selectors.ts
This fixes #4192 
- Added the six week column for kanban board
=> ISSUE #4192 - Added the six weeks column for kanban board

frontend/src/v4/helpers/pins.ts, frontend/src/v4/modules/issues/issues.selectors.ts, frontend/src/v4/modules/risks/risks.selectors.ts, frontend/src/v4/routes/viewerCanvas/viewerCanvas.component.tsx, frontend/src/v4/services/viewer/viewer.tsx, frontend/src/v5/ui/components/viewer/cards/tickets/pinDetails/pinDetails.component.tsx
This fixes #4301
- Fixed edit pin
- Fixed some bad selectors that added the pin twice
- Fixed some pin selection weirdness
=> ISSUE #4301 - Fixed edit pin not working

frontend/src/v5/ui/controls/inputs/datePicker/baseCalendarPicker/baseCalendarPicker.component.tsx
This fixes #4323 
-  Fixed clear date on custom tickets
=> ISSUE #4323 - Fixed clear date on custom tickets

frontend/assets/icons/controls/clear_circle.svg.tsx, frontend/src/v5/ui/controls/inputs/colorPicker/colorPickerPalette/colorPickerPalette.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/rulesField/ruelsField.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/rulesField/rulesField.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/rulesOptionsMenu/rulesOptionsMenu.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/rulesOptionsMenu/rulesOptionsMenu.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesForm.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesForm.helpers.ts, frontend/src/v5/validation/groupSchemes/groupSchemes.ts
This fixes #4329
Added ellipsis menu that allows to copy/paste/clear all the rules
=> Issue 4329 - Custom Ticket: Groups copy/paste rules  

frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
This fixes #4327 
The event remover was not being called with the right function to remove
=> Issue 4327 - Clicking on the background does not clear highlighted objects

frontend/src/v4/routes/components/invitationDialog/invitationDialog.component.tsx, frontend/src/v4/routes/components/newUserForm/newUserForm.component.tsx
This fixes #4380 
Opening the user invitation modal with "isAdmin" ticked allows to submit straight away
Try to send an invitation using different combinations of:
- user is admin (checked/unchecked)
- email (valid/invalid)
=> Issue 4380 - Issue adding new user admin

backend/src/scripts/migrations/5.4/mergeSceneBinaries.js
This fixes #4407
split processing to revisions to avoid running out of memory on the sorting.
should work as before
=> ISSUE #4407 - process each revision separately

frontend/src/main.tsx
This fixes #4411
Redux was being loaded after rendering
Access V4
=> ISSUE #4411 - load redux before rendering

frontend/src/v5/ui/v4Adapter/overrides/inviteUserForm.overrides.ts
This fixes #3941 
Fixed unassigned job
=> ISSUE #3941 - unassigned job stretches to full width

frontend/src/v5/validation/userSchemes/validators.ts
This fixes #3912 
The username validator has been updated to reflect the backend's one
=> ISSUE #3912 - fix username validator

frontend/src/v5/ui/components/shared/breadcrumbsRouting/breadcrumbsRouting.component.tsx
This fixes #4431
Sort breadcrumbs elements
Test breadcrumbs with lower/uppercase and weird options
=> ISSUE #4431 - sort breadcrumbs

frontend/src/v5/ui/v4Adapter/overrides/panelsMenu.overrides.ts
This fixes #3695 
Viewer buttons have new colours
Open the viewer and check the colour of the buttons when:
- selected;
- hovered;
- normal
=> ISSUE #3695 - update viewer buttons colours

frontend/src/v4/constants/viewer.ts, frontend/src/v4/modules/viewer/viewer.sagas.ts, frontend/src/v4/modules/viewer/viewer.selectors.ts, frontend/src/v4/routes/components/topMenu/components/visualSettingsDialog/visualSettingsDialog.component.tsx, frontend/src/v4/services/viewer/viewer.tsx
This fixes #4374
From visual settings you can change unity bg color
Go to visual settings and change the bg color
=> ISSUE #4374 - Visual settings: add the ability to change unity bg

backend/src/v4/routes/model.js, backend/src/v4/routes/risk.js
This fixes #2262
Corrections in swagger documentation
=> ISSUE #2262 - Corrections in swagger documentation

frontend/package.json
This fixes #4483
- Added circular:testt back to package.json
- Added circular:test call to lint
=> ISSUE #4483 - Getting back circular test to package.json

frontend/src/v5/store/tickets/tickets.selectors.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx
This fixes #4482 
- The ticket groups no longer get stuck "loading"
- Modified the selectTickets selector so that it attaches the group objects (similar to how the selectTicketById selector works)
Test that they load when using a ticket link
=> ISSUE #4482 - Fix ticket groups not loading

frontend/package.json, frontend/yarn.lock
This fixes #4520
- updated postcss
=> ISSUE #4520 - Bump postcss from 8.2.15 to 8.4.31

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/propertiesList.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketsTopPanel/IssuePropertiesRow/issuePropertiesRow.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketsTopPanel/ticketsTopPanel.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketsTopPanel/ticketsTopPanel.styles.ts
This fixes #4582
The issue properties bar has been moved
See how it looks when it is rendered with and without properties below
=> ISSUE 4582 - Move issue properties bar after description

frontend/src/v5/helpers/viewpoint.helpers.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
This fixes #4613 
- When you try to show a viewpoint and it has no groups and no camera and no clipping planes, just ignore it.
=> ISSUE 4613 - Now gotoviewpoint only shows it if there's relevant data

frontend/jest.config.js, frontend/src/v5/helpers/functions.helpers.ts, frontend/src/v5/services/intl.ts, frontend/src/v5/store/containers/containers.redux.ts, frontend/src/v5/store/containers/containers.sagas.ts, frontend/src/v5/store/viewer/viewer.sagas.ts, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardList.component.tsx, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListCollapse/dashboardListCollapse.component.tsx, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListCollapse/dashboardListCollapse.styles.ts, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemContainerTitle/dashboardListItemContainerTitle.component.tsx, frontend/src/v5/ui/components/dashboard/dashboardList/useOrderedList/useOrderedList.helpers.ts, frontend/src/v5/ui/components/dashboard/dashboardList/useOrderedList/useOrderedList.hooks.ts, frontend/src/v5/ui/controls/search/searchContext.tsx, frontend/src/v5/ui/controls/virtualList/virtualList.component.tsx, frontend/src/v5/ui/routes/dashboard/projects/containers/containers.component.tsx, frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containerListItem/containerEllipsisMenu/containerEllipsisMenu.component.tsx, frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containerListItem/containerListItemLoading.component.tsx, frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/containersList.component.tsx, frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederationContainersList/editFederationContainersList.component.tsx, frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederationContainersList/editFederationContainersListItem/editFederationContainersListItemLoading.component.tsx, frontend/src/v5/ui/routes/viewer/viewer.tsx
This fixes #4625
- Can support more than 1000 containers
=> Issue 4625 - Virtualized list for containers

.azure/build-and-deploy.yaml
This fixes #4692 
- Hotjar config
Upon successful linkage you should be able to see data coming through https://help.hotjar.com/hc/en-us/articles/360016303294-How-to-Check-That-Hotjar-Is-Working
=> ISSUE 4692 - Hotjar config

backend/VERSION.json
This fixes #4750
- Remove old version from support, forcing all users to current version
=> ISSUE 4750 - remove old version from supported list

backend/src/v5/middleware/dataConverter/inputs/teamspaces/projects/models/commons/utils.js, backend/src/v5/models/tickets.comments.js, backend/src/v5/models/tickets.js, backend/src/v5/processors/teamspaces/projects/models/commons/tickets.comments.js, backend/src/v5/processors/teamspaces/projects/models/commons/tickets.js, backend/src/v5/routes/teamspaces/projects/models/common/tickets.comments.js, backend/src/v5/routes/teamspaces/projects/models/common/tickets.js, backend/src/v5/utils/helper/yup.js, backend/tests/v5/e2e/routes/teamspaces/projects/models/common/tickets.comments.test.js, backend/tests/v5/e2e/routes/teamspaces/projects/models/common/tickets.test.js, backend/tests/v5/helper/services.js, backend/tests/v5/unit/middleware/dataConverter/inputs/teamspaces/projects/models/commons/utils.test.js, backend/tests/v5/unit/models/tickets.comments.test.js, backend/tests/v5/unit/models/tickets.test.js, backend/tests/v5/unit/processors/teamspaces/projects/models/commons/tickets.comments.test.js, backend/tests/v5/unit/processors/teamspaces/projects/models/commons/tickets.test.js, backend/yarn.lock
This fixes #4767
- `sortBy`, `sortDesc` query string added to comment list and ticket list endpoints
- when applied, the data will be sorted by the speciifed property, in desc/asec order
- NOTE: `sortDesc` is ignored if `sortBy` is not specified
- `updatedSince` query string added to  comment list and ticket list endpoints
- only tickets/comments updated since a certain date is returned.
- Ticket List:
- `sortBy`, `sortDesc` should work on any properties/module properties
- `updatedSince` should only return tickets that has been updated since the specified time
- Comment list:
- `sortBy`, `sortDesc` should work on any comment properties
- `updatedSince` should only return comments that has been updated since the specified time
=> Issue 4767 -  ticket list / comment list endpoint enhancements

frontend/src/v5/store/tickets/tickets.types.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/properties/coordsProperty/coordsProperty.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/propertiesList.component.tsx
This fixes #4752
Adds immutable properties functionality to the front end. Immutable properties cannot be edited once they are set (however they can be edited indefinitely whilst still in ticket creation).
Note: It is not possible to make it work using `field.value` in **InputController.component**. This value updates on key press, not on blur, so for text inputs it would only let you enter 1 letter. Also `field.value` can be undefined on first render even if it should have a value. This prevents you from using react useState to set the input to disabled onBlur and using useEffect to set it disabled on render.
<details>
<summary>Try this template:</summary>
```
{
"modules": [
{
"name": "immutable properties",
"properties": [
{
"type": "boolean",
"default": false,
"immutable": true, …
```
=> ISSUE #4752 - Custom Tickets: support immutable properties frontend

frontend/src/v5/helpers/syncProps.hooks.ts, frontend/src/v5/ui/components/shared/modalsDispatcher/modalsDispatcher.component.tsx
This fixes #4823 
- Added a mechanism to keep the props up to date for a dispatched modal
=> ISSUE #4823 - Added some hooks to keep the modals updated with props

backend/src/v5/schemas/tickets/templates.constants.js
This fixes #4887
Approved At changed to a date inside clash module
=> ISSUE #4887 change approved at to be a date in clash module

backend/src/v5/schemas/tickets/templates.js, backend/tests/v5/helper/services.js, backend/tests/v5/unit/schemas/tickets/templates.test.js
This fixes #4922
Limit is now set to 15
=> ISSUE #4922 set custom status values limit to 15

backend/src/v5/models/modelSettings.constants.js
This fixes #4968 
Adds an error message for code 37 from bouncer, which indicates a NWD or DWG that has encryption/password protection enabled.
=> ISSUE #4968 Added new error code

.travis.yml, backend/src/v4/middlewares/checkPermissions.js
This fixes #5033
Refactored multiple models middleware to facilitate patch requests on multiple models
case mentioned in the APT ticket should now be resolved.
=> ISSUE #5033 refactor multiple models middleware

.travis.yml, backend/src/v4/models/job.js, backend/tests/v4/integrated/job.js, frontend/src/v4/helpers/colors.ts, frontend/src/v4/modules/jobs/jobs.sagas.ts
This fixes #5034
- frontend and backend validation on hex colours
Case mentioned in APT 315 should now be resolved
=> Issue 5034 - addresses APT 315

.travis.yml
This fixes #5070 
- Update e-mail
- Travis e-mail should be updated
=> ISSUE 5070 - Update Travis e-mail

frontend/src/v4/services/viewer/viewer.tsx, frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemTitle.styles.ts, frontend/src/v5/ui/routes/dashboard/projects/drawings/drawingsList/drawingsListItem/drawingsListItemTitle/drawingsListItemTitle.component.tsx
This fixes #5080
Minor UI Fixes for milestone 1
- Filter the dashboards. The list item titles should not be broken up by the highlight
=> ISSUE #5080 - Milestone 1 - UI fixes

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/commentsPanel/createCommentBox/createCommentBox.component.tsx
This fixes #5101
Allow ticket comments to take 2d screenshots
Try to take a 2d screenshot from a ticket comment
=> ISSUE #5101 - comment can upload both 2d and 3d screenshots

.azure/build-and-deploy.yaml
This fixes #5115 
- drawingq support
- drawingq support
=> ISSUE 5115 - bump chart to 5.11.2

backend/src/v4/models/intercom.js, backend/src/v4/models/user.js, backend/src/v5/models/users.js, backend/src/v5/processors/users.js, backend/tests/v5/unit/models/users.test.js, backend/tests/v5/unit/processors/users.test.js
This fixes #5134 
- Additional attributes for Intercom contact
- Should appear in Intercom
=> ISSUE 5134 - Update Intercom createContact attributes

frontend/test/drawings/drawings.store.spec.ts
This fixes #5171 
- fixed drawing test
- added a test for ddrawing order
=> ISSUE #5171 - fixed drawing test added a test for ddrawing order

.azure/build-and-deploy.yaml, backend/package.json, backend/yarn.lock
This fixes #5166
- Upgrade to latest 4.7.3
- Check APM on Elastic Cloud
=> ISSUE 5166 - Upgrade APM dep

frontend/src/v4/modules/viewpoints/viewpoints.sagas.ts, frontend/src/v4/routes/viewerGui/components/views/views.component.tsx, frontend/src/v4/routes/viewerGui/components/views/views.container.ts
This fixes #5220 
Setting the viewpoint was not setting the clipping mode
Test tickets with different views
=> ISSUE #5143 - clipping state is broken

.azure/build-and-deploy.yaml
This fixes #5278 
- Update to latest chart version
- CronJobs should run on specific branches instead of all
=> ISSUE 5278 - Update deployment Helm chart

backend/package.json, backend/src/v4/services/queue.js, backend/yarn.lock
This fixes #5296 
Update backend dependencies as described
should work as before
=> ISSUE #5296 update dependencies

frontend/.vscode/launch.json, frontend/src/v5/helpers/colors.helper.ts, frontend/src/v5/ui/controls/inputs/colorPicker/colorPicker.component.tsx
This fixes #5348 
- Support new error codes
- Add a new coloured group to a ticket
=> ISSUE #5348 - Fixed bad default value for colorpicker

frontend/src/v5/ui/components/authTemplate/authTemplate.styles.ts, frontend/src/v5/ui/components/shared/appBar/notifications/notifications.styles.ts, frontend/src/v5/ui/routes/dashboard/projects/calibration/calibrationHeader/calibrationHeader.styles.ts, frontend/src/v5/ui/routes/dashboard/teamspaces/teamspaceLayout/teamspaceLayout.styles.ts, frontend/src/v5/ui/themes/theme.ts, frontend/stories/containers/CentredContainer.stories.tsx
This fixes #5346 
- Removed  gradient as part of the palette (slider would try to process this colour and light it up which results on an error trying to parse the gradient as a colour)
- Changed references to palette gradient to just the GRADIENT const
- Trying to select a secuence works
- Trying to the change the alpha when selecting a colour works (like in groups)
=> ISSUE #5346 - Changed palette definition because it would throw an error in the slider

frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/addOrEditGroup/groupSettingsForm/groupsCollectionSelect/groupsCollectionSelect.component.tsx, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/addOrEditGroup/groupSettingsForm/groupsCollectionSelect/groupsCollectionSelect.styles.ts, frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx
This fixes #5351 
- Changed  the way selection looks for collections in ticket groups
=> ISSUE #5351 - Fixed selection of collection in groups

backend/src/v4/models/project.js, backend/src/v4/routes/project.js, backend/tests/v4/integrated/project.js
This fixes #5382
list models in a project v4 endpoint is reinstated
The endpoint should now be available again.
=> ISSUE #5382 reinstate project model list endpoint

frontend/src/v5/ui/components/viewer/cards/cardFilters/cardFilters.helpers.ts, frontend/src/v5/ui/components/viewer/cards/cardFilters/filterChip/filterChip.component.tsx, frontend/src/v5/ui/components/viewer/cards/cardFilters/filterForm/filterFormValues/filterFormValues.component.tsx, frontend/src/v5/ui/controls/inputs/booleanSelect/booleanSelect.component.tsx, frontend/src/v5/ui/controls/inputs/formInputs.component.tsx, frontend/src/v5/validation/ticketSchemes/validators.ts
This fixes #5371
Added boolean filters
Test boolen filters
=> ISSUE #5371 - Ticket filters: boolean filters

backend/src/v4/models/project.js, backend/src/v4/routes/project.js, backend/src/v5/middleware/common.js, backend/src/v5/utils/responseCodes.js, backend/tests/v4/integrated/project.js, backend/tests/v5/unit/middleware/common.test.js
This fixes #5388
- decommissioned list model endpoint
- added middleware from #5339 to deal with decommissioned endpoints
- list model endpoint should nwo return with a 410 error telling the user where is the new endpoint
=> Issue 5388 - remove list model v4 endpoint

.azure/build-and-deploy.yaml, .azure/build.yaml, .azure/destroy.yaml, .github/workflows/automaticTesting.yml, .travis.yml, backend/jest-mongodb-config.js
This fixes #5414 
- Stop using Ubuntu 20.04
=> ISSUE 5414 - Update Ubuntu for runners

backend/src/v4/response_codes.js
This fixes #5418
- The session manager is stuck in a weird state that is struggling to connect to mongo through the provided connection.
- This situation doesn't trigger mongo-connect's autoReconnect mechanism, and there is no way to manually replace the connection (see https://github.com/jdesboeufs/connect-mongo/issues/485)
- So instead, I added in a kill switch to just kill off the application (following the unhandled promise rejection route), which in a deployment would kill the pod and generate a new one.
- in the mentioned situation, the 2nd request should now kill off the server.
- An email should be generated to explain the situation
=> ISSUE #5418 kill the server if we run into Topology is closed

backend/src/scripts/utility/users/identifyInactiveUsers.js, backend/src/scripts/utility/users/identifyOrphanedUsers.js
This fixes #5445 
- Handles missing `billing` from `customData`
=> ISSUE 5445 - Fix user utility scripts

backend/src/v5/services/mailer/templates/html/baseTemplate.html, backend/src/v5/services/mailer/templates/html/systemTemplate.html
This fixes #5459
- Match Frontegg CSS fixes
- Update footer
=> ISSUE 5459 - update e-mail template

.travis.yml
This fixes #5530
Fix issue with travis failing due to rabbitmq install would be a downgrade
=> ISSUE #5530 add flag to allow downgrades when installing rabbitmq

frontend/src/v4/modules/compare/compare.sagas.ts
This fixes #5512
Instead of throwing an error, the containers  simply won't be included as part of the diffing items (Note that they are not hidden, but filtered out)
Provided a federation with 2 containers (`containerA` with viewer+ access and `containerB` with unassigned access)
=> ISSUE #5512 - Compare feature broke with insufficient permissions

backend/src/v4/config.js
This fixes #5546
set maxAge back to 3hrs
=> ISSUE #5546 change back to 3 hrs

backend/src/v5/models/modelSettings.constants.js
This fixes #
Updates the error codes to match those from the latest version of bouncer.
=> ISSUE #5557 updated error codes from bouncer

frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederationContainersList/editFederationContainersList.component.tsx
This fixes #5608 
- Fixed list not updating when fetching the containers
=> ISSUE #5608 - Fix not changing status state for containers in edit federations

.azure/build-and-deploy.yaml
This fixes #5657
Update chart to 5.19.0, which contains configuration updates to connect to all 3 nodes in the mongo replica
=> ISSUE #5657 update helm chart to support connecting to the full replica set
